<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:29:58 +0000
// --------------------------------------------------------------------------------

$l['report_reasons'] = 'Motivos de reportar';
$l['report_reasons_desc'] = 'Aqui você pode criar e gerenciar motivos que podem ser selecionados quando os usuários denunciam conteúdo.';
$l['add_new_reason'] = 'Adicionar novo motivo';
$l['add_new_reason_desc'] = 'Adicione um novo motivo para que os usuários selecionem ao informar o conteúdo.';
$l['edit_reason'] = 'Editar motivo';
$l['edit_reason_desc'] = 'Edite um motivo para os usuários selecionar ao informar o conteúdo.';
$l['applies_to'] = 'Aplica para';
$l['order'] = 'Ordem';
$l['extra_comment'] = 'Requer comentário?';
$l['options'] = 'Opções';
$l['delete_reason'] = 'Deletar motivo';
$l['no_report_reasons'] = 'Não há motivos de reportar no seu fórum neste momento.';
$l['reason_title'] = 'Título';
$l['reason_title_desc'] = 'Digite o título do motivo para informar o conteúdo.';
$l['requires_extra'] = 'Requer um comentário extra?';
$l['requires_extra_desc'] = 'Exigir que o usuário insira um comentário adicional quando esse motivo for selecionado?';
$l['save_reason'] = 'Salvar motivo';
$l['content_colon'] = 'Conteúdo';
$l['all_content'] = 'Todo conteúdo';
$l['select_content'] = 'Selecionar conteúdo';
$l['report_content_'] = 'Nenhum';
$l['report_content_all'] = 'Todos';
$l['report_content_post'] = 'Mensagem';
$l['report_content_profile'] = 'Perfil';
$l['report_content_reputation'] = 'Reputação';
$l['report_reason_rules'] = 'Quebrar as regras do fórum';
$l['report_reason_bad'] = 'Conteúdo inapropriado';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_wrong'] = 'Fórum incorreto';
$l['report_reason_other'] = 'Outro';
$l['default_report_reason'] = 'Padrão';
$l['custom_report_reason'] = 'Customizado';
$l['update_reasons_order'] = 'Atualizar Ordem de Motivos';
$l['error_cannot_modify_reason'] = 'Você não pode modificar esse motivo.';
$l['error_cannot_delete_reason'] = 'Você não pode deletar esse motivo.';
$l['error_invalid_reason'] = 'Você selecionou um motivo inválido';
$l['error_missing_title'] = 'Você não inseriu um título por esse motivo.';
$l['error_missing_extra'] = 'Você não selecionou se você deseja informações extras por esse motivo.';
$l['success_reasons_disporder_updated'] = 'As ordens de exibição do motivo do relatório foram atualizadas com sucesso.';
$l['success_reason_created'] = 'O motivo foi criado com sucesso.';
$l['success_reason_updated'] = 'O motivo foi atualizado com sucesso.';
$l['success_reason_deleted'] = 'O motivo foi excluído com sucesso.';
$l['confirm_reason_deletion'] = 'Tem certeza de que deseja excluir esse motivo?';
