<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:44:42 +0000
// --------------------------------------------------------------------------------

$l['custom_profile_fields'] = 'Campos de Perfil Customizados';
$l['custom_profile_fields_desc'] = 'Esta seção permite que você edite, exclua e ainda gerencie seus campos de perfil customizados.';
$l['add_profile_field'] = 'Adicionar Campo de Perfil';
$l['add_new_profile_field'] = 'Adicionar Novo Campo de Perfil';
$l['add_new_profile_field_desc'] = 'Aqui você pode adicionar um novo campo de perfil customizado.';
$l['edit_profile_field'] = 'Editar Campo de Perfil';
$l['edit_profile_field_desc'] = 'Aqui você pode editar um campo de perfil customizado.';
$l['title'] = 'Título';
$l['short_description'] = 'Descrição Curta';
$l['maximum_length'] = 'Tamanho Máximo';
$l['maximum_length_desc'] = 'Este é o número máximo de caracteres que podem ser digitados. Somente se aplica a caixas de texto e campos de texto.';
$l['field_length'] = 'Tamanho do Campo';
$l['field_length_desc'] = 'Este é o tamanho do campo. Somente se aplica a caixa de seleção simples ou múltiplas.';
$l['display_order'] = 'Ordem de Visualização';
$l['display_order_desc'] = 'Esta é a ordem que os campos customizados serão mostrados na tela. Este número não pode ser repetido.';
$l['text'] = 'Campo de Texto';
$l['textarea'] = 'Área de Texto';
$l['select'] = 'Caixa de Seleção';
$l['multiselect'] = 'Caixa de Seleção Múltipla';
$l['radio'] = 'Botões de Rádio';
$l['checkbox'] = 'Botões de Opção';
$l['field_type'] = 'Tipo de Campo';
$l['field_type_desc'] = 'Este é o tipo de campo que será mostrado.';
$l['selectable_options'] = 'Opções Selecionáveis?';
$l['selectable_options_desc'] = 'Por favor informe cada opção em uma linha separada. Isto somente se aplica a caixas de seleção, botões de opção e botões de rádio.';
$l['required'] = 'Requerido?';
$l['required_desc'] = 'Será obrigatório preencher este campo durante o registro ou ao editar o perfil? Note que isto não se aplica se o campo for oculto.';
$l['editable_by_user'] = '';
$l['editable_by_user_desc'] = '';
$l['hide_on_profile'] = '';
$l['hide_on_profile_desc'] = '';
$l['min_posts_enabled'] = 'Mínimo de respostas?';
$l['min_posts_enabled_desc'] = 'Exibir este campo somente para usuários com um certo total de respostas? Se sim, defina o total de respostas desejado.';
$l['save_profile_field'] = 'Salvar Campo de Perfil';
$l['name'] = 'Nome';
$l['id'] = '';
$l['editable'] = 'Editável?';
$l['hidden'] = '';
$l['edit_field'] = 'Editar Campo';
$l['delete_field'] = 'Excluir Campo';
$l['no_profile_fields'] = 'Não existem campos de perfil customizados no momento.';
$l['error_missing_name'] = 'Você não informou um título para este campo de perfil customizado';
$l['error_missing_description'] = 'Você não informou uma descrição para este campo de perfil customizado';
$l['error_missing_filetype'] = '';
$l['error_missing_required'] = '';
$l['error_missing_editable'] = '';
$l['error_missing_hidden'] = '';
$l['error_invalid_fid'] = 'O campo de perfil selcionado não existe.';
$l['success_profile_field_added'] = 'O campo de perfil customizado foi criado com sucesso.';
$l['success_profile_field_saved'] = 'O campo de perfil customizado foi salvo com sucesso.';
$l['success_profile_field_deleted'] = 'O campo de perfil customizado foi excluído com sucesso.';
$l['confirm_profile_field_deletion'] = 'Tem certeza que deseja excluir este campo de perfil?';
$l['field_regex'] = 'Expressão regular';
$l['field_regex_desc'] = 'Digite uma expressão regular que deve ser correspondida da entrada do usuário. Você deve certificar-se de que a expressão regular é válida e segura - nenhuma validação é realizada. Vazio para qualquer coisa. <br />
<strong> Exemplo: </strong> ([a-z0-9 _ \\ -,. +] +)';
$l['show_on_registration'] = 'Mostrar no registro?';
$l['show_on_registration_desc'] = 'Este campo deve aparecer no formulário de inscrição? Observe que isso não se aplica se o campo não for editável. Os campos que são necessários sempre aparecerão no registro.';
$l['display_on_profile'] = 'Exibir no perfil?';
$l['display_on_profile_desc'] = 'Esse campo deve ser exibido no perfil do usuário? Isso não se aplica aos administradores / moderadores.';
$l['display_on_postbit'] = 'Exibir na visualização de mensagem?';
$l['display_on_postbit_desc'] = 'Esse campo deve ser exibido nas postagens do usuário?';
$l['viewableby'] = 'Visível por';
$l['viewableby_desc'] = 'Selecione os grupos permitidos para visualizar este campo de perfil.';
$l['editableby'] = 'Editável por';
$l['editableby_desc'] = 'Selecione os grupos permitidos para editar este campo de perfil.';
$l['parser_options'] = 'Opções do Analisador';
$l['parse_allowhtml'] = 'Sim, permita HTML neste campo de perfil.';
$l['parse_allowmycode'] = 'Sim, permita MyCode neste campo de perfil.';
$l['parse_allowsmilies'] = 'Sim, permita Smiles neste campo de perfil.';
$l['parse_allowimgcode'] = 'Sim, permita [img] neste campo de perfil.';
$l['parse_allowvideocode'] = 'Sim, permita [video] neste campo de perfil.';
$l['registration'] = 'Registro?';
$l['profile'] = 'Perfil?';
$l['postbit'] = 'Visualização de mensagem?';
