<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:38:03 +0000
// --------------------------------------------------------------------------------

$l['languages'] = 'Idiomas';
$l['languages_desc'] = 'Os idiomas instalados no seu fórum são mostrados abaixo. Você pode editar os arquivos, editar com outro idioma ou editar as propriedades do idioma.';
$l['find_language_packs'] = 'Encontrar Pacotes de Idioma';
$l['language_files'] = 'Arquivos de Idioma';
$l['language_files_desc'] = 'Abaixo estão os arquivos do idioma selecionado para o fórum e para o Admin CP. Você pode editá-los, se desejar.';
$l['quick_phrases'] = 'Frases Rápidas';
$l['quick_phrases_desc'] = 'Acesso rápido a frases mais normalmente modificadas.';
$l['edit_with'] = 'Editar com {1}';
$l['edit_language_variables'] = 'Editar Variáveis de Idioma';
$l['edit_language_variables_desc'] = 'Aqui é possível editar as variáveis de idioma.';
$l['edit_properties_desc'] = 'Aqui é possível editar as propriedades de um pacote de idioma.';
$l['installed_language_packs'] = 'Pacotes de Idioma Instalados';
$l['front_end'] = 'Fórum';
$l['admin_cp'] = 'Admin CP';
$l['save_language_file'] = 'Salvar Arquivo de Idioma';
$l['nav_editing_set'] = 'Editando Propriedades do Idioma';
$l['edit_properties'] = 'Editar Propriedades do Idioma';
$l['friendly_name'] = 'Nome Amigável';
$l['language_in_html'] = 'Idioma em tag &lt;html&gt;';
$l['charset'] = 'Codificação';
$l['admin'] = 'Possui variáveis de idioma do Admin CP?';
$l['rtl'] = 'Direita-Para-Esquerda?';
$l['quickphrases_agreement'] = 'Termo de Registro - Título';
$l['quickphrases_agreement_1'] = 'Termo de Registro - Parágrafo 1';
$l['quickphrases_agreement_2'] = 'Termo de Registro - Parágrafo 2';
$l['quickphrases_agreement_3'] = 'Termo de Registro - Parágrafo 3';
$l['quickphrases_agreement_4'] = 'Termo de Registro - Parágrafo 4';
$l['quickphrases_agreement_5'] = 'Termo de Registro - Parágrafo 5';
$l['quickphrases_error_nopermission_guest_1'] = 'Sem Permissão - Parágrafo 1';
$l['quickphrases_error_nopermission_guest_2'] = 'Sem Permissão - Parágrafo 2';
$l['quickphrases_error_nopermission_guest_3'] = 'Sem Permissão - Parágrafo 3';
$l['quickphrases_error_nopermission_guest_4'] = 'Sem Permissão - Parágrafo 4';
$l['no_languages'] = 'Nenhum Idioma';
$l['no_language_files_front_end'] = 'Nenhum arquivo de idioma do fórum encontrado.';
$l['no_language_files_admin_cp'] = 'Nenhum arquivo de idioma do Admin CP encontrado.';
$l['error_invalid_set'] = 'Idioma inválido especificado.';
$l['error_invalid_file'] = 'Arquivo de Idioma inválido especificado.';
$l['error_cannot_write_to_file'] = 'Não é possível gravar no arquivo.  Verifique as permissões do arquivo e tente novamente';
$l['alert_note_cannot_write'] = 'Antes de editar um arquivo de idioma, verifique as permissões do mesmo para ser possível gravar no mesmo.';
$l['success_langfile_updated'] = 'O arquivo de idioma foi atualizado com sucesso.';
$l['success_langprops_updated'] = 'As propriedades do idioma foram atualizadas com sucesso.';
$l['success_quickphrases_updated'] = 'As frases rápidas de idioma foram atualizadas com sucesso.';
$l['error_folders_fail'] = 'Ocorreu um problema ao acessar pastas de pacotes de idiomas solicitados. Certifique-se de que eles existem e podem ser gravados.';
$l['issues'] = 'Problemas';
$l['phrases'] = 'Frases';
$l['issues_ok'] = 'Parece que tudo deveria estar certo aqui.';
$l['issues_nothingtocompare'] = 'Não há nada para comparar aqui.';
$l['issues_warning'] = 'Este arquivo pode exigir sua atenção.
Certifique-se de verificar isso.';
