<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:25:55 +0000
// --------------------------------------------------------------------------------

$l['security_questions'] = 'Perguntas de segurança';
$l['security_questions_desc'] = 'Aqui você pode criar e gerenciar questões de segurança que serão exibidas aleatoriamente durante o registro.';
$l['add_new_question'] = 'Adicionar nova pergunta';
$l['add_new_question_desc'] = 'Adicione uma pergunta e suas respostas para as perguntas de segurança a serem usadas durante o registro.';
$l['edit_question'] = 'Editar pergunta';
$l['edit_question_desc'] = 'Aqui você edita uma pergunta de segurança.';
$l['options'] = 'Opções';
$l['shown'] = 'Mostrando';
$l['correct'] = 'Correto';
$l['incorrect'] = 'Incorreto';
$l['disable_question'] = 'Desabilitar pergunta';
$l['enable_question'] = 'Habilitar pergunta';
$l['delete_question'] = 'Excluir pergunta';
$l['no_security_questions'] = 'Não há perguntas de segurança no seu fórum neste momento.';
$l['question'] = 'Pergunta';
$l['question_desc'] = 'Digite a pergunta que você deseja responder durante o registro.';
$l['answers'] = 'Resposta(s)';
$l['answers_desc'] = 'Digite a(s) resposta(s) à pergunta acima. Digite cada resposta em uma linha separada.';
$l['active'] = 'Ativo';
$l['save_question'] = 'Salvar pergunta';
$l['error_invalid_question'] = 'Você selecionou uma pergunta inválida.';
$l['error_missing_question'] = 'Você não inseriu uma pergunta para esta pergunta';
$l['error_missing_answer'] = 'Você não inseriu nenhuma resposta para esta pergunta';
$l['success_question_created'] = 'A questão foi criada com sucesso.';
$l['success_question_updated'] = 'A questão foi atualizada com sucesso.';
$l['success_question_disabled'] = 'A questão foi desabilitada com sucesso.';
$l['success_question_enabled'] = 'A questão foi ativada com sucesso.';
$l['success_question_deleted'] = 'A questão foi excluída com sucesso.';
$l['confirm_question_deletion'] = 'Tem certeza de que deseja excluir esta questão?';
