<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:40:32 +0000
// --------------------------------------------------------------------------------

$l['configuration'] = 'Definições do Sistema';
$l['bbsettings'] = 'Configurações';
$l['banning'] = 'Banimento';
$l['custom_profile_fields'] = 'Campos de Perfil';
$l['smilies'] = 'Emoticons';
$l['word_filters'] = 'Filtros de Palavras';
$l['mycode'] = 'MyCode';
$l['languages'] = 'Idiomas';
$l['post_icons'] = 'Ícones de Resposta';
$l['help_documents'] = 'Documentos de Ajuda';
$l['plugins'] = 'Plugins';
$l['attachment_types'] = 'Tipos de Anexos';
$l['moderator_tools'] = 'Moderação';
$l['spiders_bots'] = 'Robôs/Buscadores';
$l['calendars'] = 'Calendários';
$l['warning_system'] = 'Sistema de Alerta';
$l['thread_prefixes'] = 'Prefixos de Tópico';
$l['can_manage_settings'] = 'Pode gerenciar ajustes?';
$l['can_manage_banned_accounts'] = 'Pode gerenciar contas banidas?';
$l['can_manage_custom_profile_fields'] = 'Pode gerenciar campos de perfil personalizados?';
$l['can_manage_smilies'] = 'Pode gerenciar emoticons?';
$l['can_manage_bad_words'] = 'Pode gerenciar filtros de palavras?';
$l['can_manage_custom_mycode'] = 'Pode gerenciar MyCode customizado?';
$l['can_manage_language_packs'] = 'Pode gerenciar pacotes de idioma?';
$l['can_manage_post_icons'] = 'Pode gerenciar ícones de respostas?';
$l['can_manage_help_documents'] = 'Pode gerenciar documentos de ajuda?';
$l['can_manage_plugins'] = 'Pode gerenciar plugins?';
$l['can_manage_attachment_types'] = 'Pode gerenciar tipos de anexos?';
$l['can_manage_spiders_bots'] = 'Pode gerenciar robôs/buscadores?';
$l['can_manage_calendars'] = 'Pode gerenciar calendários?';
$l['can_manage_warning_system'] = 'Pode gerenciar o sistema de alertas?';
$l['can_manage_mod_tools'] = 'Pode gerenciar as ferramentas de moderação?';
$l['can_manage_thread_prefixes'] = 'Pode gerenciar prefixos de tópico?';
$l['security_questions'] = 'Perguntas de segurança';
$l['report_reasons'] = 'Reportar Motivos';
$l['can_manage_security_questions'] = 'Pode gerenciar perguntas de segurança?';
$l['can_manage_report_reasons'] = 'Pode gerenciar motivos de report?';
