<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:41:51 +0000
// --------------------------------------------------------------------------------

$l['plugins'] = 'Plugins';
$l['plugins_desc'] = 'Esta seção permite instalar, ativar, desativar, desinstalar e gerenciar os plugins que você enviou para a pasta <strong>inc/plugins</strong> do seu fórum.';
$l['plugin_updates'] = 'Atualizações de Plugins';
$l['plugin_updates_desc'] = 'Esta seção permite verificar atualizações para todos os seus plugins.';
$l['browse_plugins'] = 'Explorar Plugins';
$l['browse_plugins_desc'] = 'Aqui é possível navegar pelo site oficial de modificações do MyBB e encontrar plugins compatíveis com esta instalação do MyBB.';
$l['browse_all_plugins'] = 'Explorar Todos os Plugins';
$l['plugin'] = 'Plugin';
$l['your_version'] = 'Sua Versão';
$l['latest_version'] = 'Versão Atual';
$l['download'] = 'Baixar';
$l['deactivate'] = 'Desativar';
$l['activate'] = 'Ativar';
$l['install_and_activate'] = 'Instalar e Ativar';
$l['uninstall'] = 'Desinstalar';
$l['created_by'] = 'Criado Por';
$l['no_plugins'] = 'Não existem plugins no fórum no momento.';
$l['plugin_incompatible'] = 'Este plugin é incompatível com o MyBB {1}';
$l['recommended_plugins_for_mybb'] = 'Plugins Recomendados para o MyBB {1}';
$l['browse_results_for_mybb'] = 'Explorar Resultados para o MyBB {1}';
$l['search_for_plugins'] = 'Pesquisar por Plugins';
$l['search'] = 'Pesquisar';
$l['error_vcheck_no_supported_plugins'] = 'Nenhum dos plugins instalados permite efetuar a verificação de versão.';
$l['error_vcheck_communications_problem'] = 'Ocorreu um problema de comunicação com o servidor de versões de modificações. Por favor tente novamente em alguns minutos.';
$l['error_no_input'] = 'Código de Erro 1: Nenhuma entrada especificada.';
$l['error_no_pids'] = 'Código de Erro 2: Nenhuma id de pluing especificada.';
$l['error_communication_problem'] = 'Ocorreu um problema de comunicação com o servidor de modificações. Por favor tente novamente em alguns minutos.';
$l['error_invalid_plugin'] = 'O plugin selecionado não existe.';
$l['error_no_results_found'] = 'Nenhum resultado encontrado para as palavras-chave usadas.';
$l['success_plugins_up_to_date'] = 'Parabéns, todos os seus plugins estão atualizados.';
$l['success_plugin_activated'] = 'O plugin selecionado foi ativado com sucesso.';
$l['success_plugin_deactivated'] = 'O plugin selecionado foi desativado com sucesso.';
$l['success_plugin_installed'] = 'O plugin selecionado foi instalado e ativado com sucesso.';
$l['success_plugin_uninstalled'] = 'O plugin selecionado foi desinstalado com sucesso.';
$l['active_plugin'] = 'Plugins ativos';
$l['inactive_plugin'] = 'Plugins inativos';
$l['no_active_plugins'] = 'Não há plugins ativos no seu fórum.';
$l['no_inactive_plugins'] = 'Não há plugins inativos no seu fórum.';
$l['error_vcheck_vulnerable'] = '[Plugin Vulnerável]:';
$l['error_vcheck_vulnerable_notes'] = 'Este envio foi marcado como vulnerável pela equipe do MyBB. Recomendamos a remoção completa desta modificação. Veja as notas abaixo:';
