<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:09:19 +0000
// --------------------------------------------------------------------------------

$l['today'] = '<span title="{1}">Hoje</span>';
$l['yesterday'] = '<span title="{1}">Ontem</span>';
$l['size_yb'] = 'YB';
$l['size_zb'] = 'ZB';
$l['size_eb'] = 'EB';
$l['size_pb'] = 'PB';
$l['size_tb'] = 'TB';
$l['size_gb'] = 'GB';
$l['size_mb'] = 'MB';
$l['size_kb'] = 'KB';
$l['size_bytes'] = 'bytes';
$l['na'] = 'N/A';
$l['mybb_admin_panel'] = 'Painel de Controle';
$l['mybb_admin_cp'] = 'Admin CP';
$l['logged_in_as'] = 'Logado como';
$l['view_board'] = 'Visualizar Fórum';
$l['logout'] = 'Sair';
$l['generated_in'] = 'Gerado em {1} com <a href="{2}" target="_blank">{3} queries</a>. Memória usada: {4}';
$l['enter_username_and_password'] = 'Por favor insira seu {1} e senha para continuar.';
$l['mybb_admin_login'] = 'Painel de Controle - Entrar';
$l['return_to_forum'] = 'Voltar ao Fórum';
$l['please_login'] = 'Por Favor, Faça Login';
$l['username'] = 'Login:';
$l['username1'] = 'Email:';
$l['username2'] = 'Nome de Usuário/Email:';
$l['password'] = 'Senha:';
$l['login'] = 'Logar';
$l['lost_password'] = 'Esqueceu a senha?';
$l['error_invalid_admin_session'] = 'Seção de administrador inválida';
$l['error_admin_session_expired'] = 'Sua seção de administrador expirou';
$l['error_invalid_ip'] = 'Seu endereço IP não é válido para esta seção';
$l['error_mybb_admin_lockedout'] = 'Esta conta foi bloqueada';
$l['error_mybb_admin_lockedout_message'] = 'Sua conta está bloqueada após {1} tentativas de login incorretas. Um email foi enviado a você com instruções sobre como desbloquear sua conta.';
$l['success_logged_out'] = 'Você saiu com sucesso.';
$l['error_invalid_username_password'] = 'A {1} e combinação de senha que você inseriu são inválidos.';
$l['confirm_action'] = 'Tem certeza que deseja executar esta ação?';
$l['home'] = 'Início';
$l['name'] = 'Nome';
$l['size'] = 'Tamanho';
$l['controls'] = 'Controles';
$l['view'] = 'Ver';
$l['yes'] = 'Sim';
$l['no'] = 'Não';
$l['cancel'] = 'Cancelar';
$l['options'] = 'Opções';
$l['proceed'] = 'Executar';
$l['ok'] = 'OK';
$l['error'] = 'Erro';
$l['edit'] = 'Editar';
$l['never'] = 'Nunca';
$l['legend'] = 'Legenda';
$l['version'] = 'Versão';
$l['languagevar'] = 'Idioma';
$l['use_default'] = 'Usar Padrão';
$l['file'] = 'Arquivo';
$l['go'] = 'Ok';
$l['clear'] = 'Limpar';
$l['unknown'] = 'Desconhecido';
$l['year'] = 'Ano';
$l['year_short'] = 'a';
$l['years'] = 'Anos';
$l['years_short'] = 'a';
$l['month'] = 'Mês';
$l['month_short'] = 'm';
$l['months'] = 'Meses';
$l['months_short'] = 'm';
$l['week'] = 'Semana';
$l['week_short'] = 's';
$l['weeks'] = 'Semanas';
$l['weeks_short'] = 's';
$l['day'] = 'Dia';
$l['day_short'] = 'd';
$l['days'] = 'Dias';
$l['days_short'] = 'd';
$l['hour'] = 'Hora';
$l['hour_short'] = 'h';
$l['hours'] = 'Horas';
$l['hours_short'] = 'h';
$l['minute'] = 'Minuto';
$l['minute_short'] = 'm';
$l['minutes'] = 'Minutos';
$l['minutes_short'] = 'm';
$l['second'] = 'Segundo';
$l['second_short'] = 's';
$l['seconds'] = 'Segundos';
$l['seconds_short'] = 's';
$l['permanent'] = 'Permanente';
$l['all_forums'] = 'Todos os Fóruns';
$l['mybb_acp'] = 'Admin CP';
$l['pages'] = 'Páginas';
$l['previous'] = 'Anterior';
$l['page'] = 'Página';
$l['next'] = 'Próximo';
$l['delete'] = 'Excluir';
$l['reset'] = 'Reiniciar';
$l['and'] = 'e';
$l['on'] = 'Sim';
$l['off'] = 'Não';
$l['quote'] = 'Citação:';
$l['wrote'] = 'Escreveu:';
$l['code'] = 'Código:';
$l['php_code'] = 'Código PHP:';
$l['linkback'] = 'Resposta Original';
$l['january'] = 'Janeiro';
$l['february'] = 'Fevereiro';
$l['march'] = 'Março';
$l['april'] = 'Abril';
$l['may'] = 'Maio';
$l['june'] = 'Junho';
$l['july'] = 'Julho';
$l['august'] = 'Agosto';
$l['september'] = 'Setembro';
$l['october'] = 'Outubro';
$l['november'] = 'Novembro';
$l['december'] = 'Dezembro';
$l['access_denied'] = 'Acesso Negado';
$l['access_denied_desc'] = 'Você não tem permissão para acessar esta parte do Admin CP.';
$l['cannot_perform_action_super_admin_general'] = 'Lamentamos, mas você não pode executar esta ação por que não é um super administrador.';
$l['loading_text'] = 'Loading<br />Favor Aguardar...';
$l['timezone_gmt_minus_1200'] = '(GMT -12:00)';
$l['timezone_gmt_minus_1100'] = '(GMT -11:00)';
$l['timezone_gmt_minus_1000'] = '(GMT -10:00)';
$l['timezone_gmt_minus_900'] = '(GMT -9:00)';
$l['timezone_gmt_minus_800'] = '(GMT -8:00)';
$l['timezone_gmt_minus_700'] = '(GMT -7:00)';
$l['timezone_gmt_minus_600'] = '(GMT -6:00)';
$l['timezone_gmt_minus_500'] = '(GMT -5:00)';
$l['timezone_gmt_minus_450'] = '(GMT -4:30)';
$l['timezone_gmt_minus_400'] = '(GMT -4:00)';
$l['timezone_gmt_minus_350'] = '(GMT -3:30)';
$l['timezone_gmt_minus_300'] = '(GMT -3:00) Hora Oficial de Brasília-DF';
$l['timezone_gmt_minus_200'] = '(GMT -2:00)';
$l['timezone_gmt_minus_100'] = '(GMT -1:00)';
$l['timezone_gmt'] = '(GMT) Lisboa';
$l['timezone_gmt_100'] = '(GMT +1:00)';
$l['timezone_gmt_200'] = '(GMT +2:00)';
$l['timezone_gmt_300'] = '(GMT +3:00)';
$l['timezone_gmt_350'] = '(GMT +3:30)';
$l['timezone_gmt_400'] = '(GMT +4:00)';
$l['timezone_gmt_450'] = '(GMT +4:30)';
$l['timezone_gmt_500'] = '(GMT +5:00)';
$l['timezone_gmt_550'] = '(GMT +5:30)';
$l['timezone_gmt_600'] = '(GMT +6:00)';
$l['timezone_gmt_700'] = '(GMT +7:00)';
$l['timezone_gmt_800'] = '(GMT +8:00)';
$l['timezone_gmt_900'] = '(GMT +9:00)(GMT +9:00) Osaka, Sapporo, Seoul, Tokyo, Irkutsk';
$l['timezone_gmt_950'] = '(GMT +9:30)';
$l['timezone_gmt_1000'] = '(GMT +10:00)';
$l['timezone_gmt_1100'] = '(GMT +11:00)';
$l['timezone_gmt_1200'] = '(GMT +12:00)';
$l['timezone_gmt_short'] = 'GMT {1}({2})';
$l['confirm_delete_logs'] = 'Remover as entradas de log selecionadas?';
$l['confirm_delete_all_logs'] = 'Remover todas as entradas de log?';
$l['selected_logs_deleted'] = 'As entradas de log selecionadas fora excluídas.';
$l['all_logs_deleted'] = 'Todas as entradas de log foram excluídas.';
$l['delete_selected'] = 'Excluir Selecionados';
$l['delete_all'] = 'Excluir Todos os Filtros';
$l['encountered_errors'] = 'Os seguintes erros foram encontrados:';
$l['invalid_post_verify_key'] = 'Uma falha no código de autorização ocorreu. Por favor confirme se deseja executar a ação abaixo.';
$l['invalid_post_verify_key2'] = 'Uma falha no código de autorização ocorreu. Por favor verifique se está acessando esta página corretamente.';
$l['forums_colon'] = 'Forums:';
$l['editor_title_bold'] = 'Inserir texto em negrito';
$l['editor_title_italic'] = 'Inserir texto em itálico';
$l['editor_title_underline'] = 'Inserir texto sublinhado';
$l['editor_title_left'] = 'Alinhar texto a esquerda';
$l['editor_title_center'] = 'Centralizar o texto';
$l['editor_title_right'] = 'Alinhar texto a direita';
$l['editor_title_justify'] = 'Justificar texto';
$l['editor_title_numlist'] = 'Inserir lista numerada';
$l['editor_title_bulletlist'] = 'Inserir lista de marcadores';
$l['editor_title_image'] = 'Inserir imagem';
$l['editor_title_hyperlink'] = 'Inserir link';
$l['editor_title_email'] = 'Inserir email';
$l['editor_title_quote'] = 'Inserir citação de texto';
$l['editor_title_code'] = 'Inserir código formatado';
$l['editor_title_php'] = 'Inserir código PHP formatado';
$l['editor_title_close_tags'] = 'Fechar qualquer tag MyCode que esteja aberta';
$l['editor_enter_list_item'] = 'Informe um item da lista. Clique cancelar ou deixe em branco para fechar a lista.';
$l['editor_enter_url'] = 'Por favor informe a URL do site.';
$l['editor_enter_url_title'] = 'Opcionalmente, você pode informar um título para a URL.';
$l['editor_enter_email'] = 'Por favor informe o email que deseja inserir.';
$l['editor_enter_email_title'] = 'Opcionalmente, você pode informar um título para o email.';
$l['editor_enter_image'] = 'Por favor informe o endereço URL da imagem que deseja inserir.';
$l['editor_enter_video_url'] = 'Por favor informe a URL do vídeo.';
$l['editor_video_dailymotion'] = 'Dailymotion';
$l['editor_video_metacafe'] = 'MetaCafe';
$l['editor_video_myspacetv'] = 'MySpace TV';
$l['editor_video_vimeo'] = 'Vimeo';
$l['editor_video_yahoo'] = 'Yahoo Video';
$l['editor_video_youtube'] = 'YouTube';
$l['editor_size_xx_small'] = 'Minúscuulo';
$l['editor_size_x_small'] = 'Muito Pequeno';
$l['editor_size_small'] = 'Pequeno';
$l['editor_size_medium'] = 'Médio';
$l['editor_size_large'] = 'Grande';
$l['editor_size_x_large'] = 'Muito Grande';
$l['editor_size_xx_large'] = 'Gigante';
$l['editor_font'] = 'Fonte';
$l['editor_size'] = 'Tamanho do Texto';
$l['editor_color'] = 'Cor do Texto';
$l['missing_task'] = 'Erro: Arquivo de tarefas não existe';
$l['task_backup_cannot_write_backup'] = 'Erro: A tarefa de backup do banco de dados não pode gravar no diretório de backups.';
$l['task_backup_ran'] = 'A tarefa de backup do banco de dados foi executada com sucesso.';
$l['task_checktables_ran'] = 'A tarefa de verificação de tabelas foi executada com sucesso e nenhuma tabela corrompida foi encontrada.';
$l['task_checktables_ran_found'] = 'Aviso: A tarefa de verificação de tabelas foi executada com sucesso e reparou {1} tabela(s).';
$l['task_dailycleanup_ran'] = 'A tarefa de limpeza diária foi executada com sucesso.';
$l['task_hourlycleanup_ran'] = 'A tarefa de limpeza horária foi executada com sucesso.';
$l['task_logcleanup_ran'] = 'A tarefa de limpeza de logs foi executada com sucesso e removeu logs antigos.';
$l['task_promotions_ran'] = 'A tarefa de promoções foi executada com sucesso.';
$l['task_threadviews_ran'] = 'A tarefa de visualização de tópicos foi executada com sucesso.';
$l['task_usercleanup_ran'] = 'A tarefa de limpeza de usuários foi executada com sucesso.';
$l['task_massmail_ran'] = 'A tarefa de email em massa foi executada com sucesso.';
$l['task_userpruning_ran'] = 'A tarefa de limpeza de usuários foi executada com sucesso.';
$l['task_delayedmoderation_ran'] = 'A tarefa de moderação agendada foi executada com sucesso.';
$l['task_massmail_ran_errors'] = 'Um ou mais problemas ocorreram ao enviar para "{1}":
{2}';
$l['massmail_username'] = 'Usuário';
$l['email_addr'] = 'Email';
$l['board_name'] = 'Nome do Fórum';
$l['board_url'] = 'Endereço do Fórum (URL)';
$l['lockout_unlock'] = 'Desbloquear o Admin CP';
$l['enter_username_and_token'] = 'Por favor informe seu nome de usuário e o código de ativação para continuar.';
$l['unlock_token'] = 'Código de Ativação:';
$l['unlock_account'] = 'Desbloquear Conta';
$l['locked_out_subject'] = 'Conta de Administrador Bloqueada em {1}';
$l['locked_out_message'] = '{1},

Sua conta de administrador em {2} foi bloqueada após {3} tentativas de login com falha.

Para desbloquear sua conta, acesse o URL abaixo em seu navegador.

{4} / {5} /index.php?action=unlock&uid= {7} & token = {6}

Se o link acima não funcionar corretamente, vá para

{4} / {5} /index.php?action=unlock

Você precisará digitar o seguinte:
Nome de usuário: {1}
Código de ativação: {6}

Obrigado,
{2} Staff';
$l['comma'] = ', ';
$l['login_username'] = 'nome de usuário';
$l['login_email'] = 'e-mail';
$l['login_username_and_password'] = 'nome de usuário/e-mail';
$l['secret_pin'] = 'PIN secreto:';
$l['error_invalid_username'] = 'O nome de usuário que você inseriu é inválido.';
$l['error_invalid_uid'] = 'A identificação do usuário que você inseriu é inválida.';
$l['error_invalid_token'] = 'O código de ativação que você inseriu é inválido.';
$l['all_groups'] = 'Todos os grupos';
$l['select_forums'] = 'Selecionar fóruns';
$l['select_groups'] = 'Selecionar grupos';
$l['groups_colon'] = 'Grupos:';
$l['none'] = 'Nenhum';
$l['alt_enabled'] = 'Ativado';
$l['alt_disabled'] = 'Desativado';
$l['enable'] = 'Ativar';
$l['disable'] = 'Desativar';
$l['saved'] = 'Salvo';
$l['rel_in'] = 'Em';
$l['rel_ago'] = 'atrás';
$l['rel_less_than'] = 'Menos que';
$l['rel_time'] = '<span title="{5}{6}">{1}{2} {3} {4}</span>';
$l['rel_minutes_single'] = 'minuto';
$l['rel_minutes_plural'] = 'minutos';
$l['rel_hours_single'] = 'hora';
$l['rel_hours_plural'] = 'horas';
$l['timezone_gmt_minus_950'] = '(GMT -9:30) Marquesas Islands';
$l['timezone_gmt_575'] = '(GMT +5:45) Kathmandu';
$l['timezone_gmt_650'] = '(GMT +6:30) Yangon';
$l['timezone_gmt_850'] = '(GMT +8:30) Pyongyang';
$l['timezone_gmt_875'] = '(GMT +8:45) Eucla';
$l['timezone_gmt_1050'] = '(GMT +10:30) Lord Howe Island';
$l['timezone_gmt_1150'] = '(GMT +11:30) Norfolk Island';
$l['timezone_gmt_1275'] = '(GMT +12:45) Chatham Islands';
$l['timezone_gmt_1300'] = '(GMT +13:00) Samoa, Tonga, Tokelau';
$l['timezone_gmt_1400'] = '(GMT +14:00) Line Islands';
$l['unknown_error'] = 'Um erro desconhecido ocorreu.';
$l['editor_bold'] = 'Negrito';
$l['editor_italic'] = 'Itálico';
$l['editor_underline'] = 'Sublinhado';
$l['editor_strikethrough'] = 'Riscado';
$l['editor_subscript'] = 'Subscrito';
$l['editor_superscript'] = 'Sobrescrito';
$l['editor_alignleft'] = 'Alinhar à esquerda';
$l['editor_center'] = 'Centralizar';
$l['editor_alignright'] = 'Alinhar à direita';
$l['editor_justify'] = 'Justificar';
$l['editor_fontname'] = 'Nome da fonte';
$l['editor_fontsize'] = 'Tamanho da fonte';
$l['editor_fontcolor'] = 'Cor da fonte';
$l['editor_removeformatting'] = 'Remover formatação';
$l['editor_cut'] = 'Cortar';
$l['editor_copy'] = 'Copiar';
$l['editor_paste'] = 'Colar';
$l['editor_cutnosupport'] = 'Seu navegador não permite o comando de corte. Use o atalho de teclado Ctrl / Cmd-X';
$l['editor_copynosupport'] = 'Seu navegador não permite o comando de cópia. Use o atalho de teclado Ctrl / Cmd-C';
$l['editor_pastenosupport'] = 'Seu navegador não permite o comando de cópia. Use o atalho de teclado Ctrl / Cmd-C';
$l['editor_pasteentertext'] = 'Cole o texto dentro da seguinte caixa:';
$l['editor_pastetext'] = 'Colar texto';
$l['editor_numlist'] = 'Lista numerada';
$l['editor_bullist'] = 'Lista de bolinhas';
$l['editor_undo'] = 'Desfazer';
$l['editor_redo'] = 'Refazer';
$l['editor_rows'] = 'Linhas:';
$l['editor_cols'] = 'Colunas';
$l['editor_inserttable'] = 'Inserir uma tabela';
$l['editor_inserthr'] = 'Inserir uma linha horizontal';
$l['editor_code'] = 'Código';
$l['editor_php'] = 'PHP';
$l['editor_width'] = 'Largura (Opcional):';
$l['editor_height'] = 'Altura (Opcional):';
$l['editor_insertimg'] = 'Inserir uma imagem';
$l['editor_email'] = 'E-mail:';
$l['editor_insertemail'] = 'Inserir um e-mail';
$l['editor_url'] = 'URL:';
$l['editor_insertlink'] = 'Inserir um link';
$l['editor_unlink'] = 'Desfazer link';
$l['editor_more'] = 'Mais';
$l['editor_insertemoticon'] = 'Inserir um emoticon';
$l['editor_videourl'] = 'Vídeo URL:';
$l['editor_videotype'] = 'Tipo de vídeo:';
$l['editor_insert'] = 'Inserir';
$l['editor_insertyoutubevideo'] = 'Inserir um vídeo do Youtube';
$l['editor_currentdate'] = 'Inserir a data atual';
$l['editor_currenttime'] = 'Inserir a hora atual';
$l['editor_print'] = 'Imprimir';
$l['editor_viewsource'] = 'Ver fonte';
$l['editor_description'] = 'Descrição (Opcional)';
$l['editor_enterimgurl'] = 'Inserir o url da imagem:';
$l['editor_enteremail'] = 'Inserir o endereço de e-mail:';
$l['editor_enterdisplayedtext'] = 'Digite o texto exibido:';
$l['editor_enterurl'] = 'Inserir URL:';
$l['editor_enteryoutubeurl'] = 'Digite o URL ou ID do vídeo do YouTube:';
$l['editor_insertquote'] = 'Inserir uma citação';
$l['editor_invalidyoutube'] = 'Vídeo do Youtube inválido';
$l['editor_dailymotion'] = 'Dailymotion';
$l['editor_metacafe'] = 'MetaCafe';
$l['editor_veoh'] = 'Veoh';
$l['editor_vimeo'] = 'Vimeo';
$l['editor_youtube'] = 'Youtube';
$l['editor_facebook'] = 'Facebook';
$l['editor_liveleak'] = 'LiveLeak';
$l['editor_insertvideo'] = 'Inserir um vídeo';
$l['editor_maximize'] = 'Maximizar';
$l['task_versioncheck_ran'] = 'A tarefa de verificação de versão foi executada com sucesso.';
$l['task_versioncheck_ran_errors'] = 'Não foi possível conectar-se ao MyBB para obter uma verificação de versão.';
$l['task_recachestylesheets_ran'] = 'Re-cached {1} folhas de estilo.';
$l['search_for_a_user'] = 'Pesquisar por um usuário';
$l['mybb_engine'] = 'MyBB Engine';
$l['my2fa'] = 'Autenticação de dois fatores';
$l['my2fa_failed'] = 'O código estava incorreto, você está desconectado agora';
$l['my2fa_code'] = 'Digite o código de autenticação';
$l['my2fa_label'] = 'Código de Autenticação:';
$l['my2fa_no_codes'] = 'Nota: você usou todos os seus códigos de recuperação. Visite a <a href="index.php?module=home-preferences&amp;action=recovery_codes">página de códigos de recuperação </a>para gerar um novo conjunto.';
