<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:31:36 +0000
// --------------------------------------------------------------------------------

$l['hello_desc'] = 'Um exemplo de plugin que permite que você crie mensagens na página de índice e anexe-as a cada publicação.';
$l['setting_group_hello'] = 'Olá Mundo!';
$l['setting_group_hello_desc'] = 'Configurações para o Hello World! Plugin.';
$l['setting_hello_display1'] = 'Exibir índice de mensagens';
$l['setting_hello_display1_desc'] = 'Definir como não se você não quiser exibir as mensagens no índice.';
$l['setting_hello_display2'] = 'Exibir corpo da mensagem';
$l['setting_hello_display2_desc'] = 'Definir como não se você não quiser exibir as mensagens abaixo de cada publicação.';
$l['hello_uninstall'] = 'Olá Mundo! Desinstalação';
$l['hello_uninstall_message'] = 'Deseja soltar todas as mensagens do banco de dados?';
