<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:10:04 +0000
// --------------------------------------------------------------------------------

$l['mybb_credits'] = 'Créditos do MyBB';
$l['mybb_credits_description'] = 'Estas pessoas dedicaram seu tempo e esforço para criar o MyBB.<br /><br />Suporte oficial para o Brasil provido por: <a href=\'http://www.mybb.com.br\'>MyBB Brasil</a>';
$l['about_the_team'] = 'Sobre o Time';
$l['product_managers'] = 'Gerentes de Produto';
$l['developers'] = 'Desenvolvedores';
$l['graphics_and_style'] = 'Gráficos e Estilo';
$l['software_quality_assurance'] = 'Controle de Qualidade';
$l['support_representative'] = 'Suporte';
$l['pr_liaison'] = 'Relações Públicas';
$l['check_for_updates'] = 'Verifique por atualizações';
$l['error_communication'] = 'Houve um problema ao baixar os últimos créditos. Por favor, tente novamente em alguns minutos.';
$l['no_credits'] = 'Nenhum crédito MyBB armazenado. <a href="index.php?module=home-credits&amp;fetch_new=1">Verificar atualizações</a>.';
$l['success_credits_updated'] = 'O cache de créditos MyBB foi atualizado com sucesso.';
