<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:13:31 +0000
// --------------------------------------------------------------------------------

$l['preferences_and_personal_notes'] = 'Preferências &amp; Bloco Pessoal';
$l['prefs_and_personal_notes_description'] = 'Aqui você pode gerenciar as preferências de seu Painel Administrativo e deixar anotações por sua conta.';
$l['preferences'] = 'Preferências';
$l['global_preferences'] = 'Preferências Globais';
$l['acp_theme'] = 'Tema do Painel Administrativo';
$l['select_acp_theme'] = 'Por favor , selecione um tema para uso no Painel Administrativo.';
$l['acp_language'] = 'Idioma do Painel Administrativo';
$l['select_acp_language'] = 'Por favor, selecione o idioma do Painel Administrativo.';
$l['notes_not_shared'] = 'Estas observações não serão compartilhadas com os outros administradores.';
$l['save_notes_and_prefs'] = 'Salvar Preferências e bloco pessoal';
$l['personal_notes'] = 'Bloco Pessoal';
$l['codemirror'] = 'Ligar ou Desligar edito de código';
$l['use_codemirror_desc'] = 'Esta opção permite desativar o editor de código (muito usado na edição e criação de código e folhas de estilho devido o código estar destacado em cores diferentes (Syntax Highlight). Se estiver tendo problemas de exibição ou lentidão é aconselhado desativar';
$l['success_preferences_updated'] = 'As preferências foram devidamente atualizadas.';
$l['use_2fa_desc'] = 'Autenticação de dois fatores é um método para proteger sua conta de administrador. Depois de ativá-lo, você verá um código QR abaixo do qual você precisa verificar com um aplicativo <a href="https://docs.mybb.com/1.8/administration/security/2fa/" target="_ blank "Como Google Authenticator ou Authy</a>. Esses aplicativos gerarão um token que você precisa inserir em cada login da ACP.';
$l['my2fa_qr'] = 'Código de autenticação de dois fatores';
$l['recovery_codes_desc'] = 'Veja seus <a href="index.php?module=home-preferences&amp;action=recovery_codes">códigos de recuperação</a>.';
$l['recovery_codes'] = 'Códigos de Recuperação';
$l['recovery_codes_warning'] = '<b>Nota:</b> os códigos serão regenerados em cada visita de página e só podem ser usados uma vez.';
$l['print_recovery_codes'] = 'Imprimir Códigos de Recuperação';
