<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:11:41 +0000
// --------------------------------------------------------------------------------

$l['dashboard'] = 'Central Administrativa';
$l['dashboard_description'] = 'Esta seção permite que você visualize várias estatísticas e informações relativas ao seu fórum. Você pode ainda adicionar notas para outros administradores.';
$l['mybb_server_stats'] = 'Estatísticas do servidor e do MyBB';
$l['forum_stats'] = 'Estatísticas do Forum';
$l['mybb_version'] = 'Versão do MyBB';
$l['threads'] = 'Tópicos';
$l['new_today'] = 'Novos Hoje';
$l['unapproved'] = 'Não Aprovados';
$l['php_version'] = 'Versão do PHP';
$l['posts'] = 'Respostas';
$l['sql_engine'] = 'Sistema SQL';
$l['users'] = 'Usuários';
$l['registered_users'] = 'Usuários Registrados';
$l['active_users'] = 'Usuários Ativos';
$l['registrations_today'] = 'Registros Hoje';
$l['awaiting_activation'] = 'Aguardando Aprovação';
$l['server_load'] = 'Uso do Servidor';
$l['attachments'] = 'Anexos';
$l['used'] = 'Usado';
$l['last_update_check_two_weeks'] = 'A última <a href="{1}">verificação de versão do MyBB</a> foi a mais de duas semanas atrás.';
$l['new_version_available'] = 'Você está executando atualmente a versão {1} enquanto a versão mais recente é a {2}.';
$l['admin_notes_public'] = 'Estas notas são públicas para todos os administradores.';
$l['admin_notes'] = 'Notas Admninistrativas';
$l['save_notes'] = 'Salvar Notas';
$l['success_notes_updated'] = 'As notas administrativas foram atualizadas com sucesso.';
$l['reported_posts'] = 'Mensagens reportadas';
$l['unread_reports'] = 'Reports não lidos';
$l['version_check'] = 'Checar por atualizações';
$l['version_check_description'] = 'Aqui você pode verificar se você está executando a última cópia do MyBB e ver os anúncios mais recentes diretamente do MyBB.';
$l['latest_mybb_announcements'] = 'Últimos anúncios MyBB';
$l['no_announcements'] = 'Não há anúncios armazenados. <a href="index.php?module=home&amp;action=version_check">Verifique as atualizações</a>.';
$l['your_version'] = 'Sua versão';
$l['latest_version'] = 'Última versão';
$l['update_forum'] = 'Atualize para a versão mais recente do MyBB visitando o <a href="https://mybb.com" target="_blank">site MyBB</a>.';
$l['read_more'] = 'Ler mais';
$l['success_up_to_date'] = 'Parabéns, você está executando a versão mais recente do MyBB.';
$l['error_out_of_date'] = 'Sua cópia do MyBB está desatualizada.';
$l['error_communication'] = 'Ocorreu um problema ao se comunicar com o servidor de versão. Por favor, tente novamente em alguns minutos.';
$l['error_fetch_news'] = 'O MyBB não conseguiu obter os anúncios mais recentes do site MyBB.';
$l['news_description'] = 'As últimas notícias do <a href="https://blog.mybb.com/" target="_blank">MyBB Blog</a>.';
