<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:11:58 +0000
// --------------------------------------------------------------------------------

$l['home'] = 'Início';
$l['dashboard'] = 'Central Administrativa';
$l['preferences'] = 'Preferências';
$l['version_check'] = 'Verificar Versão';
$l['mybb_credits'] = 'Créditos do MyBB';
$l['add_new_forum'] = 'Criar Novo Fórum';
$l['search_for_users'] = 'Pesquisar Usuários';
$l['themes'] = 'Temas';
$l['templates'] = 'Modelos';
$l['plugins'] = 'Plugins';
$l['database_backups'] = 'Backups';
$l['quick_access'] = 'Acesso Rápido';
$l['online_admins'] = 'Administradores Online';
$l['ipaddress'] = 'IP';
$l['mybb_documentation'] = 'Documentos MyBB';
