<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:17:30 +0000
// --------------------------------------------------------------------------------

$l['template_sets'] = 'Grupos de Modelos';
$l['template_set'] = 'Grupo de Modelo';
$l['templates'] = '{1} Modelos';
$l['manage_template_sets'] = 'Gerenciar';
$l['manage_template_sets_desc'] = 'Aqui você pode gerenciar seus grupos de modelos, visualizar os modelos usando estes grupos e iniciar a customização do visual do seu fórum.';
$l['add_set'] = 'Novo Grupo';
$l['add_set_desc'] = 'Aqui você pode criar um novo grupo de modelos. Um novo grupo de modelo cria uma cópia do modelos mestres e permite que você edite sem interferir ou alterar nada em nenhum outro grupo de modelos que você já possua.';
$l['add_template'] = 'Novo Modelo';
$l['add_template_desc'] = 'Aqui você pode criar um novo modelo.';
$l['search_replace'] = 'Pesquisar/Substituir';
$l['search_replace_desc'] = 'Esta ferramenta permite que você pesquise modelos que contenham um certo título ou texto, e opcionalmente faça uma substituição por outro texto automaticamente.';
$l['find_updated'] = 'Encontrar Modelos Atualizados';
$l['find_updated_desc'] = 'Permite que você encontre modelos alterados em uma nova versão do MyBB de forma que você aplique as alterações necessárias de forma correta.';
$l['edit_template'] = 'Editar Modelo';
$l['edit_template_desc'] = 'Aqui você pode editar o código dos modelos, o título ou o grupo.';
$l['edit_set'] = 'Editar Grupo';
$l['edit_set_desc'] = 'Aqui você pode editar as propriedades para este grupo de modelos.';
$l['manage_templates'] = 'Gerenciar Modelos';
$l['manage_templates_desc'] = 'Aqui você pode gerenciar os modelos para este grupo de modelos. Para editar um modelo clique em seu link e escolha "Edição Completa" para editar todas as propriedades numa página separada.';
$l['diff_report'] = 'Relatório de Diferenças';
$l['diff_report_desc'] = 'Executa uma análise das diferenças entre os modelos e mostra exatamente o que mudou entre sua cópia customizada e cópia mestra mais recente.';
$l['title'] = 'Título';
$l['save'] = 'Salvar';
$l['search_for'] = 'Pesquisar Por';
$l['replace_with'] = 'Substituir Com (Opcional)';
$l['reset'] = 'Reiniciar';
$l['find_templates'] = 'Encontrar Modelos';
$l['find_and_replace'] = 'Encontrar e Substituir';
$l['search_template_names'] = 'Pesquisar Título de Modelos';
$l['ungrouped_templates'] = 'Modelos Desagrupados';
$l['search_noneset'] = 'Você não informou nenhum termo de pesquisa.';
$l['search_results'] = 'Resultados da Pesquisa';
$l['search_header'] = 'Pesquisando Por "{1}" em {2}';
$l['search_updated'] = 'Atualizado {1}';
$l['search_found'] = 'Encontrado em {1}';
$l['search_created_custom'] = 'Modelo customizado criado para {1}';
$l['search_edit'] = 'editar';
$l['search_change_original'] = 'alterar original';
$l['search_noresults'] = 'Nenhum modelo foi encontrado contendo \'<strong>{1}</strong>\'';
$l['search_noresults_title'] = 'Nenhum modelo foi encontrado com o título \'<strong>{1}</strong>\'';
$l['default_templates'] = 'Modelos Padrão';
$l['edit_template_breadcrumb'] = 'Editar Modelo: ';
$l['global_templates'] = 'Modelos Globais';
$l['master_templates'] = 'Modelos Mestres';
$l['not_used_by_any_themes'] = 'Não usado em nenhum tema';
$l['used_by'] = 'Usado por: ';
$l['used_by_all_themes'] = 'Usado por todos os temas';
$l['expand_templates'] = 'Expandir Modelos';
$l['edit_template_set'] = 'Editar Grupo de Modelo';
$l['delete_template_set'] = 'Excluir Grupo de Modelo';
$l['inline_edit'] = 'Edição Rápida';
$l['full_edit'] = 'Edição Completa';
$l['revert_to_orig'] = 'Reverter ao Original';
$l['delete_template'] = 'Excluir Modelo';
$l['edit_in'] = 'Editar em';
$l['group_calendar'] = 'Calendário';
$l['group_forumdisplay'] = 'Exibição do Fórum';
$l['group_index'] = 'Página Principal';
$l['group_error'] = 'Mensagem de Erro';
$l['group_memberlist'] = 'Lista de Membros';
$l['group_multipage'] = 'Paginação';
$l['group_private'] = 'Mensagem Pessoal';
$l['group_portal'] = 'Portal';
$l['group_postbit'] = 'Exibição de Resposta';
$l['group_redirect'] = 'Redirecionamento';
$l['group_showthread'] = 'Exibição de Tópico';
$l['group_usercp'] = 'Painel de Controle';
$l['group_online'] = 'Quem Está Online';
$l['group_forumbit'] = 'Fórum';
$l['group_editpost'] = 'Editar Resposta';
$l['group_forumjump'] = 'Menu Rápido do Fórum';
$l['group_moderation'] = 'Moderação';
$l['group_nav'] = 'Navegação';
$l['group_search'] = 'Pesquisa';
$l['group_showteam'] = 'Equipe do Fórum';
$l['group_reputation'] = 'Reputação';
$l['group_newthread'] = 'Novo Tópico';
$l['group_newreply'] = 'Nova Resposta';
$l['group_member'] = 'Membro';
$l['group_warning'] = 'Sistema de Alerta';
$l['group_global'] = 'Global';
$l['group_header'] = 'Cabeçalho';
$l['group_managegroup'] = 'Gerenciar Grupo';
$l['group_misc'] = 'Outros';
$l['group_modcp'] = 'Mod CP';
$l['group_php'] = 'PHP';
$l['group_polls'] = 'Enquete';
$l['group_post'] = 'Resposta';
$l['group_printthread'] = 'Imprimir Tópico';
$l['group_report'] = 'Reportar';
$l['group_smilieinsert'] = 'Emoticons';
$l['group_stats'] = 'Estatísticas';
$l['group_xmlhttp'] = 'XMLHTTP';
$l['group_footer'] = 'Rodapé';
$l['expand'] = 'Expandir';
$l['collapse'] = 'Contrair';
$l['save_continue'] = 'Salvar e Continuar Editando';
$l['save_close'] = 'Salvar e Voltar para Lista';
$l['template_name'] = 'Nome do Modelo';
$l['template_name_desc'] = 'Nome do modelo. Se você alterar isso no modelo padrão, ele será salvo como um modelo customizado com o novo nome.';
$l['template_set_desc'] = 'A qual grupo de modelos este modelo deve pertencer?';
$l['templates_the_same'] = 'Os dois modelos selecionados são exatamente iguais e não podem ser comparados.';
$l['master_updated_ins'] = 'Alterações que foram feitas em sua versão anterior e este são mostradas assim.';
$l['master_updated_del'] = 'Alterações que foram feitas nos seus modelos (os antigos) são mostradas assim.';
$l['template_diff_analysis'] = 'Análise de Diferenças de Modelos';
$l['search_names_header'] = 'Pesquisando nomes de modelos contendo "{1}"';
$l['updated_template_welcome1'] = 'Editar - Permite que você edite o modelo atual para este grupo para incorporar as atualizações ocorridas entre as versões.';
$l['updated_template_welcome2'] = 'Reverter - Irá reverter o modelo customizado para a revisão mestra e fará com que se perca quaisquer alterações que foram feitas.';
$l['updated_template_welcome3'] = 'Diferença - Executa uma análise das diferenças entre os modelos e mostra exatamente o que mudou entre sua cópia customizada e cópia mestra mais recente.';
$l['no_global_templates'] = 'Não existem atualmente modelos globais.';
$l['no_updated_templates'] = 'Não existem modelos atualizados desde a última atualização.';
$l['confirm_template_set_deletion'] = 'Tem certeza que deseja excluir este grupo de modelo?';
$l['confirm_template_deletion'] = 'Tem certeza que deseja excluir este modelo?';
$l['confirm_template_revertion'] = 'Tem certeza que deseja reverter este modelo?';
$l['error_security_problem'] = 'Um problema de segurança potencial foi encontrado no modelo. Por favor reveja as alterações ou entre em contato com o MyBB Brasil para ajuda.';
$l['error_missing_input'] = 'Tenha certeza que você possui todos os dados necessários para editar este modelo (tid e sid)';
$l['error_already_exists'] = 'O título do modelo já está em uso. Por favor escolha outro.';
$l['error_invalid_template'] = 'Por favor selecione um modelo válido.';
$l['error_missing_set_title'] = 'Por favor selecione um título de grupo de modelo.';
$l['error_invalid_input'] = 'Tenha certeza que você possui a ID correta do grupo de modelo.';
$l['error_invalid_set'] = 'Por favor selecione um grupo de modelo válido.';
$l['error_invalid_template_set'] = 'Grupo de modelo inválido selecionado.';
$l['error_themes_attached_template_set'] = 'Este grupo de modelo não pode ser excluído por que ele faz parte de um ou mais temas.';
$l['success_template_saved'] = 'O modelo selecionado foi salvo com sucesso.';
$l['success_template_deleted'] = 'O modelo selecionado foi excluído com sucesso.';
$l['success_template_reverted'] = 'O modelo selecionado foi revertido com sucesso.';
$l['success_template_set_saved'] = 'O grupo de modelo foi salvo com sucesso.';
$l['success_template_set_deleted'] = 'O grupo de modelo foi excluído com sucesso.';
$l['add_template_group'] = 'Adicionar Grupo de Modelos';
$l['add_template_group_desc'] = 'Adicione um grupo de modelos para reunir os modelos juntos.';
$l['editing_template'] = 'Editando Modelo: {1}';
$l['empty_template_set'] = '<em>Não existem modelos neste conjunto.</em>';
$l['group_posticons'] = 'Ícone de mensagem';
$l['group_announcement'] = 'Anúncio';
$l['group_video'] = 'Vídeo MyCode';
$l['group_sendthread'] = 'Enviar tópico';
$l['group_mycode'] = 'MyCode';
$l['template_group_prefix'] = 'Prefixo do grupo de modelos';
$l['template_group_prefix_desc'] = 'O nome do prefixo para agrupar modelos. Isso não deve existir. Por exemplo, para agrupar modelos <em>hello_world</em>, <em>hello_foobar</em> e <em>hello_foo </em>, entre <strong>hello</strong> aqui.';
$l['template_group_title'] = 'Título do grupo de modelos';
$l['template_group_title_desc'] = 'O título do grupo de prefixos. Isso será mostrado na lista de modelos. Por exemplo, para os nossos modelos <em>hello</em>, entre <strong>hello</strong> aqui.';
$l['edit_template_group'] = 'Editar grupo de modelos';
$l['editing_template_group'] = 'Editar grupo de modelos {1}';
$l['delete_template_group'] = 'Excluir grupo de modelos';
$l['save_template_group'] = 'Salvar grupo de modelos';
$l['confirm_template_group_delete'] = 'Tem certeza de que deseja excluir este grupo de modelos? Esta ação não remove os modelos no grupo.';
$l['error_missing_group_prefix'] = 'Digite um prefixo para o grupo de modelos.';
$l['error_invalid_group_title'] = 'Como sublinhados (_) são usados como delimitadores, esses são proibidos nos prefixos do grupo de modelos. Selecione outro prefixo.';
$l['error_missing_group_title'] = 'Digite um título para o grupo de modelos.';
$l['error_duplicate_group_prefix'] = 'Um grupo de modelos já existe com esse prefixo. Digite outro prefixo.';
$l['error_missing_template_group'] = 'O grupo de modelos não pôde ser encontrado.';
$l['error_default_template_group'] = 'Não é possível editar ou remover um grupo de modelos padrão.';
$l['success_template_group_saved'] = 'O grupo de modelos selecionado foi salvo com sucesso.';
$l['success_template_group_deleted'] = 'O grupo de modelos selecionado foi excluído com sucesso.';
