<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:20:41 +0000
// --------------------------------------------------------------------------------

$l['themes'] = 'Temas';
$l['themes_desc'] = 'Aqui você pode gerenciar os temas configurados em seu fórum.';
$l['create_new_theme'] = 'Criar um Novo Tema';
$l['create_new_theme_desc'] = 'Aqui você pode criar um novo tema baseado no tema padrão';
$l['import_a_theme'] = 'Importar um Tema';
$l['import_a_theme_desc'] = 'Aqui você pode importar um novo tema.';
$l['edit_stylesheets'] = 'Editar Estilos';
$l['edit_stylesheets_desc'] = 'Aqui você pode facilmente gerenciar os estilos (CSS) usados por este tema.';
$l['add_stylesheet'] = 'Adicionar Estilo';
$l['add_stylesheet_desc'] = 'Aqui você pode adicionar um novo estiloo para este tema.';
$l['browse_themes'] = 'Explorar Temas';
$l['browse_themes_desc'] = 'Aqui é possível navegar pelo site oficial de modificações do MyBB e encontrar temas compatíveis com esta instalação do MyBB.';
$l['browse_all_themes'] = 'Explorar Todos os Temas';
$l['export_theme'] = 'Exportar Tema';
$l['export_theme_desc'] = 'Aqui você pode exportar seus temas e modelos customizados.';
$l['include_custom_only'] = 'Incluir ítens customizados somente?';
$l['include_custom_only_desc'] = 'Se deseja incluir ítens (estilos) herdados selecione "não", caso contrário somente elementos customizados serão exportados.';
$l['include_templates'] = 'Incluir modelos na exportação também?';
$l['include_templates_desc'] = 'Se deseja incluir os modelos customizados usados neste tema, selecione sim.';
$l['edit_stylesheet_simple_mode'] = 'Editar Estilo: Modo Simples';
$l['edit_stylesheet_simple_mode_desc'] = 'Aqui você pode facilmente editar o estilo usado em seu tema usando um modo mais simples e fácil.';
$l['edit_stylesheet_advanced_mode'] = 'Editar Estilo: Modo Avançado';
$l['edit_stylesheet_advanced_mode_desc'] = 'Aqui você pode facilmente editar o estilo usado em seu tema editando diretamente o arquivo css.';
$l['theme'] = 'Tema';
$l['num_users'] = '# Usuários';
$l['edit_theme'] = 'Editar Tema';
$l['delete_theme'] = 'Excluir Tema';
$l['set_as_default'] = 'Definir como Padrão';
$l['default_theme'] = 'Tema Padrão';
$l['force_on_users'] = 'Forçar nos Usuários';
$l['delete_revert'] = 'Excluir/Reverter';
$l['local_file'] = 'Arquivo Local';
$l['url'] = 'URL';
$l['import_from'] = 'Importar de';
$l['import_from_desc'] = 'Selecione um arquivo para importar.';
$l['parent_theme'] = 'Tema Pai';
$l['parent_theme_desc'] = 'Selecione o tema que este tema deva ser filho.';
$l['new_name'] = 'Novo Nome';
$l['new_name_desc'] = 'O novo nome do tema importado.';
$l['advanced_options'] = 'Opções Avançadas';
$l['ignore_version_compatibility'] = 'Ignorar Compatibilidade de Versão';
$l['ignore_version_compat_desc'] = 'Deve este tema ser instalado independente da versão do MyBB instalada?';
$l['import_stylesheets'] = 'Importar Estilos';
$l['import_stylesheets_desc'] = 'Se este tema possuir estilos customizados, estes deverão ser importados?';
$l['import_templates'] = 'Importar Modelos';
$l['import_templates_desc'] = 'Se este tema possuir modelos customizados, estes deverão ser importados?';
$l['import_theme'] = 'Importar Tema';
$l['create_a_theme'] = 'Criar um Tema';
$l['name'] = 'Nome';
$l['name_desc'] = 'Especifique um nome para o novo tema.';
$l['edit_theme_properties'] = 'Editar Propriedades do Tema';
$l['name_desc_edit'] = 'Especifique um nome para tema.';
$l['allowed_user_groups'] = 'Grupos Permitidos';
$l['allowed_user_groups_desc'] = 'Especifique que grupos poderão usar este tema.';
$l['all_user_groups'] = 'Todos os Grupos';
$l['template_set'] = 'Grupo de Modelos';
$l['template_set_desc'] = 'Especifique o grupo de modelos que o tema usará.';
$l['editor_theme'] = 'Estilo do Editor';
$l['editor_theme_desc'] = 'Especifique o estilo a ser usado pelo editor de MyCode neste tema.';
$l['img_directory'] = 'Diretório de Imagem';
$l['img_directory_desc'] = 'Especifique o local da pasta onde estão as imagens usadas neste tema.';
$l['logo'] = 'Logotipo do Fórum';
$l['logo_desc'] = 'Especifique o local do logotipo usado no fórum.';
$l['table_spacing'] = 'Espaço de Tabela';
$l['table_spacing_desc'] = 'A largura do espaço entre o conteúdo da tabela interna e as bordas da mesma, em pixels.';
$l['inner_border'] = 'Largura da Tabela Interna';
$l['inner_border_desc'] = 'A quantidade de espaço entre duas células de tabela, em pixels.';
$l['save_theme_properties'] = 'Salvar Propriedades do Tema';
$l['background'] = 'Plano de fundo';
$l['extra_css_atribs'] = 'Atributos CSS Extras';
$l['color'] = 'Cor';
$l['width'] = 'Largura';
$l['text_decoration'] = 'Decoração de Texto';
$l['font_family'] = 'Família de Fontes';
$l['font_size'] = 'Tamanho da Fonte';
$l['font_style'] = 'Estilo da Fonte';
$l['font_weight'] = 'Negrito';
$l['stylesheets'] = 'Estilos';
$l['inherited_from'] = 'Herdados de';
$l['attached_to'] = 'Anexados a';
$l['attached_to_desc'] = 'Você pode tanto anexar estilos globalmente ou a arquivos específicos.';
$l['actions'] = 'ações';
$l['of'] = 'de';
$l['attached_to_all_pages'] = 'Anexados a toda as páginas';
$l['properties'] = 'Propriedades';
$l['edit_style'] = 'Editar Estilo';
$l['stylesheets_in'] = 'Estilos em';
$l['stylesheet_properties'] = 'Propriedades do Estilo';
$l['stylesheet_inherited_default'] = 'Este estilo está atualmente herdando de {1}.';
$l['stylesheet_inherited'] = 'Esta folha de estilo está sendo herdada de {1}. Quaisquer mudanças que você faça romperão a herança e a folha de estilos será copiada para esse tema. Edite esta folha de estilo em {1} para manter a herança.';
$l['globally'] = 'Globalmente';
$l['specific_files'] = 'Arquivos Específicos';
$l['specific_actions'] = 'Ações Específicas';
$l['specific_actions_desc'] = 'Ações são separadas por vírgulas';
$l['file'] = 'Arquivo';
$l['add_another'] = 'Adicionar outro';
$l['edit_stylesheet_properties_for'] = 'Editar As Propriedades do Estilo para';
$l['file_name'] = 'Nome do Arquivo';
$l['file_name_desc'] = 'Nome para o estilo, normalmente terminando com <strong>[.css]</strong>';
$l['save_stylesheet_properties'] = 'Salvar Propriedades do Estilo';
$l['saved'] = 'Salvo';
$l['editing'] = 'Editando';
$l['selector'] = 'Seletor';
$l['save_changes'] = 'Salvar Alterações';
$l['save_changes_and_close'] = 'Salvar Alterações e Fechar';
$l['save_changes_js'] = 'Deseja salvar suas alterações primeiro?';
$l['delete_confirm_js'] = 'Tem certeza que deseja excluir?';
$l['import_stylesheet_from'] = 'Importar de outro estilo neste tema';
$l['write_own'] = 'Escrever meu próprio conteúdo';
$l['save_stylesheet'] = 'Salvar Estilo';
$l['add_stylesheet_to'] = 'Adicionar Estilo a';
$l['full_stylesheet_for'] = 'Estilo Completo para';
$l['recommended_themes_for_mybb'] = 'Temas Recomendados para o MyBB {1}';
$l['browse_results_for_mybb'] = 'Explorar Resultados para o MyBB {1}';
$l['search_for_themes'] = 'Pesquisar por Temas';
$l['search'] = 'Pesquisar';
$l['download'] = 'Baixar';
$l['created_by'] = 'Criado por';
$l['error_invalid_stylesheet'] = 'Você selecionou um estilo inválido.';
$l['error_invalid_theme'] = 'Você selecionou um tema inválido.';
$l['error_missing_name'] = 'Por favor informe um nome para este tema.';
$l['error_missing_url'] = 'Por favor informe um tema para importar.';
$l['error_theme_already_exists'] = 'O tema especificado já existe. Por favor informe um novo nome para este tema.';
$l['error_local_file'] = 'Não foi possível abrir o arquivo local. Tem certeza que ele existe? Por favor verifique e tente novamente.';
$l['error_uploadfailed'] = 'Envio falhou. Tente novamente.';
$l['error_uploadfailed_detail'] = 'Detalhes do Erro: ';
$l['error_uploadfailed_php1'] = 'PHP retornou: O arquivo enviado excedeu a diretiva upload_max_filesize no arquivo php.ini.';
$l['error_uploadfailed_php2'] = 'O arquivo enviado excedeu o tamanho máximo para envio.';
$l['error_uploadfailed_php3'] = 'O arquivo foi somente parcialmente enviado.';
$l['error_uploadfailed_php4'] = 'Nenhum arquivo foi enviado.';
$l['error_uploadfailed_php6'] = 'PHP retornou: Faltando diretório temporário.';
$l['error_uploadfailed_php7'] = 'PHP retornou: Falha ao escrever arquivo no disco.';
$l['error_uploadfailed_phpx'] = 'PHP retornou o código de erro: {1}.';
$l['error_uploadfailed_lost'] = 'O arquivo não foi encontrado no servidor';
$l['error_uploadfailed_nocontents'] = 'Não foi possível encontrar nenhum tema no arquivo enviado. Por favor verifique o arquivo e tente novamente.';
$l['error_invalid_version'] = 'Este tema foi criado para outra versão do MyBB. Por favor marque a caixa "Ignorar Compatibilidade de Versão" para ignorar este erro.';
$l['error_missing_stylesheet_name'] = 'Por favor informe um nome para o estilo.';
$l['error_missing_stylesheet_extension'] = 'Este estilo precisa terminar com a extensão de arquivo correta, por exemplo, {1}<em>.css</em>';
$l['error_invalid_parent_theme'] = 'O tema pai selecionado não existe. Por favor selecione um tema pai válido.';
$l['error_invalid_templateset'] = 'O grupo de modelo selecionado não existe. Por favor selecione um grupo de modelo válido.';
$l['error_invalid_editortheme'] = 'O tema do editor selecionado não existe. Por favor selecione um tema do editor válido.';
$l['error_inheriting_stylesheets'] = 'Você não pode excluir este tema por que ainda existem outros temas que estão herdando estilos do mesmo.';
$l['error_cannot_parse'] = 'O sistema não pode processar este estilo com o editor simples. Ele só pode ser editado no modo avançado.';
$l['error_communication_problem'] = 'Ocorreu um problema de comunicação com o servidor de temas. Por favor, tente novamente em alguns minutos.';
$l['error_no_results_found'] = 'Nenhum resultado encontrado para as palavras-chave usadas.';
$l['success_imported_theme'] = 'O tema selecionado foi importado com sucesso.';
$l['success_theme_created'] = 'O tema foi crigado com sucesso.';
$l['success_theme_deleted'] = 'O tema selecionado foi excluído com sucesso.';
$l['success_stylesheet_properties_updated'] = 'As propriedades do estilo selecionado foram atualizadas com sucesso.';
$l['success_stylesheet_updated'] = 'O estilo selecionado foi atualizado com sucesso.';
$l['success_stylesheet_deleted'] = 'O estilo selecionado foi excluído/revertido com sucesso.';
$l['success_theme_set_default'] = 'O tema selecionado agora é o padrão do fórum.';
$l['success_theme_forced'] = 'Todos os usuários foram forçados a usar o tema selecionado com sucesso.';
$l['success_theme_properties_updated'] = 'As propriedades do tema selecionado foram atualizadas com sucesso.';
$l['success_stylesheet_added'] = 'O estilo para o tema selecionado foi criado com sucesso.';
$l['confirm_theme_deletion'] = 'Tem certeza que deseja excluir este tema?';
$l['confirm_stylesheet_deletion'] = 'Tem certeza que deseja excluir/reverter este estilo?';
$l['confirm_theme_forced'] = 'Tem certeza que deseja forçar este tema para todos os usuários?';
$l['duplicate_theme'] = 'Temas duplicados';
$l['duplicate_theme_desc'] = 'Aqui você pode duplicar seus temas. Isso ajuda você se você quiser desenvolver outra versão.';
$l['colors_manage'] = 'Gerenciar cores';
$l['colors_attached_to'] = 'configuração de cores';
$l['colors_setting'] = 'Cor base';
$l['colors_setting_desc'] = 'Selecione a cor que este tema deve usar como sua cor base. As folhas de estilos anexadas a esta cor serão usadas.';
$l['colors_no_color_setting'] = 'Não há cores disponíveis. Crie uma lista de cores abaixo para usar esse recurso.';
$l['colors_add'] = 'Gerenciar cores';
$l['colors_add_desc'] = 'Uma lista de cores disponíveis para este tema. Esta deve ser uma lista de cores de chave (chave = item), por exemplo, <em>azul = azul</ em>. Separar itens com uma nova linha.';
$l['colors_please_select'] = 'Nenhum';
$l['colors_add_edit_desc'] = 'Selecione uma cor para anexar esta folha de estilo. Você pode selecionar mais de uma cor.';
$l['colors_specific_color'] = 'Cor específica';
$l['new_name_duplicate_desc'] = 'Um novo nome para o tema duplicado.';
$l['duplicate_stylesheets'] = 'Duplicate Stylesheets';
$l['duplicate_stylesheets_desc'] = 'Se este tema contiver folhas de estilo personalizadas, elas devem ser duplicadas?';
$l['duplicate_templates'] = 'Modelos Duplicados';
$l['duplicate_templates_desc'] = 'Se esse tema contiver modelos personalizados, eles devem ser duplicados?';
$l['display_order'] = 'Ordem';
$l['save_stylesheet_order'] = 'Salvar ordens de folhas de estilo';
$l['attached_to_nothing'] = 'Anexado a nada';
$l['error_theme_security_problem'] = 'Um problema de segurança potencial foi encontrado no tema. Não foi importado. Entre em contato com o autor ou grupo MyBB para obter suporte.';
$l['error_no_color_picked'] = 'Você não especificou as cores para anexar esta folha de estilo.';
$l['error_no_display_order'] = 'Ocorreu um erro ao encontrar as ordens de exibição para as folhas de estilo. Atualize a página e tente novamente.';
$l['success_duplicated_theme'] = 'O tema selecionado foi duplicado com sucesso.';
$l['success_stylesheet_order_updated'] = 'As ordens de exibição das folhas de estilo foram atualizadas com sucesso.';
$l['theme_info_fetch_error'] = 'Ocorreu um erro ao buscar as informações de estilo.';
$l['theme_info_save_error'] = 'Ocorreu um erro ao salvar as informações de estilo.';
$l['saving'] = 'Salvando...';
