<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:30:31 +0000
// --------------------------------------------------------------------------------

$l['tools_and_maintenance'] = 'Ferramentas e Manutenção';
$l['maintenance'] = 'Manutenção';
$l['logs'] = 'Logs';
$l['system_health'] = 'Estado do Sistema';
$l['cache_manager'] = 'Gerenciar Cache';
$l['task_manager'] = 'Gerenciar Tarefas';
$l['recount_and_rebuild'] = 'Recontar e Reconstruir';
$l['view_php_info'] = 'Visualizar Info do PHP';
$l['database_backups'] = 'Backups';
$l['optimize_database'] = 'Otimizar Banco de Dados';
$l['file_verification'] = 'Verificação de Arquivo';
$l['administrator_log'] = 'Administração';
$l['moderator_log'] = 'Moderação';
$l['user_email_log'] = 'Email de Usuários';
$l['system_mail_log'] = 'Email do Sistema';
$l['user_warning_log'] = 'Alertas de Usuário';
$l['statistics'] = 'Estatísticas';
$l['can_access_system_health'] = 'Pode acessar o estado do sistema?';
$l['can_manage_cache'] = 'Pode gerenciar o cache?';
$l['can_manage_tasks'] = 'Pode gerenciar as tarefas agendadas?';
$l['can_manage_db_backup'] = 'Pode gerenciar o backup do banco de dados?';
$l['can_optimize_db'] = 'Pode otimizar o banco de dados?';
$l['can_recount_and_rebuild'] = 'Pode recontar e reconstruir?';
$l['can_manage_admin_logs'] = 'Pode gerenciar os logs administrativos?';
$l['can_manage_mod_logs'] = 'Pode gerenciar os logs da moderação?';
$l['can_manage_user_mail_log'] = 'Pode gerenciar os logs de email de usuário?';
$l['can_manage_system_mail_log'] = 'Pode gerenciar os logs de email do sistema?';
$l['can_manage_user_warning_log'] = 'Pode gerenciar os logs de alerta de usuário?';
$l['can_view_php_info'] = 'Pode visualizar as infos do PHP?';
$l['can_manage_file_verification'] = 'Pode gerenciar a verificação de arquivo?';
$l['can_view_statistics'] = 'Pode visualizar estatísticas?';
$l['spam_log'] = 'Relatório de Spam';
$l['can_manage_spam_log'] = 'Pode gerenciar relatórios de spam?';
