<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:29:07 +0000
// --------------------------------------------------------------------------------

$l['cache'] = 'Cache:';
$l['cache_manager'] = 'Gerenciar Cache';
$l['cache_manager_description'] = 'Aqui você pode gerenciar os caches que são usados para otimizar o MyBB. Reconstruir o cache fará com que todos os dados necessários sejam obtidos novamente e ressincronizados. Recarregar o cache fará com que o cache seja carregado novamente pelo gerenciador usado (disco, eaccelerator, memcache, etc). Recarregar é útil quando se troca do banco de dados ou disco para o xcache, eaccelerator ou outro gerenciador de cache.';
$l['rebuild_cache'] = 'Reconstruir Cache';
$l['reload_cache'] = 'Recarregar Cache';
$l['error_cannot_rebuild'] = 'Este cache não pode ser reconstruído.';
$l['error_empty_cache'] = 'O cache está vazio.';
$l['error_incorrect_cache'] = 'Cache incorreto especificado.';
$l['error_no_cache_specified'] = 'Você não especificou um cache para visualizar.';
$l['success_cache_rebuilt'] = 'O cache foi reconstruído com sucesso.';
$l['success_cache_reloaded'] = 'O cache foi recarregado com sucesso.';
$l['rebuild_reload_all'] = '(Reconstruir & Recarregar todos)';
