<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:40:02 +0000
// --------------------------------------------------------------------------------

$l['recount_rebuild'] = 'Recontagem e Reconstrução';
$l['recount_rebuild_desc'] = 'Aqui você pode recontar e reconstruir informações para corrigir erros de sincronização no seu fórum.';
$l['data_per_page'] = 'Entradas por Página';
$l['recount_stats'] = 'Recontar Estatísticas';
$l['recount_stats_desc'] = 'Isto irá recontar e atualizar as estatísticas do fórum.';
$l['rebuild_forum_counters'] = 'Reconstruir Contadores do Fórum';
$l['rebuild_forum_counters_desc'] = 'Isto irá atualizar os contadores de respostas/tópicos e a última resposta em cada fórum para refletir os valores corretos.';
$l['rebuild_thread_counters'] = 'Reconstruir Contadores de Tópico';
$l['rebuild_thread_counters_desc'] = 'Isto irá atualizar os contadores de respostas/visualizações e a última resposta em cada tópico para refletir os valores corretos.';
$l['recount_user_posts'] = 'Recontar Contagem de Respostas';
$l['recount_user_posts_desc'] = 'Isto irá atualizar a contagem de repostas de todos os usuários para refletir os valores corretos.';
$l['rebuild_attachment_thumbs'] = 'Reconstruir Miniaturas em Anexos';
$l['rebuild_attachment_thumbs_desc'] = 'Isto irá reconstruir as miniaturas em anexos para que utilizem os valores corretos de largura e altura especificados e também minaturas faltantes.';
$l['success_rebuilt_forum_counters'] = 'Os contadores do fórum foram reconstruidos com sucesso.';
$l['success_rebuilt_thread_counters'] = 'Os contadores de tópicos foram reconstruidos com sucesso.';
$l['success_rebuilt_user_counters'] = 'As respostas foram recontadas com sucesso.';
$l['success_rebuilt_attachment_thumbnails'] = 'As miniaturas em anexos foram reconstruidas com sucesso.';
$l['success_rebuilt_forum_stats'] = 'As estatísticas do fórum foram reconstruídas com sucesso.';
$l['confirm_proceed_rebuild'] = 'Clique "Continuar" para dar sequencia ao processo de recontagem e reconstrução.';
$l['automatically_redirecting'] = 'Redirecionando Automaticamente...';
$l['recount_reputation'] = 'Recontar reputação';
$l['recount_reputation_desc'] = 'Isso vai recontar a reputação de cada usuário.';
$l['recount_warning'] = 'Recontar Pontos de Aviso';
$l['recount_warning_desc'] = 'Isso vai recontar os pontos de avisos ativos de cada usuário.';
$l['recount_private_messages'] = 'Recontar Mensagens Privadas';
$l['recount_private_messages_desc'] = 'Isso vai recontar as mensagens privadas de cada usuário.';
$l['recount_referrals'] = 'Recontar Referências';
$l['recount_referrals_desc'] = 'Isso vai recontar as referências de cada usuário.';
$l['recount_thread_ratings'] = 'Recontar Avaliações de Tópicos';
$l['recount_thread_ratings_desc'] = 'Isso vai recontar as avaliações de cada tópico.';
$l['rebuild_poll_counters'] = 'Reconstruir contadores de enquete';
$l['rebuild_poll_counters_desc'] = 'Quando isso for executado, os contadores de votos e o número total de votos de cada pesquisa serão atualizados para refletir os valores corretos.';
$l['recount_user_threads'] = 'Recontar contas de tópicos do usuário';
$l['recount_user_threads_desc'] = 'Quando isso é executado, a contagem de tópicos para cada usuário será atualizada para refletir seu valor atual ao vivo com base nos tópicos no banco de dados e fóruns que tenham contagem de tópicos desabilitada.';
$l['success_rebuilt_poll_counters'] = 'Os contadores de enquete foram reconstruídos com sucesso.';
$l['success_rebuilt_user_post_counters'] = 'A contagem de posts do usuário foi relatada com sucesso.';
$l['success_rebuilt_user_thread_counters'] = 'A contagem de tópicos do usuário foi relatada com sucesso.';
$l['success_rebuilt_reputation'] = 'A reputação do usuário foi reconstruída com sucesso.';
$l['success_rebuilt_warning'] = 'Os pontos de aviso do usuário foram reconstruídos com sucesso.';
$l['success_rebuilt_private_messages'] = 'A contagem de mensagens privadas do usuário foi recontada com sucesso.';
$l['success_rebuilt_referral'] = 'A contagem de referência do usuário foi recontada com sucesso.';
$l['success_rebuilt_thread_ratings'] = 'As classificações de tópicos foram relatadas com sucesso.';
