<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:30:05 +0000
// --------------------------------------------------------------------------------

$l['mod_logs'] = 'Logs da Moderação';
$l['mod_logs_desc'] = 'Aqui você pode visualizar, excluir e pesquisar os logs da moderação. Estes logs contem as ações de qualquer usuário que tenha privilégios de moderador no fórum.';
$l['prune_mod_logs'] = 'Excluir os Logs da Moderação';
$l['prune_mod_logs_desc'] = 'Aqui você pode excluir os logs da moderação que se enquadrem em um critério específico.';
$l['no_modlogs'] = 'Não existem entradas de log para o critério selecionado.';
$l['username'] = 'Usuário';
$l['date'] = 'Data';
$l['action'] = 'Ação';
$l['information'] = 'Informação';
$l['ipaddress'] = 'Endereço IP';
$l['forum'] = 'Fórum:';
$l['thread'] = 'Tópico:';
$l['post'] = 'Resposta:';
$l['user_info'] = 'Usuário:';
$l['filter_moderator_logs'] = 'Filtrar Logs da Moderação';
$l['forum_moderator'] = 'Moderador do Fórum:';
$l['sort_by'] = 'Organizar Por:';
$l['results_per_page'] = 'Resultados Por Página:';
$l['all_moderators'] = 'Todos os Moderadores';
$l['older_than'] = 'Mais antigo que ';
$l['forum_name'] = 'Nome do Fórum';
$l['thread_subject'] = 'Assunto do Tópico';
$l['asc'] = 'Ascendente';
$l['desc'] = 'Descendente';
$l['in'] = 'em';
$l['order'] = 'ordem';
$l['days'] = 'dias';
$l['prune_moderator_logs'] = 'Excluir Logs da Moderação';
$l['date_range'] = 'Período:';
$l['all_forums'] = 'Todos os Fóruns';
$l['success_pruned_mod_logs'] = 'Os logs da moderação foram excluídos com sucesso.';
$l['announcement'] = 'Anúncio:';
$l['note_logs_locked'] = 'Por motivos de segurança, os logs com menos de 24 horas não podem ser suprimidos.';
