<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:29:24 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = 'Verificação de Arquivo';
$l['checking'] = 'Verificando...';
$l['file_verification_message'] = 'Ese processo fará uma verificação dos arquivos padrão do MyBB para checar sua validade. Clique em SIM para continuar.<br /> <small>Note por favor, que este processo não pode diferenciar entre modificações customizadas e corrupção dos arquivos. Por isso você deve ter cautela ao reverter arquivos que este procesos indique como "corrompidos".</small>';
$l['error_communication'] = 'Ocorreu um problema de comunicação com o servidor. Por favor tente novamente em alguns minutos.';
$l['file'] = 'Arquivo';
$l['no_corrupt_files_found'] = 'Parabéns! Nenhum arquivo corrompido foi encontrado em sua instalação.';
$l['found_problems'] = 'Problemas Encontrados';
$l['changed'] = 'Alterado';
$l['missing'] = 'Faltando';
$l['status'] = 'Status';
$l['no_problems_found'] = 'Sem problemas detectados';
