<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:29:40 +0000
// --------------------------------------------------------------------------------

$l['user_email_log'] = 'Logs de Email de Usuários';
$l['user_email_log_desc'] = 'Todos os emails enviados de um usuário para outro, além de outros emails específicos são logados e mostrados abaixo. Aqui você pode identificar potenciais usuários que estejam abusando desta função.';
$l['prune_user_email_log'] = 'Excluir Logs de Email de Usuários';
$l['close_window'] = 'Fechar Janela';
$l['user_email_log_viewer'] = 'Visualizador dos Logs de Email de Usuários';
$l['to'] = 'Para';
$l['from'] = 'De';
$l['ip_address'] = 'Endereço IP';
$l['subject'] = 'Assunto';
$l['date'] = 'Data';
$l['email'] = 'Email';
$l['date_sent'] = 'Data de Envio';
$l['deleted'] = 'Excluído';
$l['sent_using_send_thread_feature'] = 'Enviado usando o recurso de Enviar Tópico a um Amigo';
$l['thread'] = 'Tópico:';
$l['find_emails_by_user'] = 'Encontrar todos os emails deste usuário';
$l['find'] = 'Encontrar';
$l['deleted_user'] = 'Usuário Excluído';
$l['email_sent_to_user'] = 'Email enviado ao usuário';
$l['no_logs'] = 'Não existem entradas de log para o critério selecionado.';
$l['filter_user_email_log'] = 'Filtrar logs de email de usuário';
$l['username_is'] = 'Usuário é';
$l['email_contains'] = 'Endereço de Email contem';
$l['subject_contains'] = 'Assunto contem';
$l['find_emails_to_user'] = 'Encontrar todos os emails enviados a este usuário';
$l['error_invalid_user'] = 'O usuário informado não existe.';
$l['email_sent_using_contact_form'] = 'E-mail enviado usando o formulário de contato';
