<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:40:23 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = 'Relatórios de Spam';
$l['spam_logs_desc'] = 'Esta seção permite que você visualize um histórico de usuários bloqueados pelos filtros de spam.';
$l['prune_spam_logs'] = 'Suprimir relatórios de Spam';
$l['prune_spam_logs_desc'] = 'Here you can prune the spam logs matching a specified criteria.';
$l['spam_username'] = 'Aqui você pode suprimir os logs de spam correspondentes a um critério especificado.';
$l['spam_email'] = 'Endereço de e-mail';
$l['spam_ip'] = 'IP';
$l['spam_date'] = 'Data';
$l['spam_confidence'] = 'Confiança';
$l['no_spam_logs'] = 'Nenhum usuário foi bloqueado pelos filtros de spam ainda.';
$l['success_pruned_spam_logs'] = 'Os logs de spam foram suprimidos com sucesso.';
$l['note_logs_locked'] = 'Os logs de spam foram suprimidos com sucesso.';
$l['all_usernames'] = 'Todos os usernames';
$l['all_emails'] = 'Todos os endereços de e-mail';
$l['date_range'] = 'Intervalo de data:';
$l['days'] = 'dias';
$l['filter_spam_logs'] = 'Filtrar relatórios de Spam';
$l['asc'] = 'Ascendendo';
$l['desc'] = 'Descendendo';
$l['search_ip_on_sfs'] = 'Pesquise este IP no Stop Forum Spam';
$l['search'] = 'Pesquisar';
$l['in'] = 'em';
$l['order'] = 'ordem';
$l['sort_by'] = 'Ordenar por';
$l['results_per_page'] = 'Resultados por página';
