<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:42:19 +0000
// --------------------------------------------------------------------------------

$l['system_health'] = 'Estado do Sistema';
$l['system_health_desc'] = 'Aqui você pode visualizar informações sobre o estado do seu sistema.';
$l['utf8_conversion'] = 'Conversão UTF-8';
$l['utf8_conversion_desc'] = 'Você está atualmente convertendo uma tabela do banco de dados para o formato UTF-8. Este processo pode levar várias horas dependendo do tamanho do seu fórum e da tabela. Quando este processo for concluído, você retornará para a página inicial de Conversão UTF-8.';
$l['utf8_conversion_desc2'] = 'Esta ferramenta verifica se as tabelas do banco de dados estão em formato UTF-8 e permite que você as converta se não estiverem.';
$l['convert_all'] = 'Converter Tudo';
$l['converting_to_utf8'] = 'MyBB está atualmente convertendo a tabela "{1}" para UTF-8 a partir do formato {2}.';
$l['convert_to_utf8'] = 'Você irá converter a tabela "{1}" para UTF-8 a partir do formato {2}.';
$l['convert_all_to_utf'] = 'Você irá converter TODAS as tabelas para UTF-8 a partir do formato {1}.';
$l['please_wait'] = 'Por favor, aguarde...';
$l['converting_table'] = 'Convertendo Tabela:';
$l['convert_table'] = 'Converter Tabela';
$l['convert_tables'] = 'Converter Todas as Tabelas';
$l['convert_database_table'] = 'Converter Tabela do Banco de Dados';
$l['convert_database_tables'] = 'Converter Todas as Tabelas do Banco de Dados';
$l['table'] = 'Tabela';
$l['status'] = 'Status';
$l['convert_now'] = 'Converter Agora';
$l['totals'] = 'Totais';
$l['attachments'] = 'Anexos';
$l['total_database_size'] = 'Banco de Dados';
$l['attachment_space_used'] = 'Espaço de Anexos Usado';
$l['total_cache_size'] = 'Tamanho Total do Cache';
$l['estimated_attachment_bandwidth_usage'] = 'Uso de Banda por Anexos';
$l['max_upload_post_size'] = 'Max Envio/Postagem';
$l['average_attachment_size'] = 'Tamanho Médio de Anexos';
$l['stats'] = 'Estatísticas';
$l['task'] = 'Tarefa';
$l['run_time'] = 'Hora de Execução';
$l['next_3_tasks'] = 'Próximas 3 Tarefas';
$l['backup_time'] = 'Hora do Backup';
$l['no_backups'] = 'Não existem backups.';
$l['existing_db_backups'] = 'Backups de Banco de Dados Existentes';
$l['writable'] = 'Gravável';
$l['not_writable'] = 'Não Gravável';
$l['please_chmod_777'] = 'Por favor CHMOD para 777.';
$l['chmod_info'] = 'Por favor altere o CHMOD do arquivo abaixo para o espeficado. Para mais informações sobre CHMOD veja o';
$l['file'] = 'Arquivo';
$l['location'] = 'Localização';
$l['settings_file'] = 'Arquivo de Definições';
$l['config_file'] = 'Arquivo de Configurações';
$l['file_upload_dir'] = 'Diretório de Upload de Arquivos';
$l['avatar_upload_dir'] = 'Diretório de Upload de Avatares';
$l['language_files'] = 'Arquivos de Idioma';
$l['backup_dir'] = 'Diretório de Backups';
$l['cache_dir'] = 'Diretório de Cache';
$l['themes_dir'] = 'Diretório de Temas';
$l['chmod_files_and_dirs'] = 'CHMOD Arquivos e Diretórios';
$l['notice_process_long_time'] = 'Este processo pode levar várias horas dependendo do tamanho do seu fórum e desta tabela.';
$l['check_templates'] = 'Verificar Modelos';
$l['check_templates_desc'] = 'Verifica todos os modelos instalados em busca de falhas de segurança conhecidas.';
$l['check_templates_title'] = 'Verificar a Segurança dos Modelos';
$l['check_templates_info'] = 'Este processo irá verificar os modelos instalados em busca de falhas de segurança que podem afetar o fórum e o servidor onde o fórum está hospedado. Isto pode levar algum tempo, depedendo da quantidade de temas instalados.
<br /><br />Para iniciar, clique no botão abaixo.';
$l['check_templates_info_desc'] = 'Os modelos abaixo possuem falhas de segurança conhecidas. Por favor, verifique-os.';
$l['full_edit'] = 'Edição Completa';
$l['error_chmod'] = 'dos arquivos e diretórios necessários não possuem as configurações apropriadas de CHMOD.';
$l['error_invalid_table'] = 'A tabela especificada não existe.';
$l['error_db_encoding_not_set'] = 'Sua instalação atual do MyBB não está configurada para usar esta ferramenta ainda.';
$l['error_not_supported'] = 'Seu banco de dados atual não é suportado pela ferramenta de conversão UTF-8.';
$l['error_invalid_input'] = 'Ocorreu um problema ao verificar os modelos. Por favor tente novamente ou entre em contato com o MyBB Brasil para ajuda.';
$l['error_master_templates_altered'] = 'Os Modelos Mestres foram modificados. Por favor entre em contato com o MyBB Brasil para ajuda.';
$l['success_templates_checked'] = 'Modelos verificados com sucesso - nenhum problema de segurança encontrado!';
$l['success_all_tables_already_converted'] = 'Todas as tabelas já foram convertidas ou já estão em formato UTF-8.';
$l['success_table_converted'] = 'A tabela "{1}" foi convertida em UTF-8 com sucesso.';
$l['success_chmod'] = 'Todos os arquivos e diretórios necessários possuem as configurações de CHMOD corretas.';
$l['convert_all_to_utf8mb4'] = 'Você está prestes a converter TODAS as tabelas na codificação de idioma Unicode UTF-8 de 4 bytes da codificação {1}.';
$l['converting_to_utf8mb4'] = 'MyBB está atualmente convertendo a tabela "{1}" para a codificação de idioma Unicode UTF-8 de 4 bytes da codificação {2}.';
$l['status_utf8'] = 'UTF-8 Status';
$l['status_utf8mb4'] = 'Suporte UTF-8 de 4 bytes <br /> (requer MySQL 5.5.3 ou superior)';
$l['not_available'] = 'Não disponível';
$l['all_tables'] = 'Todas as Tabelas';
$l['no_tasks'] = 'Não há tarefas em execução neste momento.';
$l['notice_mb4_warning'] = '4-Byte UTF-8 Support requer MySQL 5.5.3 ou superior. Você não poderá importar seu banco de dados em um servidor MySQL com outra versão.';
$l['error_utf8mb4_version'] = 'Sua versão do MySQL não suporta codificação UTF-8 de 4 bytes.';
$l['warning_multiple_encodings'] = 'Recomenda-se não usar diferentes codificações em seu banco de dados. Isso pode causar um comportamento inesperado ou erros do MySQL.';
$l['warning_utf8mb4_config'] = 'Para o suporte completo de 4 bytes UTF-8, você precisa alterar <i>$config[\'database\'][\'codificação\'] = \'utf8\'; </i> para<i>$config[\'database\'][\' Codificação \'] =\' utf8mb4 \'; </i> no seu inc/config.php.';
