<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:44:22 +0000
// --------------------------------------------------------------------------------

$l['user_group_promotions'] = 'Promoções de Grupos';
$l['user_group_promotions_desc'] = 'Aqui você pode gerenciar as promoções de grupos.';
$l['edit_promotion'] = 'Editar Promoções';
$l['edit_promotion_desc'] = 'Aqui você pode gerenciar as promoções que são automaticamente executadas no seu fórum.';
$l['add_new_promotion'] = 'Adicionar Nova Promoção';
$l['add_new_promotion_desc'] = 'Aqui você pode criar novas promoções que são automaticamente executadas no seu fórum.';
$l['title'] = 'Títuulo';
$l['short_desc'] = 'Descrição Curta';
$l['post_count'] = 'Contagem de Respostas';
$l['reputation'] = 'Reputação';
$l['referrals'] = 'Indicações';
$l['time_registered'] = 'Tempo de Registro';
$l['promo_requirements'] = 'Requisitos de Promoção';
$l['promo_requirements_desc'] = 'Selecione um critério que precisa ser atingido para esta promoção. Segure CTRL para selecionar múltiplos critérios.';
$l['greater_than_or_equal_to'] = 'Maior ou igual a';
$l['greater_than'] = 'Maior que';
$l['equal_to'] = 'Igual a ';
$l['less_than_or_equal_to'] = 'Menor ou igual a ';
$l['less_than'] = 'Menor que';
$l['reputation_count'] = 'Contagem de Reputação';
$l['reputation_count_desc'] = 'Informe a quantidade de reputação necessária. Você deve escolher reputação como valor selecionável para isto ser incluído. Selecione o tipo de comparação para reputação.';
$l['referral_count'] = 'Contagem de Indicações';
$l['referral_count_desc'] = 'Informe a quantidade de indicações necessárias. A Contagem de Indicações deve ser selecionada como um valor requerido para que seja incluída. Selecione o tipo de comparação para indicações.';
$l['post_count_desc'] = 'Informe a qualidade de respostas necessárias. Você deve escolher a contagem de respostas como valor selecionável para isto ser incluído. Selecione o tipo de comparação para respostas.';
$l['hours'] = 'Horas';
$l['days'] = 'Dias';
$l['weeks'] = 'Semanas';
$l['months'] = 'Meses';
$l['years'] = 'Anos';
$l['time_registered_desc'] = 'Informe o número de horas, dias, semanas, meses ou anos que este usuário precisa estar registrado. Você deve escolher o tempo de registro como valor selecionável para isto ser incluído. Selecione se o tempo de registro precisa ser contado em horas, dias, semanas, meses ou anos.';
$l['all_user_groups'] = 'Todos os Grupos';
$l['orig_user_group'] = 'Grupo Original';
$l['orig_user_group_desc'] = 'Selecione que grupo ou grupos de usuários o usuário precisa fazer parte para a promoção ser executada. Segure CTRL para selecionar múltiplos grupos.';
$l['new_user_group'] = 'Novo Grupo';
$l['new_user_group_desc'] = 'Selecione qual o grupo que o usuário passará a fazer parte após esta promoção ser executada.';
$l['primary_user_group'] = 'Grupo Primário';
$l['secondary_user_group'] = 'Grupo Secundário';
$l['user_group_change_type'] = 'Tipo de Mudança de Grupo';
$l['user_group_change_type_desc'] = 'Selecione \'Grupo Primário\' se o grupo primário do usuário deva ser mudado para o novo grupo. Selecione \'SGrupo Secundário\' se o novo grupo do usuário deva ser adicionado como um grupo secundário no seu perfil.';
$l['enabled'] = 'Habilitado?';
$l['enable_logging'] = 'Habilitar Log?';
$l['promotion_logs'] = 'Logs de Promoções';
$l['view_promotion_logs'] = 'Ver Logs de Promoções';
$l['view_promotion_logs_desc'] = 'Aqui você pode visualizar as promoções que já executaram.';
$l['promoted_user'] = 'Usuário Promovido';
$l['time_promoted'] = 'Data de Promoção';
$l['no_promotion_logs'] = 'Não existem promoções logadas no momento.';
$l['promotion_manager'] = 'Gerenciador de Promoções';
$l['promotion'] = 'Promoções';
$l['disable_promotion'] = 'Desativar Promoção';
$l['enable_promotion'] = 'Habilitar Promoção';
$l['delete_promotion'] = 'Excluir Promoção';
$l['no_promotions_set'] = 'Não existem promoções habilitadas no momento.';
$l['update_promotion'] = 'Salvar Promoção';
$l['multiple_usergroups'] = 'Grupos Múltiplos';
$l['secondary'] = 'Secundário';
$l['primary'] = 'Primário';
$l['error_no_promo_id'] = 'Você não informou uma id de promoção';
$l['error_invalid_promo_id'] = 'Você não informou uma id de promoção válida';
$l['error_no_title'] = 'Você não informou um título para esta promoção';
$l['error_no_desc'] = 'Você não informou uma descrição para esta promoção';
$l['error_no_requirements'] = 'Você não selecionou ao menos um requisito para esta promoção';
$l['error_no_orig_usergroup'] = 'Você não selecionou ao menos um grupo de usuário original para esta promoção';
$l['error_no_new_usergroup'] = 'Você não selecionou ao menos um novo grupo de usuário para esta promoção';
$l['error_no_usergroup_change_type'] = 'Você não selecionou ao menos um método de mudança de grupo para esta promoção';
$l['success_promo_disabled'] = 'A promoção de grupo selecionada foi desativada com sucesso.';
$l['success_promo_deleted'] = 'A promoção de grupo selecionada foi excluída com sucesso.';
$l['success_promo_enabled'] = 'A promoção de grupo selecionada foi habilitada com sucesso.';
$l['success_promo_updated'] = 'A promoção de grupo selecionada foi atualizada com sucesso.';
$l['success_promo_added'] = 'A promoção foi criada com sucesso.';
$l['confirm_promo_disable'] = 'Tem certeza que deseja desabilitar esta promoção?';
$l['confirm_promo_deletion'] = 'Tem certeza que deseja excluir esta promoção?';
$l['thread_count'] = 'Contagem de tópicos';
$l['time_online'] = 'Tempo Online';
$l['warning_points'] = 'Pontos de advertência';
$l['warning_points_desc'] = 'Digite o número de pontos de aviso necessários. Os pontos de advertência devem ser selecionados como um valor necessário para que isso seja incluído. Selecione o tipo de comparação para os pontos de aviso.';
$l['thread_count_desc'] = 'Digite o número de tópicos necessários. A contagem de tópicos deve ser selecionada como um valor necessário para que isso seja incluído. Selecione o tipo de comparação para os tópicos.';
$l['time_online_desc'] = 'Digite o número de horas, dias, semanas, meses ou anos para os quais esse usuário deve estar online. O tempo online deve ser selecionado como um valor necessário para que isso seja incluído. Selecione se o tempo gasto em linha deve ser contado em horas, dias, semanas, meses ou anos.';
