<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:36:30 +0000
// --------------------------------------------------------------------------------

$l['awaiting_activation'] = 'Aguardando ativação';
$l['awaiting_activation_desc'] = 'Aqui você pode gerenciar usuários que aguardam ativação. Observe que qualquer usuário que esteja aguardando a ativação de e-mail não precisará confirmar seu e-mail se eles estiverem ativados aqui.';
$l['manage_awaiting_activation'] = 'Gerenciar Aguardando Ativação';
$l['no_users_awaiting_activation'] = 'Atualmente, não há usuários aguardando ativação.';
$l['username'] = 'Nome de usuário';
$l['registered'] = 'Registrado';
$l['last_active'] = 'Última atividade';
$l['email'] = 'E-mail';
$l['ipaddress'] = 'IP';
$l['type'] = 'Tipo';
$l['email_activation'] = 'Aguardando a ativação de e-mail';
$l['administrator_activation'] = 'Aguardando a ativação do administrador';
$l['admin_activation_coppa'] = 'Aguardando a ativação do administrador (COPPA)';
$l['activate_users'] = 'Ativar usuários';
$l['delete_users'] = 'Excluir usuários';
$l['confirm_activate_users'] = 'Tem certeza de que deseja ativar os usuários selecionados?';
$l['confirm_delete_users'] = 'Tem certeza de que deseja excluir os usuários selecionados?';
$l['no_users_selected'] = 'Você não selecionou nenhum usuário.';
$l['success_users_deleted'] = 'O(s) usuário(s) selecionado(s) foram excluídos.';
$l['success_users_activated'] = 'O(s) usuário(s) selecionado(s) foram ativados.';
$l['emailsubject_activateaccount'] = 'Ativação da conta em {1}';
$l['email_adminactivateaccount'] = '{1},

O administrador ativou sua conta do fórum em {2}.

Para prosseguir, acesse

{3}

Você poderá fazer o login com as credenciais que você registrou.

Obrigado,
{2} Staff';
