<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:51:16 +0000
// --------------------------------------------------------------------------------

$l['users_and_groups'] = 'Usuários e Grupos';
$l['users'] = 'Usuários';
$l['groups'] = 'Grupos';
$l['user_titles'] = 'Títulos de Usuário';
$l['banning'] = 'Banimento';
$l['admin_permissions'] = 'Permissões de Admin';
$l['mass_mail'] = 'Email em Massa';
$l['group_promotions'] = 'Promoções de Grupo';
$l['can_manage_users'] = 'Pode gerenciar usuários?';
$l['can_manage_user_groups'] = 'Pode gerenciar grupos?';
$l['can_manage_user_titles'] = 'Pode gerenciar títulos de usuário?';
$l['can_manage_user_bans'] = 'Pode gerenciar banimentos?';
$l['can_manage_admin_permissions'] = 'Pode gerenciar permissões de admin?';
$l['can_send_mass_mail'] = 'Pode enviar email em massa?';
$l['can_manage_group_promotions'] = 'Pode gerenciar promoções?';
$l['awaiting_activation'] = 'Aguardando Aprovação';
$l['can_manage_awaiting_activation'] = 'Pode gerenciar a ativação?';
