<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 19:51:32 +0000
// --------------------------------------------------------------------------------

$l['user_titles'] = 'Títulos de Usuário';
$l['user_titles_desc'] = 'Esta seção permite gerenciar os títulos de usuário.';
$l['add_new_user_title'] = 'Novo Título de Usuário';
$l['add_new_user_title_desc'] = 'Esta seção permite adicionar um novo título de usuário. <i>Nota: Isto <strong>não</strong> é o <u><a href="index.php?module=user-group_promotions">sistema de promoções.</a></u></i>';
$l['error_missing_title'] = 'Você não informou um nome para este título';
$l['error_missing_posts'] = 'Você não informou um número mínimo de respostas para este título';
$l['error_invalid_user_title'] = 'Você informou um título de usuário inválido';
$l['success_user_title_created'] = 'O novo título de usuário foi criado com sucesso.';
$l['success_user_title_updated'] = 'O novo título de usuário foi atualizado com sucesso.';
$l['success_user_title_deleted'] = 'O novo título de usuário foi excluído com sucesso.';
$l['title_to_assign'] = 'Título';
$l['title_to_assign_desc'] = 'Este título será mostrado abaixo do nome do usuário se ele não especificar um título customizado.';
$l['minimum_posts'] = 'Mínimo de Respostas';
$l['minimum_posts_desc'] = 'O número mínimo de respostas para que o usuário receba este título.';
$l['number_of_stars'] = 'Número de Estrelas';
$l['number_of_stars_desc'] = 'Informe o número de estrelas para serem mostradas juntamente com este título. Escreva 0 para não mostrar estrelas.';
$l['star_image'] = 'Imagem de Estrela';
$l['star_image_desc'] = 'Se este título de usuário mostrar estrelas, informe o caminho para a imagem de estrela aqui. Se em branco, a imagem de estrela do grupo será mostrada. Use {theme} para informar o diretório de imagens padrão do tema em uso.';
$l['save_user_title'] = 'Salvar Título de Usuário';
$l['edit_user_title'] = 'Editar Título de Usuário';
$l['edit_user_title_desc'] = 'Esta seção permite editar um título de usuário.';
$l['user_title_deletion_confirmation'] = 'Tem certeza que deseja excluir este título de usuário?';
$l['manage_user_titles'] = 'Gerenciar Títulos de Usuários';
$l['user_title'] = 'Título de Usuário';
$l['no_user_titles'] = 'Você não tem títulos de usuário definidos no momento';
$l['error_cannot_have_same_posts'] = 'Este título do usuário não pode ter o mesmo número mínimo de postagens que outro título';
