<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:32:07 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Versão Completa:';
$l['archive_replies'] = 'Respostas';
$l['archive_reply'] = 'Responder';
$l['archive_pages'] = 'Páginas:';
$l['archive_note'] = 'Esta é uma versão reduzida do nosso conteúdo. <a href="{1}">Ver versão completa</a> com o formato adequado.';
$l['archive_reference_urls'] = 'URL\'s de Referência';
$l['archive_nopermission'] = 'Desculpe,mas não tem permissão para aceder a este recurso.';
$l['error_nothreads'] = 'Não existem de momento tópicos neste fórum.';
$l['error_unapproved_thread'] = 'Este tópico está em moderação. Por favor <a href="{1}">veja a versão completa</a> para ver os conteúdos deste tópico.';
$l['archive_not_found'] = 'A página solicitada não foi encontrada neste servidor';
$l['error_nopermission'] = 'Você não tem permissão para ver tópicos neste fórum.';
$l['error_mustlogin'] = 'Este quadro de avisos exige que todos os usuários façam o login.';
