<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:19:19 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Contate-nos';
$l['contact_no_message'] = 'Você não forneceu uma mensagem para enviar.';
$l['contact_no_subject'] = 'É necessário inserir um assunto.';
$l['contact_no_email'] = 'Você deve inserir um endereço de email válido.';
$l['contact_success_message'] = 'Sua mensagem foi enviada com sucesso ao Administrador.';
$l['contact_subject'] = 'Assunto';
$l['contact_subject_desc'] = 'Breve resumo do tópico da sua mensagem.';
$l['contact_message'] = 'Mensagem';
$l['contact_message_desc'] = 'Descreva sua preocupação nesta área em detalhes.';
$l['contact_email'] = 'E-mail';
$l['contact_email_desc'] = 'Digite seu e-mail para que possamos contatá-lo de volta.';
$l['contact_send'] = 'Enviar';
$l['subject_too_long'] = 'O assunto é muito longo. Digite um assunto menor do que {1} caracteres (atualmente {2}).';
$l['message_too_short'] = '92/5000
A mensagem é muito curta. Digite uma mensagem com mais de {1} caracteres (atualmente {2}).';
$l['message_too_long'] = 'A mensagem é muito longa. Digite uma mensagem com menos de {1} caracteres (atualmente {2}).';
$l['error_stop_forum_spam_spammer'] = 'Desculpe, {1} corresponde ao de um spammer conhecido e, portanto, seu envio de contato foi bloqueado.';
$l['error_stop_forum_spam_fetching'] = 'Desculpe, algo correu errado, verificando sua mensagem contra um banco de dados de spammer. Provavelmente o banco de dados não pôde ser acessado. Por favor, tente novamente mais tarde.';
