<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:38:35 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Não inseriu o nome de usuário, por favor insira-o.';
$l['userdata_banned_username'] = 'O nome de usuário que inseriu foi banido, tente outro por favor.';
$l['userdata_bad_characters_username'] = 'O nome de usuário escolhido contém caracteres inválidos. Escreva um nome de usuário diferente.';
$l['userdata_invalid_username_length'] = 'O nome de usuário escolhido tem um tamanho inválido. Escreva um nome de usuário diferente, entre {1} e {2} caracteres.';
$l['userdata_invalid_usertitle_length'] = 'O título de usuário escolhido tem um tamanho inválido. Escreva um título de usuário diferente, com um máximo de {1} caracteres.';
$l['userdata_username_exists'] = 'O nome de usuário que inseriu já existe, tente outro por favor.';
$l['userdata_invalid_password_length'] = 'A senha escolhida tem um tamanho inválido. Escreva uma senha diferente, entre {1} e {2} caracteres.';
$l['userdata_no_complex_characters'] = 'A senha que você digitou não é suficientemente complexa. Digite uma senha que tenha pelo menos {1} caracteres e contenha uma letra maiúscula, uma letra minúscula e um número.';
$l['userdata_passwords_dont_match'] = 'A senha inserida como confirmação não coincide com a original. Por favor confira a senha.';
$l['userdata_missing_email'] = 'Não inseriu nenhuma email. Insira um por favor.';
$l['userdata_invalid_email_format'] = 'O email inserido é inválido. Insira outro por favor.';
$l['userdata_emails_dont_match'] = 'O endereço de email inserido como confirmação não coincide com o original. Por favor confira ambos os endereços de email.';
$l['userdata_banned_email'] = 'O endereço de email inserido está de momento bloqueado para utilização. Por favor insira outro.';
$l['userdata_email_already_in_use'] = 'Inseriu um email que já está a ser utilizado por outro membro. Por favor tente outro adereço de email.';
$l['userdata_dob_required'] = 'Não selecionou nenhuma data de nascimento. Selecione a sua data de nascimento por favor. Contudo pode escolher para esconder a data de nascimento dos usuários.';
$l['userdata_invalid_website'] = 'O endereço do site inserido é inválido. Por favor insira um endereço válido ou deixe este campo vazio.';
$l['userdata_invalid_icq_number'] = 'O número de ICQ inserido é inválido. Insira um número de ICQ que seja válido ou deixe este campo vazio por favor.';
$l['userdata_invalid_msn_address'] = 'O endereço de MSN inserido é inválido. Insira um endereço de MSN que seja válido ou deixe este campo vazio por favor.';
$l['userdata_invalid_birthday'] = 'A data de nascimento inserida é inválida. Insira uma data de nascimento que seja válida ou deixe este campo vazio por favor.';
$l['userdata_invalid_birthday_coppa'] = 'Para verificar a sua idade, insira o ano em que nasceu por favor. Pode esconder a idade e o ano de nascimento as opções de perfil.';
$l['userdata_invalid_birthday_coppa2'] = 'Tem que ter pelo menos 13 anos de idade para ser um membro desta comunidade. Contacte um administrador por favor.';
$l['userdata_invalid_birthday_privacy'] = 'Por favor, escolha uma opção de privacidade do aniversário válida.';
$l['userdata_invalid_referrer'] = 'O usuário referido acerca deste site não existe. Escolha um usuário válido ou deixe este campo vazio.';
$l['userdata_invalid_language'] = 'A linguagem escolhida não existe. Escolha uma linguagem que exista por favor.';
$l['userdata_missing_returndate'] = 'Um ou mais campos estão em falta na data de retorno especificada. Verifique se escolheu um dia, um mês e o ano por favor.';
$l['userdata_missing_required_profile_field'] = 'Não escolheu uma opção para o campo "{1}". Por favor insira ou escolha uma opção para este campo.';
$l['userdata_bad_profile_field_values'] = 'Não escolheu uma opção válida para o campo "{1}". Escolha uma opção das presentes por favor.';
$l['userdata_max_limit_reached'] = 'Inseriu um número inválido de caracteres para o campo "{1}". Por favor não use mais do que {2} caracteres.';
$l['userdata_invalid_checkfield'] = 'Foi detectado que este formulário foi enviado por um spam bot. Se isto é um erro, contacte o administrador por favor.';
$l['userdata_invalid_postnum'] = 'O número de mensagens inserido é inválido. Por favor insira um número válido ou deixe este campo vazio.';
$l['userdata_bad_password_security'] = 'A senha que você inseriu é igual ao seu nome de usuário ou endereço de e-mail. Digite uma senha mais forte.';
$l['userdata_invalid_style'] = 'O estilo que você selecionou é inválido. Selecione um estilo válido.';
$l['userdata_bad_profile_field_value'] = 'Você não inseriu um valor válido para o campo "{1}". Digite um valor válido antes de continuar.';
$l['userdata_invalid_threadnum'] = 'A contagem de tópicos que você inseriu é inválida. Digite uma contagem de threads válida ou deixe o campo vazio.';
$l['userdata_too_many_sig_images'] = 'Lamentamos, mas não podemos atualizar sua assinatura porque ela contém muitas imagens. Remova algumas imagens da sua assinatura para continuar.';
$l['userdata_too_many_sig_images2'] = '<Strong> Nota: </ strong> A quantidade máxima de imagens para assinaturas é {1}.';
$l['userdata_sig_too_long'] = 'Você não pode atualizar sua assinatura porque é muito longa. O comprimento máximo para assinaturas é {1} caracteres.';
$l['userdata_sig_remove_chars_plural'] = 'Remova os caracteres {1} e tente novamente.';
$l['userdata_sig_remove_chars_singular'] = 'Remova 1 caractere e tente novamente.';
