<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:30:07 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Você não pode dar avisos a ninguém mais, já que atingiu seu limite na quantidade de avisos que você pode distribuir por dia.<br /><br /> O número máximo de avisos que você pode distribuir por dia é {1}."';
$l['warnings_error_invalid_user'] = 'O usuário selecionado não existe.';
$l['warnings_error_invalid_post'] = 'O post selecionado não existe.';
$l['warnings_error_cannot_warn_self'] = 'Você não pode adicionar ao seu próprio nível de aviso.';
$l['warnings_error_user_reached_max_warning'] = 'Este usuário não pode ser avisado porque já alcançou o nível máximo de aviso.';
$l['warnings_error_no_note'] = 'Você não inseriu nenhuma nota administrativa para este aviso.';
$l['warnings_error_invalid_type'] = 'Você selecionou um tipo de aviso inválido.';
$l['warnings_error_cant_custom_warn'] = 'Você não tem permissão para dar avisos aos usuários.';
$l['warnings_error_no_custom_reason'] = 'Você não inseriu um motivo para o seu aviso.';
$l['warnings_error_invalid_custom_points'] = 'Você não inseriu um número válido de pontos para adicionar ao nível de aviso desse usuário. Você precisa inserir um valor numérico maior que 0 mas não maior do que {1}.';
$l['warnings_error_invalid_expires_period'] = 'Você digitou um tipo de expiração inválido.';
