<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:24:45 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Você inseriu uma combinação inválida de nome de usuário/senha. <br /><br />Se você esqueceu sua senha, por favor <a href="member.php?action=lostpw"> para fazer uma nova</a>.';
$l['logindata_invalidpwordusernameemail'] = 'Você inseriu uma combinação de e-mail/senha inválida. <br /><br />Se você esqueceu sua senha, por favor <a href="member.php?action=lostpw"> para fazer uma nova</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'Você inseriu uma senha inválida de nome de usuário/senha ou e-mail/senha. <br /><br />Se você esqueceu sua senha, por favor <a href="member.php?action=lostpw"> para fazer uma nova</a>.';
$l['logindata_regimageinvalid'] = 'O código de verificação de imagem que você inseriu estava incorreto. Digite o código exatamente como ele aparece na imagem.';
$l['logindata_regimagerequired'] = 'Preencha o código de verificação da imagem para continuar o processo de login. Digite o código exatamente como ele aparece na imagem.';
