<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:35:25 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'O ID de usuário não existe, por favor insira um que seja válido.';
$l['postdata_firstpost_no_subject'] = 'O tópico não têm título, por favor insira um.';
$l['postdata_missing_subject'] = 'Não escreveu nenhum título, por favor insira um.';
$l['postdata_missing_message'] = 'Não escreveu a mensagem, por favor escreva-a.';
$l['postdata_message_too_long'] = 'A mensagem está longa demais. A mensagem tem que ter menos de {1} caracteres (atualmente tem {2}).';
$l['postdata_message_too_short'] = 'A mensagem está curta. A mensagem tem que ter mais de {1} caracteres.';
$l['postdata_subject_too_long'] = 'O assunto está muito longo. Por favor insira um assunto menor do que 85 caracteres (actualmente {1}).';
$l['postdata_post_flooding'] = 'Estás criando mensagens rápido demais após ter criado uma mensagem anterior. Por favor aguarde {1} segundos.';
$l['postdata_post_flooding_one_second'] = 'Estás criando mensagens rápido demais após ter criado uma anterior mensagem. Aguarde 1 segundo.';
$l['postdata_too_many_images'] = 'A mensagem inserida tem  {1} imagens, onde apenas são permitidas {2} imagens por mensagem. Por favor diminua o número de imagens para cumprir o este limite.';
$l['postdata_too_many_videos'] = 'A mensagem inserida tem {1} vídeos, onde apenas s~so permitidos {2} videos por mensagem. Por favor diminua o número de vídeos para cumprir este limite.';
$l['postdata_invalid_prefix'] = 'O prefixo seleccionado é inválido. Seleccione um prefixo válido';
$l['thread_closed'] = 'Tópico Fechado';
$l['thread_opened'] = 'Tópico Aberto';
$l['thread_stuck'] = 'Tópico Fixo';
$l['thread_unstuck'] = 'Tópico Liberto';
$l['postdata_banned_username'] = 'O nome de usuário que você inseriu pode não estar registrado. Por favor insira um nome de usuário diferente.';
$l['postdata_bad_characters_username'] = 'O nome de usuário que você inseriu contém caracteres inválidos. Por favor insira um nome de usuário diferente.';
$l['postdata_invalid_username_length'] = 'O nome de usuário que você inseriu é de comprimento inválido. Digite um nome de usuário entre os caracteres {1} e {2}.';
$l['postdata_username_exists'] = 'O nome de usuário que você inseriu já existe. Por favor insira um nome de usuário diferente.';
$l['postdata_require_prefix'] = 'Este fórum requer um prefixo de tópico a ser definido. Selecione um prefixo válido.';
