<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:41:39 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'Editar Mensagem';
$l['edit_post'] = 'Editar esta Mensagem';
$l['delete_post'] = 'Eliminar Mensagem';
$l['delete_q'] = 'Eliminar?';
$l['delete_1'] = 'Para eliminar esta mensagem, marque a caixa de verificação à esquerda e depois clique no botão à direita.';
$l['delete_2'] = '<b>Nota:</b> se esta mensagem é a primeira mensagem de um tópico, apagando-a irá resultar na eliminação do tópico inteiro.';
$l['subject'] = 'Assunto';
$l['your_message'] = 'A sua Mensagem';
$l['post_options'] = 'Opções de Mensagem:';
$l['options_sig'] = '<strong>Assinatura:</strong> Incluir assinatura. (apenas usuárioes registrados)';
$l['options_emailnotify'] = '<strong>Notificação de Email:</strong> receber um Email sempre que houver uma nova resposta. (apenas usuárioes registrados)';
$l['options_disablesmilies'] = '<strong>Desativar Sorrisos:</strong> Desativar sorrisos para que não apareçam nesta mensagem.';
$l['preview_post'] = 'Mensagem Anterior';
$l['update_post'] = 'Atualizar Mensagem';
$l['poll'] = 'Votação:';
$l['poll_desc'] = 'Excepcionalmente você pode anexar uma votação a este tópico.';
$l['poll_check'] = 'Quero inserir uma votação';
$l['num_options'] = 'Número de opções:';
$l['max_options'] = '(Máximo: {1})';
$l['delete_now'] = 'Eliminar agora';
$l['edit_time_limit'] = 'Desculpe, mas você não pode editar a sua mensagem. O Administrador definiu que as mensagens só podem ser editadas num prazo de {1} minutos após serem colocadas.';
$l['no_prefix'] = 'Sem Prefixo';
$l['redirect_nodelete'] = 'A mensagem não foi eliminada, porque você não selecionou a opção "Eliminar" na caixa de verificação.';
$l['redirect_postedited'] = 'Obrigado, esta mensagem foi editada.<br />';
$l['redirect_postedited_redirect'] = 'Você vai agora retornar ao Tópico.';
$l['redirect_postedited_poll'] = 'Obrigado, esta mensagem foi editada. <br />Porque optou por inserir uma votação, você vai ser redirecionado para a página de criação de votações.';
$l['error_invalidpost'] = 'Desculpe, mas parece que seguiu um endereço inválido. Por favor, tenha a certeza de que a mensagem especificada existe e tente novamente.';
$l['redirect_threaddeleted'] = 'Obrigado, o Tópico foi eliminado.<br />Vai agora retornar ao fórum.';
$l['redirect_postdeleted'] = 'Obrigado, a Mensagem foi eliminada.<br />Vai agora retornar ao Tópico.';
$l['redirect_threadclosed'] = 'Você não pode editar mensagens existentes neste tópico, porque o tópico foi encerrado por um Moderador.';
$l['redirect_post_moderation'] = 'O Administrador especificou que toda a edição de mensagens requer moderação. Vai agora retornar ao Tópico.';
$l['redirect_thread_moderation'] = 'O Administrador especificou que toda a edição de Tópicos requer moderação. Vai agora retornar ao índice do Fórum.';
$l['thread_deleted'] = 'Tópico Eliminado';
$l['post_deleted'] = 'Mensagem Eliminada';
$l['editreason'] = 'Motivo da edição:';
$l['redirect_norestore'] = 'A postagem não foi restaurada porque você não marcou a caixa de seleção "Restaurar".';
$l['redirect_threadrestored'] = 'Obrigado, o tópico foi restaurado.<br /> Você será devolvido ao fórum.';
$l['redirect_postrestored'] = 'Obrigado, o post foi restaurado.<br /> Agora você será devolvido ao tópico';
$l['error_already_delete'] = 'Desculpe, mas esta postagem já foi excluída.';
$l['thread_soft_deleted'] = 'Tópico excluído suavemente';
$l['post_soft_deleted'] = 'Post excluído suavemente';
$l['thread_restored'] = 'Tópico Restaurado';
$l['post_restored'] = 'Post Restaurado';
$l['error_already_deleted'] = 'A publicação selecionada já foi excluída.';
