<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:10:22 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Inserir Tópico';
$l['moderated_by'] = 'Moderado por:';
$l['nothreads'] = 'Desculpe, mas no momento não existem Tópicos neste Fórum, com as opções limitadas à data e hora especificada.';
$l['search_forum'] = 'Pesquisar no Fórum:';
$l['thread'] = 'Tópico';
$l['author'] = 'Autor';
$l['replies'] = 'Respostas';
$l['views'] = 'Visualizações    ';
$l['lastpost'] = 'Última Mensagem';
$l['rating'] = 'Avaliação';
$l['markforum_read'] = 'Marcar o Fórum Como Lido';
$l['subscribe_forum'] = 'Subscrever Este Fórum';
$l['unsubscribe_forum'] = 'Anular Subscrição deste Fórum';
$l['clear_stored_password'] = 'Limpar senha armazenada neste Fórum';
$l['sort_by_subject'] = 'Ordenar por: Assunto';
$l['sort_by_lastpost'] = 'Ordenar por: Última Mensagem';
$l['sort_by_starter'] = 'Ordenar por: Autor';
$l['sort_by_started'] = 'Ordenar por: Data de Criação';
$l['sort_by_rating'] = 'Ordenar por: Avaliação';
$l['sort_by_replies'] = 'Ordenar por: Respostas';
$l['sort_by_views'] = 'Ordenar por: Visualizações';
$l['sort_order_asc'] = 'Ordem: Ascendente';
$l['sort_order_desc'] = 'Ordem: Descendente';
$l['datelimit_1day'] = 'De: Hoje';
$l['datelimit_5days'] = 'De: 5 Dias Atrás';
$l['datelimit_10days'] = 'De: 10 Dias Atrás';
$l['datelimit_20days'] = 'De: 20 Dias Atrás';
$l['datelimit_50days'] = 'De: 50 Dias Atrás';
$l['datelimit_75days'] = 'De: 75 Dias Atrás';
$l['datelimit_100days'] = 'De: 100 Dias Atrás';
$l['datelimit_lastyear'] = 'De: Último Ano';
$l['datelimit_beginning'] = 'De: Início';
$l['new_thread'] = 'Novas Mensagens';
$l['new_hot_thread'] = 'Tópico Popular (Com Novidades)';
$l['posts_by_you'] = 'Contém Mensagens Suas';
$l['no_new_thread'] = 'Sem Novas Mensagens';
$l['hot_thread'] = 'Tópico Popular (sem novidades)';
$l['locked_thread'] = 'Tópico bloqueado';
$l['goto_first_unread'] = 'Ir para a primeira mensagem não lida';
$l['pages'] = 'Páginas:';
$l['pages_last'] = 'Última';
$l['users_browsing_forum'] = 'usuários a verem este fórum:';
$l['users_browsing_forum_guests'] = '{1} Visitante(s)';
$l['users_browsing_forum_invis'] = '{1} usuário(s) invisível(s)';
$l['delayed_moderation'] = 'Moderação agendada';
$l['inline_thread_moderation'] = 'Moderação do tópico em linha:';
$l['close_threads'] = 'Fechar Tópicos';
$l['open_threads'] = 'Abrir Tópicos';
$l['stick_threads'] = 'Fixar Tópicos';
$l['unstick_threads'] = 'Libertar Tópicos';
$l['delete_threads'] = 'Apagar Tópicos';
$l['move_threads'] = 'Mover Tópicos';
$l['approve_threads'] = 'Aprovar Tópicos';
$l['unapprove_threads'] = 'Não Aprovar Tópicos';
$l['inline_go'] = 'Ir';
$l['clear'] = 'Limpar';
$l['sub_forums_in'] = 'Fóruns em \'{1}\'';
$l['forum_rules'] = '{1} - Regras';
$l['subforums'] = '<strong>Sub Foruns:</strong>';
$l['asc'] = 'asc';
$l['desc'] = 'desc';
$l['forum_announcements'] = 'Anúncios do Fórum';
$l['sticky_threads'] = 'Tópicos Importantes';
$l['normal_threads'] = 'Tópicos Normais';
$l['icon_dot'] = 'Contém Mensagens Suas. ';
$l['icon_no_new'] = 'Sem Mensagens Novas.';
$l['icon_new'] = 'Mensagens Novas.';
$l['icon_hot'] = ' Tópico Popular.';
$l['icon_lock'] = ' Tópico bloqueado.';
$l['attachment_count'] = 'Este tópico contém 1 anexo.';
$l['attachment_count_multiple'] = 'Este tópico contém {1} anexos.';
$l['rss_discovery_forum'] = 'Últimos Tópicos em {1}';
$l['forum_unapproved_posts_count'] = 'Existem de momento {1} mensagens por aprovar neste fórum.';
$l['forum_unapproved_post_count'] = 'Existe de momento 1 mensagem por aprovar neste fórum.';
$l['forum_unapproved_threads_count'] = 'Existem de momento {1} tópicos por aprovar neste fórum.';
$l['forum_unapproved_thread_count'] = 'Existe de momento 1 tópico por aprovar neste fórum.';
$l['thread_unapproved_posts_count'] = 'Existem de momento {1} mensagens por aprovar neste tópico.';
$l['thread_unapproved_post_count'] = 'Existe de momento 1 mensagem por aprovar neste tópico.';
$l['page_selected'] = 'Todos os <strong>{1}</strong> tópicos nesta página estão selecionados.';
$l['all_selected'] = 'Todos os <strong>{1}</strong> tópicos neste fórum estão selecionados.';
$l['select_all'] = 'Selecionar todos os <strong>{1}</strong> tópicos neste fórum.';
$l['clear_selection'] = 'Limpar seleção.';
$l['error_containsnoforums'] = 'Desculpe, mas o fórum está tentanto visualizar não contém nenhum fórum ou subfórum agregado.';
$l['nopermission'] = 'Desculpe, mas você não tem permissão para ver os tópicos neste fórum.';
$l['prefix'] = 'Prefixo:';
$l['prefix_all'] = 'Prefixo: Qualquer/Sem Prefixo.';
$l['prefix_any'] = 'Prefixo: Qualquer Prefixo.';
$l['prefix_none'] = 'Prefixo: Sem Prefixo.';
$l['soft_delete_threads'] = 'Deletar Suavemente Tópicos';
$l['restore_threads'] = 'Restaurar Tópicos';
$l['deleted_thread'] = 'Tópico Deletado';
$l['inline_edit_description'] = '(Click e segure para editar)';
