<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 14:31:24 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Olá Mundo!';
$l['hello_add'] = 'Adicionar';
$l['hello_add_message'] = 'Adicionar Mensagem';
$l['hello_empty'] = 'Nenhuma mensagem foi encontrada.';
$l['hello_message_empty'] = 'Mensagem não pode ser vazia.';
$l['hello_done'] = 'Adicionou uma nova mensagem com sucesso.';
