<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:52:43 +0000
// --------------------------------------------------------------------------------

$l['d1_name'] = 'Registro de usuário';
$l['d1_desc'] = 'Benefícios e privilégios para o registro do usuário.';
$l['d1_document'] = 'Algumas partes deste fórum podem exigir que você seja logado e registrado. O registro é gratuito e leva alguns minutos para ser concluído.
<br /> <br /> Você é encorajado a se registrar; Uma vez que você se registrar, você poderá enviar mensagens, definir suas próprias preferências e manter um perfil.
<br /> <br /> Alguns dos recursos que geralmente exigem registro são assinaturas, mudança de estilos, acesso ao seu Bloco de Notas Pessoal e membros do fórum de e-mail.';
$l['d2_name'] = 'Atualizando Perfil';
$l['d2_desc'] = 'Alterando seus dados atualmente registrados.';
$l['d2_document'] = 'Em algum momento durante a sua estadia, você pode decidir que precisa atualizar algumas informações, como suas informações de mensagens instantâneas, sua senha ou seu endereço de e-mail. Você pode alterar qualquer uma dessas informações em seu painel de controle do usuário. Para acessar este painel de controle, basta clicar no link no canto superior direito da maioria das páginas intituladas "Usuário CP". A partir daí, basta escolher o link apropriado na seção "Seu perfil" e alterar ou atualizar os itens desejados e, em seguida, clicar no botão enviar localizado na parte inferior da página para que as alterações entrem em vigor.';
$l['d3_name'] = 'Uso de cookies no MyBB';
$l['d3_desc'] = 'O MyBB usa cookies para armazenar certas informações sobre seu registro.';
$l['d3_document'] = 'O MyBB faz uso de cookies para armazenar suas informações de login se você estiver registrado e sua última visita se você não estiver.
<br /> <br /> Os cookies são pequenos documentos de texto armazenados em seu computador; Os cookies definidos por este fórum só podem ser usados neste site e não representam risco de segurança.
<br /> <br /> Os cookies neste fórum também acompanham os tópicos específicos que você leu e quando você os lê pela última vez.
<br /> <br /> Para limpar todos os cookies definidos por este fórum, você pode clicar em <a href="misc.php?action=clearcookies&amp;my_post_key={1}"> aqui </a>.';
$l['d4_name'] = 'Efetuar login e sair';
$l['d4_desc'] = 'Como fazer login e sair.';
$l['d4_document'] = 'Quando você efetuar o login, você define um cookie na sua máquina para que você possa navegar nos fóruns sem ter que inserir seu nome de usuário e senha sempre. Ao sair, limpa esse cookie para garantir que ninguém mais possa navegar no fórum como você.
<br /> <br /> Para entrar, basta clicar no link de login no canto superior direito do fórum. Para sair, clique no link de logout no mesmo local. No caso de você não conseguir sair, limpar os cookies em sua máquina terá o mesmo efeito.';
$l['d5_name'] = 'Publicar um novo tópico';
$l['d5_desc'] = 'Iniciando um novo tópico em um fórum.';
$l['d5_document'] = 'Quando você vai para um fórum em que você está interessado e deseja criar um novo tópico (ou tópico), basta escolher o botão na parte superior e inferior dos fóruns, intitulado "New Thread". Por favor, tome nota que talvez você não tenha permissão para publicar um novo tópico em todos os fóruns, pois seu administrador pode restringir a publicação nesse fórum para a equipe ou arquivado completamente no fórum.';
$l['d6_name'] = 'Publicar uma resposta';
$l['d6_desc'] = 'Respondendo a um tópico dentro de um fórum.';
$l['d6_document'] = 'Durante a sua visita, você pode encontrar um tópico ao qual você gostaria de fazer uma resposta. Para fazer isso, basta clicar no botão "Nova resposta" na parte inferior ou superior do segmento. Tenha em atenção que o seu administrador pode ter uma publicação restrita para determinados indivíduos nesse fórum específico.
<br /> <br /> Além disso, um moderador de um fórum pode ter fechado um segmento, o que significa que os usuários não podem responder a ele. Não existe nenhuma maneira para um usuário abrir tal thread sem a ajuda de um moderador ou administrador.';
$l['d7_name'] = 'MyCode';
$l['d7_desc'] = 'Saiba como usar o MyCode para aprimorar suas postagens.';
$l['d7_document'] = 'You can use MyCode, a simplified version of HTML, in your posts to create certain effects.
<p><br />[b]This text is bold[/b]<br />&nbsp;&nbsp;&nbsp;<b>This text is bold</b>
<p>[i]This text is italicized[/i]<br />&nbsp;&nbsp;&nbsp;<i>This text is italicized</i>
<p>[u]This text is underlined[/u]<br />&nbsp;&nbsp;&nbsp;<u>This text is underlined</u>
<p>[s]This text is struck out[/s]<br />&nbsp;&nbsp;&nbsp;<strike>This text is struck out</strike>
<p><br />[url]http://www.example.com/[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">http://www.example.com/</a>
<p>[url=http://www.example.com/]Example.com[/url]<br />&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">Example.com</a>
<p>[email]example@example.com[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">example@example.com</a>
<p>[email=example@example.com]E-mail Me![/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">E-mail Me!</a>
<p>[email=example@example.com?subject=spam]E-mail with subject[/email]<br />&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com?subject=spam">E-mail with subject</a>
<p><br />[quote]Quoted text will be here[/quote]<br />&nbsp;&nbsp;&nbsp;<quote>Quoted text will be here</quote>
<p>[code]Text with preserved formatting[/code]<br />&nbsp;&nbsp;&nbsp;<code>Text with preserved formatting</code>
<p><br />[img]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif">
<p>[img=50x50]http://www.php.net/images/php.gif[/img]<br />&nbsp;&nbsp;&nbsp;<img src="http://www.php.net/images/php.gif" width="50" height="50">
<p><br />[color=red]This text is red[/color]<br />&nbsp;&nbsp;&nbsp;<font color="red">This text is red</font>
<p>[size=3]This text is size 3[/size]<br />&nbsp;&nbsp;&nbsp;<font size="3">This text is size 3</font>
<p>[font=Tahoma]This font is Tahoma[/font]<br />&nbsp;&nbsp;&nbsp;<font face="Tahoma">This font is Tahoma</font>
<p><br />[align=center]This is centered[/align]<div align="center">This is centered</div>
<p>[align=right]This is right-aligned[/align]<div align="right">This is right-aligned</div>
<p><br />[list]<br />[*]List Item #1<br />[*]List Item #2<br />[*]List Item #3<br />[/list]<br /><ul><li>List item #1</li><li>List item #2</li><li>List Item #3</li>
</ul>
<p>You can make an ordered list by using [list=1] for a numbered, and [list=a] for an alphabetical list.</p>';
