<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:46:46 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'Manutenção de usuário';
$l['s1_desc'] = 'Instruções básicas para manter uma conta do fórum';
$l['s2_name'] = 'Postando';
$l['s2_desc'] = 'Postando, respondendo, e uso básico do fórum.';
