<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:53:16 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = '{1} Gestão de Grupo';
$l['nav_join_requests'] = 'Pedidos de adesão';
$l['nav_group_memberships'] = 'Membros do Grupo';
$l['not_leader_of_this_group'] = 'Desculpe, mas você não é o líder deste grupo.';
$l['invalid_group'] = 'Este grupo de usuário não existe.';
$l['pending_requests'] = 'Pedidos de adesão pendentes';
$l['num_requests_pending'] = 'Existem atualmente <strong>{1}</strong> pedido de adesão pendente para este Grupo de Membros.';
$l['group_management'] = 'Gestão de Grupo';
$l['members_of'] = 'Membros em "{1}"';
$l['user_name'] = 'Nome de usuário';
$l['contact'] = 'Contato';
$l['reg_date'] = 'Registrado';
$l['post_count'] = 'Mensagens';
$l['remove_selected'] = 'Remover o usuário selecionado do Grupo';
$l['add_member'] = 'Adicionar membro a "{1}"';
$l['add_member_submit'] = 'Adicionar membro ao grupo';
$l['join_requests'] = 'Pedidos de adesão';
$l['join_requests_title'] = 'Pedido de adesão para "{1}"';
$l['leader'] = '(Líder)';
$l['reason'] = 'Motivo';
$l['accept'] = 'Aceitar';
$l['ignore'] = 'Ignorar';
$l['decline'] = 'Rejeitar';
$l['action_requests'] = 'Executar ação';
$l['join_requests_moderated'] = 'Os pedidos de adesão foram moderados.<br />Vai agora seguir para a lista de pedidos.';
$l['no_requests'] = 'Atualmente não existem pedidos de adesão para este Grupo.';
$l['user_added'] = 'O usuário foi adicionado ao Grupo de Membros.';
$l['users_removed'] = 'Os usuários selecionados foram removidos do Grupo de Membros.';
$l['group_no_members'] = 'De momento não existem membros neste grupo.<br />Para voltar à página de Gestão de grupos, clique <a href="usercp.php?action=usergroups">aqui</a>.';
$l['group_public_moderated'] = 'Este Grupo de Membros é público, onde todos podem entrar.  Todas as adesãos têm de ser moderadas por um Líder de Grupo.';
$l['group_public_not_moderated'] = 'Este Grupo de Membros é um Grupo público, onde todos podem entrar livremente.';
$l['group_private'] = 'Este Grupo de Membros é um Grupo privado. Apenas podem fazer parte deste Grupo de Membros adicionado pelo Líder.';
$l['group_default'] = 'Este Grupo de Membros é um núcleo de usuários de Grupo.';
$l['group_leaders'] = 'Líder de Grupo';
$l['no_users_selected'] = 'Desculpe, mas não foram selecionados usuários para remover.<br />Retorne e selecione os usuários que quer remover deste Grupo.';
$l['error_alreadyingroup'] = 'O usuário especificado já faz parte do Grupo de Membros.';
$l['invite_member'] = 'Convide membro para "{1}"';
$l['invite_member_submit'] = 'Convide membro para grupo';
$l['no_users'] = 'Não tem usuários nesse grupo.';
$l['group_public_invite'] = 'Este grupo de usuários é um grupo de usuários públicos que requer um convite de um líder de grupo para se juntar.';
$l['error_alreadyinvited'] = 'O usuário especificado já foi convidado.';
$l['user_invited'] = 'O usuário foi convidado a participar do grupo de usuários.';
$l['invite_pm_subject'] = 'Você foi convidado para se juntar a "{1}"';
$l['invite_pm_message'] = 'Você recebeu um convite para se juntar ao grupo de usuários "{1}".

Para participar, avance para a página [url={2}/usercp.php?action=usergroups]Grupo Membros [/url] e clique em \'Aceitar convidar\'.

Este convite não expira.';
$l['invite_pm_message_expires'] = 'Você recebeu um convite para se juntar ao grupo de usuários "{1}".

Para participar, avance para a página [url={2}/usercp.php?action=usergroups]Grupo Membros [/url] e clique em \'Aceitar convidar\'.

Este convite expirará {3} dias a partir de agora.';
