<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:54:38 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Lista de Membros';
$l['memberlist_disabled'] = 'A funcionalidade da Lista de Membros foi desativada pelo Administrador.';
$l['member_list'] = 'Lista de Membros';
$l['avatar'] = 'Avatar';
$l['username'] = 'Nome de Usuário';
$l['joined'] = 'Registradoado';
$l['lastvisit'] = 'Última Visita';
$l['posts'] = 'Mensagens Colocadas';
$l['referrals'] = 'Referência';
$l['search_members'] = 'Pesquisar na Lista de Membros';
$l['website'] = 'Página web';
$l['sort_by'] = 'Ordenar por';
$l['contains'] = 'Contém:';
$l['sort_by_username'] = 'Ordenar por: Nome de Usuário';
$l['sort_by_regdate'] = 'Ordenar por: Data de registroo';
$l['sort_by_lastvisit'] = 'Ordenar por: Última visita';
$l['sort_by_posts'] = 'Ordenar por: Mensagens Colocadas';
$l['sort_by_referrals'] = 'Ordenar por: Membros referidos';
$l['order_asc'] = 'ordem ascendente';
$l['order_desc'] = 'ordem descendente';
$l['forumteam'] = 'Mostrar Equipe do Fórum';
$l['advanced_search'] = 'Pesquisa Avançada';
$l['search_member_list'] = 'Pesquisa Lista de Membros';
$l['search_criteria'] = 'Pesquisa por critério';
$l['begins_with'] = 'Começa por';
$l['username_contains'] = 'Contém';
$l['search_website'] = 'Endereço da Página Web';
$l['search_aim'] = 'Apelido AIM';
$l['search_msn'] = 'Endereço Windows Live Messenger';
$l['search_yahoo'] = 'Apelido Yahoo';
$l['search_icq'] = 'Número ICQ';
$l['search_options'] = 'Opções de Pesquisa';
$l['per_page'] = 'Resultados por página';
$l['search'] = 'Pesquisar';
$l['error_no_members'] = '<p>Não foram encontrados membros com os critérios de pesquisa que introduziu.</p><p>Por favor insira um critério de pesquisa diferente e tente novamente.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
$l['threads'] = 'Contagem de tópicos';
$l['sort_by_threads'] = 'Ordenar por: Contagem de tópicos';
$l['asc'] = 'asc';
$l['desc'] = 'desc';
$l['nav_memberlist_search'] = 'Pesquisar';
$l['search_skype'] = 'Skype';
$l['search_google'] = 'Google Hangouts';
