<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 15:45:58 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = 'Registrar';
$l['nav_activate'] = 'Ativar';
$l['nav_resendactivation'] = 'Reenviar Email de Ativação';
$l['nav_lostpw'] = 'Recuperar senha perdida';
$l['nav_resetsenha'] = 'Reset à senha';
$l['nav_login'] = 'Entrar';
$l['nav_emailuser'] = 'Email do usuário';
$l['nav_profile'] = 'Perfil de {1}';
$l['tpp_option'] = 'Mostrar {1} tópicos por página';
$l['ppp_option'] = 'Mostrar {1} mensagens por página';
$l['account_activation'] = 'Ativação da Conta';
$l['activate_account'] = 'Ativar Conta';
$l['activation_code'] = 'Código de Ativação';
$l['email_user'] = 'Enviar {1} um Email';
$l['email_subject'] = 'Assunto do Email';
$l['email_message'] = 'Mensagem do Email';
$l['send_email'] = 'Enviar Email';
$l['error_hideemail'] = 'O destinatário escolheu esconder o seu endereço de Email e como resultado, você não lhe pode enviar o Email.';
$l['error_no_email_subject'] = 'Você tem de inserir um Assunto no Email';
$l['error_no_email_message'] = 'Você tem de inserir uma mensagem no Email';
$l['login'] = 'Login';
$l['pw_note'] = 'Por favor, tenha atenção que a senha é sensível a maiúsculas e minísculas.';
$l['lostpw_note'] = 'Perdeu a sua senha?';
$l['lost_pw'] = 'Perdeu a senha da conta';
$l['lost_pw_form'] = 'Formulário de recuperação de senha';
$l['email_address'] = 'Endereço de Email:';
$l['request_user_pass'] = 'Pedir Credenciais de Acesso';
$l['profile'] = 'Perfil de {1}';
$l['registration_date'] = 'Data de registro:';
$l['date_of_birth'] = 'Data de Aniversário:';
$l['birthdayhidden'] = 'Ocultar';
$l['birthday'] = 'Aniversário:';
$l['local_time'] = 'Hora Local:';
$l['local_time_format'] = '{1} em {2}';
$l['users_forum_info'] = 'Informações do fórum de {1}';
$l['joined'] = 'Registrado em:';
$l['lastvisit'] = 'Última Visita:';
$l['total_posts'] = 'Total de Mensagens:';
$l['ppd_percent_total'] = '{1} mensagens por dia | {2} porcento do total de mensagens';
$l['find_posts'] = 'Procurar Todas as Mensagens';
$l['find_threads'] = 'Procurar Todos os tópicos';
$l['members_referred'] = 'Referenciado pelo membro:';
$l['rating'] = 'avaliação:';
$l['users_contact_details'] = 'Dados de contato de {1}';
$l['homepage'] = 'Página:';
$l['pm'] = 'Mensagem Privada:';
$l['send_pm'] = 'Enviar uma Mensagem Privada a {1}.';
$l['icq_number'] = 'Número ICQ:';
$l['aim_screenname'] = 'AIM:';
$l['yahoo_id'] = 'ID:';
$l['msn'] = 'MSN:';
$l['avatar'] = 'Avatar:';
$l['warning_level'] = 'Nível de Avisos:';
$l['warn'] = 'Avisar';
$l['away_note'] = '{1} está de momento ausente.';
$l['away_reason'] = 'Motivo:';
$l['away_since'] = 'Ausente desde:';
$l['away_returns'] = 'Retorna em:';
$l['away_no_reason'] = 'Não especificado.';
$l['users_additional_info'] = 'Informação adicional sobre {1}';
$l['email'] = 'Email:';
$l['send_user_email'] = 'Enviar um Email a {1}.';
$l['users_signature'] = 'Assinatura de {1}';
$l['agreement'] = 'Acordo de Registro no Fórum';
$l['agreement_1'] = 'Apesar de se tentar editar ou excluir quaisquer tópicos, respostas ou mensagens contendo conteúdo falso, difamatório, abusivo, obsceno, racista, profano, ameaçador, sexista, pornográfico, discriminatório ou qualquer outro tipo de comentário que prejudique a privacidade dos outros usuários, ou ainda que viole quaisquer leis, é impossível para nós rever todo o conteúdo colocado neste fórum de discussão. Por essa razão, você concorda que todo o conteúdo colocado neste fórum de discussão reflete os pontos de vista e opiniões dos seus autores originais, assim como quem coloca o conteúdo e não os pontos de vista do fórum de discussão. Por esse motivo, nós não nos responsabilizamos e não podemos garantir a exatidão ou veracidade de qualquer conteúdo colocado neste fórum de discussão.';
$l['agreement_2'] = 'Ao se registrar neste Fórum, você concorda em não colocar conteúdo falso, difamatório, abusivo, obsceno, racista, profano, ameaçador, sexista, pornográfico, discriminatório ou qualquer outro tipo de comentário que prejudique a privacidade dos outros usuários, ou ainda que viole quaisquer leis.';
$l['agreement_3'] = 'Caso não cumpra as regras do fórum, você poderá sofrer sanções no fórum, podendo até mesmo resultar no término da sua conta de usuário, suspensão, ou expulsão permanente, ficando assim impossibilitado de aceder a este fórum. O seu endereço IP é ligado a cada tópico ou mensagem que você criar neste fórum de discussão e pode ser recuperado pela equipa do fórum, caso seja necessário. Você concorda em que a equipa do fórum tem direito a excluir, editar ou bloquear qualquer conta de usuário ou conteúdo em qualquer altura, caso seja necessário. Você concorda que qualquer informação sua enviada para este fórum de discussão seja armazenada numa base de dados, e que os "cookies" sejam salvaguardados no seu computador a fim de guardar as suas informações de login no fórum.';
$l['agreement_4'] = 'Qualquer informação que você forneça neste fórum não será facultada a terceiros sem o seu consentimento. No entanto você concorda que a equipa do fórum não pode ser considerada responsável por quaisquer tentativas de acesso não autorizado, nas quais seus dados pessoais venham a ser comprometidos.';
$l['agreement_5'] = 'Ao prosseguir com o processo de registro você concorda com todos os termos e com outros que a administração do Fórum especifique à posteriori.';
$l['registration'] = 'Registro';
$l['required_fields'] = 'Campos Obrigatórios';
$l['complex_password'] = '<acronym title="A senha tem de ter pelo menos {1} caracteres e ser composta com letras e números com maiúsculas e minúsculas.">Complex</acronym> senha:';
$l['confirm_email'] = 'Confirmar Email:';
$l['optional_fields'] = 'Campos Opcionais';
$l['website_url'] = 'Endereço do seu Site:';
$l['birthdate'] = 'Aniversário:';
$l['additional_info'] = 'Informação Adicional';
$l['i_agree'] = 'Eu Aceito';
$l['account_details'] = 'Detalhes da Conta';
$l['account_prefs'] = 'Preferências da Conta:';
$l['invisible_mode'] = 'Esconder o meu estado da lista Quem está Online.';
$l['allow_notices'] = 'Receber Emails dos Administradores.';
$l['hide_email'] = 'Esconder o seu Email dos outros membros.';
$l['email_notify'] = 'Subscrever-me automaticamente em tópicos que coloco mensagens.';
$l['receive_pms'] = 'Receber mensagens privadas dos outros usuários.';
$l['pm_notice'] = 'Alertar-me com uma notificações quando receber uma mensagem Privada.';
$l['email_notify_newpm'] = 'Enviar-me um email sempre que receber uma mensagem privada nova.';
$l['time_offset'] = 'Fuso Horário:';
$l['time_offset_desc'] = 'Se reside numa zona que utiliza um Fuso Horário diferente do atual, poderá alterar o mesmo aqui.';
$l['dst_correction'] = 'Salvar correção de Horário de Verão:';
$l['dst_correction_auto'] = 'Detectar automaticamente Horário de Verão';
$l['dst_correction_enabled'] = 'Usar sempre a correcção Horário de Verão';
$l['dst_correction_disabled'] = 'Nunca usar a correcção Horário de Verão';
$l['redirect_registered_coppa_activate'] = 'Obrigado por se registrar no {1}, {2}. A sua conta foi criada com sucesso, no entanto como o dono desta conta tem menos de 13 Anos, é necessária a permissão Paternal, antes da conta de usuário ser utilizada.<br /><br />Um parente ou tutor legal, vai ter que fazer o download, preencher e enviar-nos uma cópia completa do nosso <a href="member.php?action=coppa_form">Formulário de Autorização de conformidade COPPA</a>.<br /><br />Assim que se receba uma cópia completa deste formulário, a conta é ativada.';
$l['coppa_compliance'] = 'Conformidade COPPA';
$l['coppa_desc'] = 'Por norma, para se registrar nestes fóruns, é requerido que você verifique a sua idade, para obedecer com <a href="http://coppa.org/" title="Protecção Online da Privacidade das crianças" target="_blank">COPPA</a>. Por favor, introduza a sua data de Nascimento.<br /><br />Se é menor de 13 Anos, tem de obter Permissão Parental, para fazer o registro. Um parente ou tutor legal, vai ter que fazer o download, preencher e enviar-nos uma cópia completa do nosso <a href="member.php?action=coppa_form" target="_blank">COPPA Formulário de Autorização de conformidade COPPA</a>.';
$l['hide_dob'] = 'Você pode escolher esconder a sua data de Nascimento e idade, editando o seu perfil depois de se registrar.';
$l['continue_registration'] = 'Continuar com o Registro';
$l['birthdayprivacy'] = 'Privacidade da Data de Nascimento:';
$l['birthdayprivacyall'] = 'Mostrar Idade e Data de Nascimento';
$l['birthdayprivacynone'] = 'Esconder Idade e Data de Nascimento';
$l['birthdayprivacyage'] = 'Mostrar apenas a Idade';
$l['leave_this_field_empty'] = 'Deixe este campo vazio:';
$l['error_need_to_be_thirteen'] = 'Você tem de ter trinta anos ou mais, para se registrar neste fórum.';
$l['coppa_registration'] = 'Formulário de registro COPPA';
$l['coppa_form_instructions'] = 'Por favor, imprima este formulário, preencha e envie-nos para o endereço de email mencionado.';
$l['fax_number'] = 'Número de Fax:';
$l['mailing_address'] = 'Endereço de Email:';
$l['account_information'] = 'Informação da Conta';
$l['parent_details'] = 'Detalhes Parente / Tutor';
$l['full_name'] = 'Nome Completo:';
$l['relation'] = 'Relação:';
$l['phone_no'] = 'Telefone #:';
$l['coppa_parent_agreement'] = 'Eu compreendo que essa informação é verdadeira, que qualquer informação pode ser alterada no futuro, introduzindo a respectiva senha e que este usuário pode ser removido, pedido.';
$l['coppa_agreement_1'] = 'usuários menores que 13 anos, têm de ter permissão do parente, ou tutor legal, para se registrar em {1}.';
$l['coppa_agreement_2'] = 'Um parente ou tutor legal, vai ter que fazer o download, preencher e enviar-nos uma cópia completa do nosso <a href="member.php?action=coppa_form" target="_blank">Formulário de Autorização de conformidade COPPA</a> antes do Membro do grupo ter acesso.';
$l['coppa_agreement_3'] = 'Se você desejar, pode iniciar o processo do registro agora, no entanto; a conta vai estar inacessível, até que o seguinte formulário de conformidade seja recebido.';
$l['error_awaitingcoppa'] = 'Não se pode ligar, usando esta conta, devido a estar a aguardar o formulário de validação COPPA, por um parente ou tutor.<br /><br />Um parente ou tutor legal, vai ter que fazer o download, preencher e enviar-nos uma cópia completa do nosso <a href="member.php?action=coppa_form">Formulário de Autorização de conformidade COPPA</a>.<br /><br />Assim que se receba uma cópia completa deste formulário, a conta será activada.';
$l['lang_select'] = 'Configuração do idioma:';
$l['lang_select_desc'] = 'Se vive num País onde o idioma é diferente do idioma padrão do fórum, pode selecionar outro pré instalado no fórum.';
$l['lang_select_default'] = 'Usar Padrão';
$l['submit_registration'] = 'Enviar Registro!';
$l['confirm_password'] = 'Confirmar senha:';
$l['referrer'] = 'Referência:';
$l['referrer_desc'] = 'Se você foi referido para este fórum, por outro membro, pode introduzir o nome dele no campo. Se não, simplesmente deixe o campo em branco.';
$l['resend_activation'] = 'Reenviar Ativação da conta';
$l['request_activation'] = 'Pedir Ativação da Conta';
$l['ppp'] = 'Mensagens por Página:';
$l['ppp_desc'] = 'Permite-lhe selecionar um número de mensagens, para mostrar por página num tópico.';
$l['tpp'] = 'Tópicos por Página:';
$l['tpp_desc'] = 'Permite-lhe selecionar um número de tópicos, para mostrar por página numa Lista de tópicos.';
$l['reset_password'] = 'Reset senha';
$l['send_password'] = 'Enviar nova senha!';
$l['image_verification'] = 'Verificação de Imagem';
$l['verification_note'] = 'Por favor introduza o texto que aparece na imagem. Este processo é usado para prevenir registros automáticos.';
$l['verification_subnote'] = '(Não é sensível a Maiúsculas)';
$l['registration_errors'] = 'Ocorreram os seguintes erros com o seu registro';
$l['timeonline'] = 'Tempo Online:';
$l['registrations_disabled'] = 'Desculpe, mas não se pode registrar neste momento porque o Administrador suspendeu novos registros de contas.';
$l['error_username_length'] = 'O seu nome de usuário é inválido. Nomes de usuário devem de ter entre {1} e {2} caracteres.';
$l['none_registered'] = 'Sem Registros';
$l['not_specified'] = 'Não especificado';
$l['membdayage'] = '({1} Anos de idade)';
$l['mod_options'] = 'Opções de Moderador';
$l['edit_in_mcp'] = 'Editar este usuário no CP';
$l['ban_in_mcp'] = 'Expulsar este usuário no CP';
$l['edit_usernotes'] = 'Editar notas de usuário no CP';
$l['no_usernotes'] = 'Não existem de momento notas neste usuário';
$l['reputation'] = 'Reputação:';
$l['reputation_vote'] = 'Avaliação';
$l['reputation_details'] = 'Detalhes';
$l['already_logged_in'] = 'Atenção: Você já se encontra Ligado com {1}.';
$l['admin_edit_in_acp'] = 'Editar este usuário no Admin CP';
$l['admin_ban_in_acp'] = 'Expulsar este usuário no Admin CP';
$l['admin_options'] = 'Opções de Administrador';
$l['redirect_registered_activation'] = 'Obrigado por se registrar em {1}, {2}.<p>Para completar o seu registro, por favor verifique a sua conta de email e siga as instruções para Ativação da conta. Enquanto não Ativar a sua conta, não vai conseguir colocar mensagens no Fórum';
$l['redirect_emailupdated'] = 'O seu email foi alterado com sucesso.<br />Vai agora retornar à Página principal.';
$l['redirect_accountactivated'] = 'A sua conta foi ativada com sucesso.<br />Vai agora retornar à Página principal.';
$l['redirect_registered'] = 'Obrigado por se registrar no {1}, {2}.<br />Vai agora retornar à Página principal.';
$l['redirect_registered_admin_activate'] = 'Obrigado por se registrar no {1}, {2}.<br />O seu registro tem de ser ativado por um Administrador. Enquanto isso, não vai poder colocar mensagens no fórum.';
$l['redirect_loggedout'] = 'Acabou de se desconectar do Fórum.<br />Vai agora retornar para a página principal.';
$l['redirect_alreadyloggedout'] = 'Você já se desconectou, ou então não se conectou ainda.<br />Vai agora retornar para a página principal.';
$l['redirect_lostpwsent'] = 'Obrigado, todas as contas pertencentes a esse endereço de email, serão enviadas informações e detalhes de como efetuar reset às senhas.';
$l['redirect_activationresent'] = 'A sua Ativação de email foi reenviada.';
$l['redirect_passwordreset'] = 'Obrigado, foi feito o reset à senha da sua conta. Foi gerada uma nova senha, que foi enviada para a sua conta de correio eletronico.';
$l['redirect_memberrated'] = 'O Membro foi avaliado com sucesso.';
$l['redirect_registered_senhasent'] = 'Uma nova senha foi gerada, e foi enviada para a sua conta de correio eletronico. Antes de fazer o login no fórum, vai ter que verificar o no seu email pela senha.';
$l['redirect_validated'] = 'Obrigado, a sua conta foi validada.<br />Vai agora retornar ao fórum.';
$l['error_activated_by_admin'] = 'Você não consegue reenviar o seu email de Ativação de conta, porque todos os registros têm de ser aprovados por um Administrador.';
$l['error_alreadyregistered'] = 'Desculpe, mas o nosso sistema detetou que você já se encontra registrado neste Fórum, e o registro de contas múltiplas foi desativado.';
$l['error_alreadyregisteredtime'] = 'Não conseguimos processar o seu registro, porque já foi feito {1} novo registro(s) do seu endereço IP, passados {2} horas. Por favor, tente novamente masi tarde.';
$l['error_badlostpwcode'] = 'Parece que o código de reset à senha é inválido. Por favor releia o email que enviou ou então contate um Administrador para mais ajuda.';
$l['error_badactivationcode'] = 'Você introduziu um código de Ativação de conta inválido. Para reenviar todos os emails de Ativação, para o endereço de email, por favor clique <a href="member.php?action=resendactivation">Aqui</a>.';
$l['error_alreadyactivated'] = 'Parece que a sua conta já se encontra ativada, ou não requer o processo de verificação de email.';
$l['error_nothreadurl'] = 'A sua mensagem não contém o URL do tópico. Por favor, use o "Enviar a um Amigo" se assim o desejar.';
$l['error_bannedusername'] = 'Você introduziu um nome de usuário que se encontra banido dos registros. Por favor escolha outro nome de usuário.';
$l['error_notloggedout'] = 'o Seu ID de usuário não pode ser verificado para poder sair. Isto poderá ser devido a um código Javascript malicioso, que está a tentar sair automaticamente. Se você quer sair, por favor clique em Sair no topo do Fórum, ou então limpe os Cokies do Fórum.';
$l['error_regimageinvalid'] = 'O código de verificação de imagem que introduziu está incorreto. Por favor introduza o código exatamente como aparece na imagem.';
$l['error_regimagerequired'] = 'Por favor complete a verificação de imagem para continuar o processo de Login. Por favor insira o código exatamente como aparece na imagem.';
$l['error_spam_deny'] = ' O nosso sistema detetou que você pode ser um spammer e, por isso, foi-lhe negado o registro. Se você acha que é um erro, por favor contate o Administrador.';
$l['js_validator_no_username'] = 'Tem de inserir um nome de usuário';
$l['js_validator_invalid_email'] = 'Tem de inserir um endereço de email válido';
$l['js_validator_email_match'] = 'Tem de inserir o mesmo endereço de email novamente';
$l['js_validator_no_image_text'] = 'Tem de inserir o texto da imagem';
$l['js_validator_password_matches'] = 'As senhas que introduziu têm de coincidir';
$l['js_validator_password_complexity'] = 'As senhas têm de conter um ou mais símbolos';
$l['js_validator_password_length'] = 'A sua senha tem de ter {1} ou mais caracteres de comprimento';
$l['js_validator_not_empty'] = 'Você tem de selecionar ou introduzir um valor para este campo';
$l['js_validator_checking_username'] = 'Verificar se o nome de usuário está disponível';
$l['js_validator_username_length'] = 'Nomes de usuário têm de ter entre {1} ou {2} caracteres de comprimento';
$l['js_validator_checking_referrer'] = 'Verificando se existe alguma referência do nome de usuário.';
$l['js_validator_captcha_valid'] = 'Verificando se introduziu ou não o código de verificação de imagem correto.';
$l['subscription_method'] = 'Modo Padrão de Subscrição de Tópico:';
$l['no_auto_subscribe'] = 'Não Subscrever';
$l['no_email_subscribe'] = 'Sem notificação de email';
$l['instant_email_subscribe'] = 'Notificação de email';
$l['remove_from_buddy_list'] = 'Remover da Lista de Amigos';
$l['add_to_buddy_list'] = 'Adicionar à Lista de Amigos';
$l['remove_from_ignore_list'] = 'Remover da Lista de Ignorados';
$l['add_to_ignore_list'] = 'Adicionar à Lista de Ignorados';
$l['nav_resetpassword'] = 'Resetar senha';
$l['total_threads'] = 'Total de tópicos:';
$l['tpd_percent_total'] = '{1} tópicos por dia | {2}% de todos os tópicos.';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Hangouts ID:';
$l['ban_note'] = 'Essa conta está atualmente banida.';
$l['ban_by'] = 'Banida por';
$l['ban_length'] = 'Duração do banimento';
$l['ban_remaining'] = 'restando';
$l['required_info'] = 'Informação obrigatória';
$l['signature'] = 'Assinatura:';
$l['error_invalid_birthday'] = 'A data de nascimento que você inseriu é inválida. Por favor insira uma válida.';
$l['timeonline_hidden'] = '(Invisível)';
$l['error_stop_forum_spam_spammer'] = 'Desculpe, seu {1} corresponde ao de um spammer conhecido. Se você acha que isso é um erro, entre em contato com um administrador.';
$l['error_stop_forum_spam_fetching'] = 'Desculpe, algo deu errado ao verificar sua conta em um banco de dados de spammers. Provavelmente o banco de dados não pôde ser acessado. Por favor, tente novamente mais tarde.';
$l['purgespammer'] = 'Purgar Spammer';
$l['view_all_notes'] = 'Ver todas as notas';
$l['view_notes_for'] = 'Ver notas de {1}';
$l['registration_ip'] = 'IP de registro:';
$l['last_known_ip'] = 'Último IP conhecido:';
$l['redirect_accountactivated_admin'] = 'Seu e-mail foi validado com sucesso.<br /> Seu registro deve ser ativado por um administrador. Até então, talvez você não possa publicar nesses fóruns.<br /> Agora você será levado de volta à página principal.';
$l['redirect_registered_passwordsent'] = 'Foi gerada uma senha aleatória e enviada para o seu endereço de e-mail. Antes de poder fazer login nesse fórum, você precisará verificar seu e-mail para esta senha.';
$l['error_alreadyvalidated'] = 'Seu e-mail já foi validado.';
$l['error_spam_deny_time'] = 'Nossos sistemas detectam que você pode ser um spammer e, portanto, você foi negado o registro. O registro deve levar um mínimo de {1} segundos para evitar inscrições automáticas, você se registrou em {2} segundos. Se você acha que isso é um erro, entre em contato com o Administrador.';
$l['js_validator_no_security_question'] = 'Você precisa inserir a resposta para a pergunta acima';
$l['security_question'] = 'Pergunta de Segurança';
$l['question_note'] = 'Por favor, responda a pergunta fornecida. Esse processo é usado para evitar processos automatizados.';
$l['error_question_wrong'] = 'A resposta que você forneceu para a questão de segurança é errada. Por favor, tente novamente.';
$l['no_subscribe'] = 'Sem notificações';
$l['instant_pm_subscribe'] = 'Mensagem instantânea de MP';
$l['report_user'] = 'Reportar usuário';
$l['newregistration_subject'] = 'Novo registro em {1}';
$l['newregistration_message'] = '{1},

Há um novo usuário {2} que está com ativação pendente.

Username: {3}

Obrigado,
{2} Staff';
