<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:33:07 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = 'Clique aqui se não pretende esperar mais.';
$l['redirect_return_forum'] = '<br /><br />Em alternativa, <a href="{1}">Volte ao início de Fórum</a>.';
$l['redirect_emailsent'] = 'A sua Mensagem de Email foi enviada com sucesso.';
$l['redirect_loggedin'] = 'Você efetuou o login com sucesso.<br />Será redirecionado para onde estava.';
$l['error_invalidpworusername'] = 'Você inseriu um nome de usuário ou senha errada. <br /><br />Se esqueceu da senha, por favor <a href="member.php?action=lostpw">peça uma nova</a>.';
$l['error_invalidpworusername1'] = ' Você inseriu um Email ou senha errada. <br /><br />Se esqueceu da senha, por favor <a href="member.php?action=lostpw">peça uma nova</a>.';
$l['error_invalidpworusername2'] = 'Você inseriu uma combinação de Nome de usuário e senha ou um Email e senha errada . <br /><br />Se esqueceu da senha, por favor <a href="member.php?action=lostpw">peça uma nova</a>.';
$l['error_incompletefields'] = 'Aparentemente deixou um ou mais campos obrigatórios em branco. Retroceda e preencha todos os campos obrigatórios.';
$l['error_alreadyuploaded'] = 'Esta mensagem já contém um anexo com o mesmo nome. Por favor altere o nome e insira novamente. Em alternativa pode clicar em "Actualizar Anexo".';
$l['error_alreadyuploaded_perm'] = 'Esta mensagem já contém um anexo com o mesmo nome. Por favor, remova o arquivo existente ou renomeie o arquivo e envie-o novamente.';
$l['error_nomessage'] = 'Desculpe, não é possível continuar porque você não inseriu uma mensagem válida. Por favor volte atrás e tente novamente.';
$l['error_invalidemail'] = 'Você não inseriu um endereço de Email válido.';
$l['error_nomember'] = 'O membro que especificou é inválido ou então não existe.';
$l['error_maxposts'] = 'Desculpe, mas excedeu o limite diário para postar mensagens.  Por favor, espere até amanhã para postar novas ou então contacte um Administrador.<br /><br />A postagem máxima diária de mensagens permitida que pode postar num dia é de {1}';
$l['error_nohostname'] = 'Não é possível encontrar o nome do Servidor para o IP colocado.';
$l['error_invalidthread'] = 'O tópico especificado não existe.';
$l['error_invalidpost'] = 'A mensagem especificada não existe.';
$l['error_invalidannouncement'] = 'O anúncio especificado não existe.';
$l['error_invalidattachment'] = 'O anexo especificado não existe.';
$l['error_invalidforum'] = 'Fórum inválido';
$l['error_closedinvalidforum'] = 'Não pode postar mensagens neste fórum, devido ao mesmo se encontrar encerrado ou por se tratar de uma categoria.';
$l['error_attachtype'] = 'O tipo de arquivo que está a tentar anexar não é permitido. Remova o anexo e selecione outro.';
$l['error_attachsize'] = 'O arquivo que anexou é demasiado grande. O tamanho máximo permitido é de {1} kilobytes.';
$l['error_uploadsize'] = 'O arquivo enviado excede o limite permitido.';
$l['error_uploadfailed'] = 'Envio de anexo falhou. Escolha um formato de arquivo válido e tente novamente. ';
$l['error_uploadfailed_detail'] = 'Detalhes: ';
$l['error_uploadfailed_php1'] = 'PHP: O arquivo enviado excede o valor especificado na variavel upload_max_filesize do arquivo de configuração php.ini. Contate o administrador do fórum para resolução desta questão.';
$l['error_uploadfailed_php2'] = 'O arquivo enviado excede o valor máximo permitido.';
$l['error_uploadfailed_php3'] = 'O arquivo foi apenas enviado parcialmente.';
$l['error_uploadfailed_php4'] = 'Não foi enviado qualquer arquivo.';
$l['error_uploadfailed_php6'] = 'PHP: Diretório temporário em falta. Contacte o Administrador do fórum e reporte este erro.';
$l['error_uploadfailed_php7'] = 'PHP: Erro ao escrever arquivo para o disco. Contacte o Administrador do fórum com este erro.';
$l['error_uploadfailed_phpx'] = 'Erro de PHP: {1}. Contacte o Administrador do fórum e reporte este erro.';
$l['error_uploadfailed_nothingtomove'] = 'Foi especificado um arquivo inválido.';
$l['error_uploadfailed_movefailed'] = 'Ocorreu um erro ao mover o arquivo enviado para o diretório de destino.';
$l['error_uploadfailed_lost'] = 'Não foi possível encontrar o anexo no servidor.';
$l['error_emailmismatch'] = 'Os endereços de email que inseriu não correspondem. Retroceda e tente novamente.';
$l['error_nosenha'] = 'Não inseriu uma senha válida.';
$l['error_usernametaken'] = 'O nome de usuário que escolheu já se encontra em utilização. Se você já se encontra registrado no fórum, por favor faça <a href="member.php?action=login">login</a>.';
$l['error_nousername'] = 'Não inseriu qualquer nome de usuário.';
$l['error_invalidusername'] = 'O Nome de usuário inserido não é válido.';
$l['error_invalidsenha'] = 'A senha inserida não está correta. Se esqueceu a sua senha, clique <a href="member.php?action=lostpw">aqui</a>. Caso contrário volte atrás e tente novamente.';
$l['error_postflooding'] = 'Pedimos desculpa, mas não é possível processar a sua mensagem. O Administrador especificou que apenas pode postar novas mensagens a cada {1} segundos.';
$l['error_nopermission_guest_1'] = 'Não se encontra autenticado ou não tem permissão para acessar esta página. Podendo ser pelos seguintes motivos:';
$l['error_nopermission_guest_2'] = 'Não se encontra autenticado ou registrado. Utilize os campos no final desta página para se autenticar.';
$l['error_nopermission_guest_3'] = 'Não tem permissão para acessar  esta página. Está tentando acessas páginas de Administração ou a algum recurso? Verifique as regras do Fórum, para ver se está autorizado a realizar essa ação.';
$l['error_nopermission_guest_4'] = 'A sua conta poderá ter sido desativada por um administrador, ou ainda se encontra em processo de activação.';
$l['error_nopermission_guest_5'] = 'Você acessou esta página diretamente, em vez de usar a formas adequada ou links.';
$l['login'] = 'Login';
$l['need_reg'] = 'Precisa de se registar?';
$l['forgot_senha'] = 'Esqueceu-se da senha?';
$l['error_nopermission_user_1'] = 'Não tem permissão para acessar esta página. Poderá ser devido a uma das seguintes razões:';
$l['error_nopermission_user_ajax'] = 'Não tem permissão para acessar  esta página..';
$l['error_nopermission_user_2'] = 'A sua conta de usuário foi suspensa ou banida do acesso a este recurso.';
$l['error_nopermission_user_3'] = 'Não tem permissão para acessar esta página. Possivelmente está tentando utilizar um recurso o qual não tem permissão para tal.';
$l['error_nopermission_user_4'] = 'A sua conta ainda está aguardadndo validação/activação.';
$l['error_nopermission_user_5'] = 'Você acessou aesta página directamente, em vez de usar a formas adequada ou links.';
$l['error_nopermission_user_resendactivation'] = 'Reenviar Código de Activação';
$l['error_nopermission_user_username'] = 'Atualmente encontra-se ligado com o Nome de usuário: \'{1}\'';
$l['logged_in_user'] = 'usuário Ligado';
$l['error_too_many_images'] = 'Muitas Imagens.';
$l['error_too_many_images2'] = 'Não é possível processar a sua mensagem uma vez que a mesma contem muitas imagens. Remova algumas imagens da mensagem e tente novamente.';
$l['error_too_many_images3'] = '<b>Nota:</b> O numero máximo de imagens por mensagem é de';
$l['error_attach_file'] = 'Erro ao anexar arquivo';
$l['please_correct_errors'] = 'Corrija os seguintes erros antes de continuar:';
$l['error_reachedattachquota'] = 'Não é possível anexar este arquivo uma vez que atingiu a sua quota limite de {1}';
$l['error_invaliduser'] = 'O usuário especificado é inválido ou não existe.';
$l['error_invalidaction'] = 'Ação inválida';
$l['error_messagelength'] = 'Desculpe, a sua mensagem é muito longa e não pode ser postada. Por favor reduza o tamanho da sua mensagem e tente novamente.';
$l['error_message_too_short'] = 'A sua mensagem é muito curta e não pôde ser postada.';
$l['failed_login_wait'] = 'Esgotou o número máximo de tentativas permitidas para se autenticar. Deverá aguardar {1}h {2}m {3}s antes de tentar novamente.';
$l['failed_login_again'] = '<br />Ainda tem <strong>{1}</strong> tentativas para se autenticar.';
$l['error_max_emails_day'] = 'Não pode usar \'enviar tópico a um amigo\', ou um \'email a um usuário\', porque você já usou a sua quota de espaço para enviar {1} mensagens nas últimas 24 horas.';
$l['emailsubject_lostpw'] = 'Alterar senha  no {1}';
$l['emailsubject_senhareset'] = 'Nova senha no {1}';
$l['emailsubject_subscription'] = 'nova Resposta a {1}';
$l['emailsubject_randomsenha'] = 'A sua senha para {1}';
$l['emailsubject_activateaccount'] = 'Ativação da Conta no {1}';
$l['emailsubject_forumsubscription'] = 'Novo Tópico em {1}';
$l['emailsubject_reportpost'] = 'Mensagem Reportada no {1}';
$l['emailsubject_reachedpmquota'] = 'Espaço de Mensagens Privadas Atingido em {1}';
$l['emailsubject_changeemail'] = 'Alteração de Email em {1}';
$l['emailsubject_newpm'] = 'Nova Mensagem Privada em {1} - {2}';
$l['emailsubject_sendtofriend'] = 'Página Web interessante em {1}';
$l['emailbit_viewthread'] = '... (visitar o tópico para ler o restante..)';
$l['email_lostpw'] = '{1},

Para completar o processo de redefinição de senha da sua conta no {2}, deverá visitar o seguinte endereço.

{3}/member.php?action=resetsenha&uid={4}&code={5}

Em caso do link acima não funcionar vá para:

{3}/member.php?action=resetsenha

Utilize os seguintes dados:
usuário: {1}
Código de Ativação: {5}

Obrigado,
A Equipe {2}';
$l['email_lostpw1'] = '{1},

Para completar a fase de reset à senha da sua conta em {2}, você terá que seguir a URL abaixo no seu navegador web.

{3}/member.php?action=resetsenha&uid={4}&code={5}

Se o link acima não funcionar correctamente, siga para

{3}/member.php?action=resetsenha

Você vai necessitar de introduzir o seguinte:
O seu endereço de Email
Código de Ativação: {5}

Obrigdo,
A Equipe {2}';
$l['email_lostpw2'] = '{1},

Para completar a fase de reset à senha da sua conta em {2}, você terá que seguir a URL abaixo no seu navegador.

{3}/member.php?action=resetsenha&uid={4}&code={5}

Se o link acima não funcionar corretamente, siga para

{3}/member.php?action=resetsenha

Você vai necessitar de introduzir o seguinte:
Nome de usuário: {1} (Ou o seu endereço de Email)
Código de Ativação: {5}

Obrigado,
A Equipe {2}';
$l['email_reportpost'] = '{1} de {2} reportou esta mensagem:

{3}
{4}/{5}

O motivo que este usuário deu para reportar desta mensagem foi:
{7}

Esta mensagem foi enviada a todos os moderadores deste fórum, ou todos os Administradores e Super Moderadores caso não existam moderadores.

Por favor, verifique esta mensagem assim que possível.';
$l['email_senhareset'] = '{1},

A sua senha no {2} foi alterada.

A sua nova senha é: {3}

Vai necessitar desta senha para se autenticar no fórum, uma vez ligado deverá alterar a mesma no seu Painel de Controle (CP).

Obrigado,
A Equipe {2}';
$l['email_randomsenha'] = '{1},

Obrigado pelo seu registro no {2}. Em baixo encontra-se o seu nome de usuário e a senha gerada aleatoriamente. Para se autenticar no {2}, você vai necessitar desses dados.

Nome de usuário: {3}
senha: {4}

Recomendamos que altere a sua senha de imediato depois de se ligar ao Fórum. Poderá efectuar essa alteração através do seu Painel de Controlo (CP) clicando em Alterar senha no Menu à esquerda.

Obrigado,
A Equipe {2}';
$l['email_randomsenha1'] = '{1},

Obrigado por se registrar em {2}. Abaixo está o seu nome de usuário e a senha gerada aleatoriamente. Para fazer login {2}, você irá precisar destes detalhes.

O seu endereço de Email
senha: {4}

Recomendamos que você mude a sua senha imediatamente após efetuar login. Você pode fazer isso no seu Painel de usuário e e seguida, clique em Alterar senha no menu à esquerda.

Obrigado,
A Equipe {2}';
$l['email_randomsenha2'] = '{1},

Obrigado por se registrar em {2}. Abaixo está o seu nome de usuário e a senha gerada aleatoriamente. Para fazer login {2}, você irá precisar destes detalhes.

Nome de usuário: {3} (Ou o seu endereço de Email)
senha: {4}

Recomendamos que você mude a sua senha imediatamente após efetuar login. Você pode fazer isso no seu CP de usuário e em seguida, clique em Alterar senha no menu à esquerda.

Obrigado,
A Equipe {2}';
$l['email_sendtofriend'] = 'Olá,

{1} de {2} talvez esteja interessado em ler este tópico no fórum:

{3}

{1} Incluída a Seguinte Mensagem:
------------------------------------------
{4}
------------------------------------------

Obrigado,
A Equipe {2}
';
$l['email_forumsubscription'] = '{1},

{2} iniciou um novo tópico em  {3}. Este é um fórum que subscreveu em {4}.

Nome do tópico {5}

Aqui está um resumo da mensagem:
--
{6}
--

Para ver o tópico siga o seguinte endereço:
{7}/{8}

Poderão existir mais tópicos ou respostas a este fórum mas não receberá mais notificações enquanto não visitar o fórum novamente.

Obrigado,
A Equipe {4}

------------------------------------------
Cancelar Subscrição:

Caso não pretenda receber mais notificações de novos tópicos neste fórum, visite o seguinte endereço:
{7}/usercp2.php?action=removesubscription&type=forum&fid={9}&my_post_key={10}

------------------------------------------';
$l['email_activateaccount'] = '{1},

Para completar o seu registro no {2}, deverá visitar o seguinte endereço abaixo.

{3}/member.php?action=activate&uid={4}&code={5}

Se o endereço acima não funcionar corretamente vá a:

{3}/member.php?action=activate

Deverá introduzir os seguintes dados:
Nome de usuário: {1}
Código de Ativação: {5}

Obrigado,
A Equipe {2}';
$l['email_activateaccount1'] = '{1},

Para completar o processo de registro em {2}, vai ter que seguir a URL abaixo no seu navegador.

{3}/member.php?action=activate&uid={4}&code={5}

Se o link acima não funcionar corretamente, vá para

{3}/member.php?action=activate

Vai ter que digitar o seguinte:
O seu endereço de Email
Código de Ativação: {5}

Obrigado,
A Equipe {2}';
$l['email_activateaccount2'] = '{1},

Para completar o processo de registro em {2}, vai ter que seguir a URL abaixo no seu navegador.

{3}/member.php?action=activate&uid={4}&code={5}

Se o link acima não funcionar corretamente, vá para

{3}/member.php?action=activate

Vai ter que digitar o seguinte:
Nome de usuário: {1} (Ou o seu endereço de Email)
Código de Ativação: {5}

Obrigado,
A Equipe {2}';
$l['email_subscription'] = '{1},

{2} acabou de responder a um tópico no qual você se inscreveu em {3}. Este tópico é intitulado {4}.

Aqui está um trecho da mensagem:
------------------------------------------
{5}
------------------------------------------

Para visualizar o tópico, você pode acessar o seguinte URL:
{6}/{7}

Também pode haver outras respostas para este tópico, mas você não receberá mais notificações até que você visite o quadro novamente.

Obrigado,
{3} Staff

------------------------------------------
Informações de cancelamento de inscrição:

Se você não quiser receber mais notificações de respostas a esse tópico, visite o seguinte URL em seu navegador:
{6}/usercp2.php?action=removesubscription&tid={8}&my_post_key={9}';
$l['email_reachedpmquota'] = '{1},

Esta é uma mensagem automática enviada por {2} para o avisar que a sua caixa de Mensagens Privadas atingiu o seu limite.

Um ou mais usuários podem ter tentado enviar-lhe uma Mensagem Privada, a qual não foi entregue com sucesso devido a esta situação.

Por favor, apague algumas das suas Mensagens Privadas de forma a libertar algum espaço, deverá também apagar as mensagens da Rreciclagem\'.

Obrigado,
A equipe {2}
{3}';
$l['email_changeemail'] = '{1},

Recebemos um pedido de alteração de Email da conta em {2}. Veja os detalhes em baixo.

Endereço de Email Antigo: {3}
Endereço de Email Novo: {4}

Se as alterações estão corretas, por favor complete o seguinte processo de validação em {2} seguindo o seguinte endereço.

{5}/member.php?action=activate&uid={8}&code={6}

Se o link acima não funcionar corretamente visite

{5}/member.php?action=activate

Necessita de inserir os seguintes dados:
Nome de usuário: {7}
Código de Ativação: {6}

Se decidir de não efetuar a validação do seu novo endereço de Email, o seu perfil não irá sofrer alterações e continuará a usar o endereço anterior.

Obrigado,
A Equipe {2}
{5}';
$l['email_newpm'] = '{1},

Você recebeu uma nova mensagem privada em {3} a partir de {2}:

------------------------------------------
{5}
------------------------------------------

Para visualizar, responder ou encaminhar esta mensagem, você pode seguir este link:

{4} /private.php

Observe que você não receberá mais notificações de novas mensagens até você visitar {3}.

Você pode desativar novas notificações de mensagens na página de opções da sua conta:

{4} /usercp.php?action=options

Obrigado,
{3} Staff
{4}';
$l['email_emailuser'] = '{1},

{2} de {3} enviou-lhe a seguinte mensagem:
------------------------------------------
{5}
------------------------------------------

Obrigado,
A Equipe {3}
{4}

------------------------------------------
Não quer receber mensagens de Email de outros membros?

Se não quer que outros membros sejam capazes de lhe enviar Emails, visite o seu Painel de Controlo (CP) e active a opção \'Esconder o seu Email dos outros usuárioes\':
{4}/usercp.php?action=options

------------------------------------------';
$l['error_uploadempty'] = 'O arquivo especificado está vazio.';
$l['error_nopassword'] = 'Você não inseriu uma senha válida.';
$l['error_invalidpassword'] = 'A senha que você digitou está incorreta. Se você esqueceu sua senha, clique em <a href="member.php?action=lostpw">aqui </a>. Caso contrário, volte e tente novamente.';
$l['forgot_password'] = 'Esqueceu sua senha?';
$l['error_maxattachpost'] = 'Desculpe, mas não pode anexar este arquivo porque você atingiu o número máximo de anexos permitidos por postagem de {1}';
$l['attachments_disabled'] = 'Você não pode usar o sistema de anexos porque ele foi desabilitado pelo Administrador.';
$l['emailsubject_passwordreset'] = 'Nova senha em {1}';
$l['emailsubject_randompassword'] = 'Sua senha para {1}';
$l['emailsubject_reportprofile'] = 'Usuário reportado em {1}';
$l['emailsubject_reportreputation'] = 'Reputação relatada em {1}';
$l['emailsubject_newjoinrequest'] = 'Novo pedido de inscrição em {1}';
$l['emailsubject_changepassword'] = 'Mudança de senha em {1}';
$l['email_reportprofile'] = '{1} de {2} relatou o seguinte usuário:

{3}
{4} / {5}

A razão que este usuário deu para informar esse usuário:
{6}

Esta mensagem foi enviada para todos os moderadores deste fórum, ou todos os administradores e super moderadores se não houver moderadores.

Por favor, verifique esse usuário o mais rápido possível.';
$l['email_reportreputation'] = '{1} de {2} relatou a seguinte reputação:

{3}
{4} / {5}

A razão pela qual este usuário deu por relatar esta reputação:
{6}

Esta mensagem foi enviada para todos os moderadores deste fórum, ou todos os administradores e super moderadores se não houver moderadores.

Verifique esta reputação o mais rápido possível.';
$l['email_report_comment_extra'] = '{1}: {2}';
$l['email_passwordreset'] = '{1},

Sua senha em {2} foi redefinida.

Sua nova senha é: {3}

Você precisará dessa senha para entrar nos fóruns, uma vez que você efetuar login, você deve mudá-lo indo para o Painel de Controle do Usuário.

Obrigado,
{2} Staff';
$l['email_randompassword'] = '{1},

Obrigado por se registrar no {2}. Abaixo está seu nome de usuário e a senha gerada aleatoriamente. Para entrar no {2}, você precisará desses detalhes.

Nome de usuário: {3}
Senha: {4}

Recomenda-se que você altere sua senha imediatamente após o seu login. Você pode fazer isso indo ao seu CP do usuário e, em seguida, clicando em Alterar senha no menu à esquerda.

Obrigado,
{2} Staff';
$l['email_randompassword1'] = '{1},

Obrigado por se registrar no {2}. Abaixo está seu nome de usuário e a senha gerada aleatoriamente. Para entrar no {2}, você precisará desses detalhes.

Seu endereço de email
Senha: {4}

Recomenda-se que você altere sua senha imediatamente após o seu login. Você pode fazer isso indo ao seu CP do usuário e, em seguida, clicando em Alterar senha no menu à esquerda.

Obrigado,
{2} Staff';
$l['email_randompassword2'] = '{1},

Obrigado por se registrar no {2}. Abaixo está seu nome de usuário e a senha gerada aleatoriamente. Para entrar no {2}, você precisará desses detalhes.

Nome de usuário: {3} (Ou seu endereço de e-mail)
Senha: {4}

Recomenda-se que você altere sua senha imediatamente após o seu login. Você pode fazer isso indo ao seu CP do usuário e, em seguida, clicando em Alterar senha no menu à esquerda.

Obrigado,
{2} Staff';
$l['email_changeemail_noactivation'] = '{1},

Recebemos um pedido no {2} para alterar seu endereço de e-mail (veja os detalhes abaixo).

Endereço de e-mail antigo: {3}
Novo endereço de e-mail: {4}

Esta alteração foi processada automaticamente. Se você não solicitou esta alteração, entre em contato com um Administrador.

Obrigado,
{2} Staff
{5}';
$l['email_changepassword'] = '{1},

Você está recebendo este e-mail porque você, ou alguém com acesso à sua senha, mudou recentemente a senha da sua conta.

Nome de usuário: {1}
Endereço de e-mail: {2}

Se você não solicitou esta alteração, entre em contato com um Administrador.

Obrigado,
{3} Staff
{4}';
$l['email_groupleader_joinrequest'] = '{1},

{2} pediu para participar do {3} no {4} (veja abaixo).

Motivo: {5}

Para aceitar ou recusar esse pedido, acesse

{6} /managegroup.php?gid= {7}

Obrigado,
{4} Staff';
$l['email_contact_subject'] = 'Contato: {1}';
$l['email_contact'] = 'E-mail: {1}
Perfil no Fórum: {2}
IP: {3}
Mensagem:
{4}';
$l['pmsubject_subscription'] = 'Nova reposta para {1}';
$l['pm_subscription'] = '{1},

{2} acabou de responder a um tópico ao qual você se inscreveu. Este tópico é intitulado {3}.

Aqui está um trecho da mensagem:
------------------------------------------
{4}
------------------------------------------

Para visualizar o tópico, você pode acessar o seguinte URL:
[url] {5} / {6} [/url]

Também pode haver outras respostas a este tópico, mas você não receberá mais notificações até você visitar o segmento novamente.

------------------------------------------
Informações de cancelamento de inscrição:

Se você não quiser receber mais notificações de respostas a esse tópico, visite o seguinte URL em seu navegador:
[url]{5}/usercp2.php?action=removesubscription&tid={7}&my_post_key={8}[/url]';
$l['email_broken_task_subject'] = 'Erro da tarefa MyBB em {1}';
$l['email_broken_task'] = 'Sua cópia do MyBB rodando em {1} ({2}) experimentou um erro no sistema de tarefas.

O arquivo de tarefa para {3} está faltando.

Esta tarefa foi desativada até o problema ser resolvido.';
