<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:36:46 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Documentos de Ajuda';
$l['nav_smilies'] = 'Listagem de Sorrisos';
$l['nav_syndication'] = 'Últimos Tópicos Adicionados (RSS)';
$l['aol_im'] = 'AOL';
$l['msn'] = 'MSN';
$l['yahoo_im'] = 'Yahoo';
$l['msn_messenger_center'] = 'Centro de Mensagens MSN';
$l['msn_address_is'] = 'O endereço MSN de {1} é:';
$l['yahoo_center'] = 'Yahoo!';
$l['send_y_message'] = 'Enviar a {1} uma mensagem Yahoo!.';
$l['view_y_profile'] = 'Ver Perfil Yahoo! de {1}.';
$l['aim_center'] = 'AOL';
$l['download_aim'] = 'Download AIM';
$l['aim_remote'] = 'AIM Remoto';
$l['send_me_instant'] = 'Enviar uma mensagem instantânea';
$l['add_me_buddy_list'] = 'Adicionar à Lista de Amigos';
$l['add_remote_to_page'] = 'Adicionar Remoto à sua Página';
$l['download_aol_im'] = 'Download AOL';
$l['buddy_list'] = 'Lista de Amigos';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Enviar Mensagem Privada';
$l['last_active'] = '<strong>Última Atividade:</strong> {1}';
$l['close'] = 'Fechar';
$l['no_buddies'] = '<em>A sua lista de amigos está  vazia. Use o seu User CP ou visite um perfil de usuário para adicionar usuários à sua lista de amigos.</em>';
$l['help_docs'] = 'Documentos de  Ajuda';
$l['smilies_listing'] = 'Listagem de Sorrisos';
$l['name'] = 'Nome';
$l['abbreviation'] = 'Abreviatura';
$l['click_to_add'] = 'Clique num sorriso para inseri-lo na sua mensagem';
$l['close_window'] = 'Fechar Janela';
$l['who_posted'] = 'Quem colocou?';
$l['total_posts'] = 'Total de Mensagens:';
$l['user'] = 'usuário';
$l['num_posts'] = '# Mensagens';
$l['forum_rules'] = '{1} - Regras';
$l['error_invalid_limit'] = 'O limite de feeds de itens que inseriu é inválido. Por favor, especifique um limite válido.';
$l['syndication'] = 'Último Tópico RSS';
$l['syndication_generated_url'] = 'O link gerado para RSS:';
$l['syndication_note'] = 'Abaixo você pode gerar links para especificar os fedds RSS. Os Links podem ser gerados para todos os fóruns, por fórum, ou um número específico de fóruns. Você vai aparecer um link, que pode copiar para um leitor RSS, com este <a href="http://www.sharpreader.net/">SharpReader</a>. <i><a href="http://www.xml.com/pub/a/2002/12/18/dive-into-xml.html">O que é RSS?</a></i>';
$l['syndication_forum'] = 'Fórum para acessar o conteúdo:';
$l['syndication_forum_desc'] = 'Por favor selecione um fórum à direita. Use a tecla CTRL para selecionar vários fóruns.';
$l['syndication_version'] = 'Versão do Feed:';
$l['syndication_version_desc'] = 'Por favor selecione a versão dos feeds que deseja gerar.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (Padrão)';
$l['syndication_generate'] = 'Gerar URL RSS';
$l['syndication_limit'] = 'Limite:';
$l['syndication_limit_desc'] = 'Número de tópicos para download de uma vez. Não é recomendado mais de 50.';
$l['syndication_threads_time'] = 'tópicos de cada vez';
$l['syndicate_all_forums'] = 'Conteúdo de todos os Fóruns';
$l['redirect_markforumread'] = 'O fórum selecionado foi marcado como lido.';
$l['redirect_markforumsread'] = 'Todos os fóruns foram marcados como lidos.';
$l['redirect_forumpasscleared'] = 'A senha armazenada para este fórum foi apagada.';
$l['redirect_cookiescleared'] = 'Todos os cookies foram apagados.';
$l['error_invalidimtype'] = 'Este usuário não tem este tipo de conta de mensagem instantânea no seu perfil.';
$l['error_invalidhelpdoc'] = 'O documento de ajuda especificado parece não existir.';
$l['error_invalidkey'] = 'Não foi possível verificar a exclusão de cookies. Isto pode ter sido causado por um código javascript malicioso, ao tentar apagar os seus cookies automaticamente. Se desejar apagar os seus cookies, por favor leia o documento de ajuda "Uso de cookies no MyBB\\.';
$l['dst_settings_updated'] = 'As suas configurações de horário de verão foram automaticamente ajustadas.<br /><br />Vai agora ser redirecionando para o início do fórum.';
$l['skype'] = 'Skype';
$l['skype_center'] = 'Skype Center';
$l['chat_on_skype'] = 'Chat com{1} no Skype';
$l['call_on_skype'] = 'Ligue {1} no Skype';
$l['online_none'] = '<em>Você  não tem amigos online</em>';
$l['offline_none'] = '<em>Você não tem amigos offlines</em>';
$l['search_help_documents'] = 'Procurar documentos de ajuda';
$l['search_by_name'] = 'Procure por nome';
$l['search_by_document'] = 'Procure por documento';
$l['enter_keywords'] = 'Insira palavras-chaves';
$l['search'] = 'Procurar';
$l['redirect_searchresults'] = 'Obrigado, sua pesquisa foi enviada e você será levado para a lista de resultados.';
$l['search_results'] = 'Resultados da pesquisa';
$l['help_doc_results'] = 'Resultados documentos de ajuda';
$l['document'] = 'Documento';
$l['error_nosearchresults'] = 'Desculpe, mas nenhum resultado foi retornado usando as informações de consulta fornecidas. Redefina seus termos de pesquisa e tente novamente.';
$l['no_help_results'] = 'Desculpe, mas nenhum resultado foi retornado usando as informações de consulta fornecidas.';
$l['error_helpsearchdisabled'] = 'A habilidade de pesquisar os documentos de ajuda foi desabilitada pelo Administrador.';
$l['no_smilies'] = 'Atualmente, não há smilies disponíveis.';
$l['error_invalidforum'] = 'Fórum inválido';
$l['error_invalidsearch'] = 'Foi especificada uma pesquisa inválida. Por favor volte e tente novamente.';
$l['error_no_search_support'] = 'Este mecanismo de banco de dados não suporta pesquisa.';
$l['error_searchflooding'] = 'Desculpe, mas você só pode realizar uma pesquisa a cada {1} segundos. Aguarde outro {2} segundos antes de tentar procurar novamente.';
$l['error_searchflooding_1'] = 'Desculpe, mas você só pode realizar uma pesquisa a cada {1} segundos. Aguarde mais 1 segundo antes de tentar procurar novamente.';
