<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:51:23 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Responder';
$l['post_reply_to'] = 'Responder a {1}';
$l['post_new_reply'] = 'Postar nova resposta a';
$l['reply_to'] = 'Responder ao tópico: {1}';
$l['post_subject'] = 'Assunto da Mensagem:';
$l['your_message'] = 'A sua Mensagem:';
$l['post_options'] = 'Opções da Mensagem:';
$l['options_sig'] = '<strong>Assinatura:</strong> Incluir a sua Assinatura. (apenas membros registados)';
$l['options_emailnotify'] = '<strong>Notificação de Email:</strong> receber um Email sempre que haja uma nova resposta. (apenas membros registrados)';
$l['options_disablesmilies'] = '<strong>Desativar sorrisos:</strong> Desativar Sorrisos, impedindo que apareçam nesta mensagem.';
$l['post_reply'] = 'Postar Resposta';
$l['preview_post'] = 'Visualizar Resposta';
$l['mod_options'] = 'Opções de Moderador:';
$l['close_thread'] = '<strong>Encerrar Tópico</strong>: Prevenir a colocação de mensagens neste tópico.';
$l['stick_thread'] = '<strong>Fixar Tópico:</strong> Fixar este Tópico no topo do Fórum.';
$l['forum_rules'] = '{1} - Regras';
$l['thread_review'] = 'Rever Tópico (Recentes primeiro)';
$l['thread_review_more'] = 'Este tópico tem mais de {1} respostas. <a href="{2}">Ler o Tópico inteiro.</a>';
$l['posted_by'] = 'Postado por';
$l['draft_saved'] = 'A nova mensagem foi guardada nos Rascunhos com sucesso.<br />Retornado à sua listagem de Rascunhos.';
$l['image_verification'] = 'Verificação de Imagem';
$l['verification_note'] = 'Por favor, digite o texto que está na imagem. Este processo é para prevenir registros automáticos.';
$l['verification_subnote'] = '(insensível a maiúsculas)';
$l['invalid_captcha'] = 'O código de verificação da imagem que inseriu está incorreto. Por favor insira o código exatamente como aparece na imagem.';
$l['error_post_already_submitted'] = 'Você já colocou esta mensagem no tópico especificado. Por favor visite o tópico para ver a sua resposta.';
$l['multiquote_external_one'] = 'Você selecionou uma mensagem externa a este Tópico.';
$l['multiquote_external'] = 'Você selecionou {1} mensagens externas a este Tópico.';
$l['multiquote_external_one_deselect'] = 'Desselecionar esta mensagem';
$l['multiquote_external_deselect'] = 'Desselecionar estas mensagens';
$l['multiquote_external_one_quote'] = 'Citar esta mensagem também';
$l['multiquote_external_quote'] = 'Citar estas mensagens também';
$l['redirect_newreply'] = 'Obrigado, a sua resposta foi postada.';
$l['redirect_newreply_moderation'] = 'o Administrador determinou que todas as novas mensagens requerem moderação. Você vai agora retornar ao tópico.';
$l['redirect_newreply_post'] = '<br />Você será redirecionado para a sua mensagem.';
$l['redirect_newreplyerror'] = 'Desculpe, mas a sua resposta foi rejeitada por falta de conteúdo. <br />Você vai retornar ao tópico.';
$l['redirect_threadclosed'] = 'Você não pode inserir respostas neste tópico, porque foi encerrado por um moderador.';
$l['error_post_noperms'] = 'Você não tem privilégios para editar este Rascunho.';
$l['error_stop_forum_spam_spammer'] = 'Desculpe, seu {1} corresponde ao de um spammer conhecido. Se você acha que isso é um erro, entre em contato com um administrador';
$l['error_stop_forum_spam_fetching'] = 'Desculpe, algo correu errado, verificando sua resposta contra um banco de dados de spammer. Provavelmente o banco de dados não pôde ser acessado. Por favor, tente novamente mais tarde.';
$l['error_suspendedposting'] = 'Os privilégios de postagem estão atualmente suspensos {1}. <br /> <br />

Data de Suspensão: {2}';
$l['error_suspendedposting_temporal'] = 'até {1}';
$l['error_suspendedposting_permanent'] = 'permanentemente';
