<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:52:12 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Novo Tópico';
$l['newthread_in'] = 'Novo Tópico em {1}';
$l['post_new_thread'] = 'Inserir novo Tópico';
$l['thread_subject'] = 'Assunto do Tópico';
$l['your_message'] = 'A Sua Mensagem:';
$l['post_options'] = 'Opções de Mensagem:';
$l['options_sig'] = '<b>Assinatura:</b> Incluir a sua assinatura. (apenas membros registrados)';
$l['options_emailnotify'] = '<b>Notificação de Email:</b> receber um Email sempre que houver uma nova resposta. (apenas membros registrados)';
$l['options_disablesmilies'] = '<b>Desativar Sorrisos:</b> Desativar os Sorrisos impede que apareçam nesta mensagem.';
$l['post_thread'] = 'Inserir Mensagem';
$l['preview_post'] = 'Visualizar Mensagem';
$l['poll'] = 'Enquete:';
$l['poll_desc'] = 'Opcionalmente você pode anexar uma enquete a este tópico.';
$l['poll_check'] = 'Eu quero inserir uma enquete';
$l['num_options'] = 'Número de Opções:';
$l['max_options'] = '(Máximo: {1})';
$l['mod_options'] = 'Opções de Moderador:';
$l['close_thread'] = '<b>Encerrar Tópico</b>: Prevenir que coloquem mensagens neste tópico.';
$l['stick_thread'] = '<b>Fixar Tópico:</b> fixar este tópico no topo do fórum.';
$l['draft_saved'] = 'O novo tópico foi salvo nos Rascunhos com sucesso.<br />Você vai agora ser redirecionado para a listagem de Rascunhos.';
$l['image_verification'] = 'Verificação da Imagem';
$l['verification_note'] = 'Por favor, digite o texto que está na imagem. Este processo é para prevenir registros automáticos.';
$l['verification_subnote'] = '(Não é sensível a maiúsculas)';
$l['invalid_captcha'] = 'O código de verificação da imagem que inseriu está incorreto. Por favor insira o código exatamente como aparece na imagem.';
$l['error_post_already_submitted'] = 'Você já postou este tópico no fórum especificado. Por favor visite o fórum para ver o seu tópico.';
$l['no_prefix'] = 'Sem Prefixo';
$l['forum_rules'] = '{1} - Regras';
$l['multiquote_external_one'] = 'Você selecionou uma mensagem de outro tópico.';
$l['multiquote_external'] = 'Você seleccionou {1} mensagens de outros tópicos.';
$l['multiquote_external_one_deselect'] = 'Desselecionar esta mensagem';
$l['multiquote_external_deselect'] = 'Desselecionar estas mensagens';
$l['multiquote_external_one_quote'] = 'Citar esta mensagem também';
$l['multiquote_external_quote'] = 'Citar estas mensagens também';
$l['redirect_newthread'] = 'Obrigado, o seu tópico foi postado.';
$l['redirect_newthread_poll'] = '<br />Você será redirecionado para as opções de configuração da enquete.';
$l['redirect_newthread_moderation'] = '<br />O Administrador determinou que todas os novos tópicos requerem moderação. Você vai agora retornar á listagem de tópicos.';
$l['redirect_newthread_thread'] = '<br />Você vai agora ser redirecionado para o novo tópico.';
$l['invalidthread'] = 'O rascunho especificado não existe ou então você não tem privilégios para o ver.';
$l['redirect_newthread_unviewable'] = '<br /> Você não tem permissão para ver os tópicos neste fórum. Agora você será devolvido ao fórum.';
$l['error_stop_forum_spam_spammer'] = 'Desculpe, seu {1} corresponde ao de um spammer conhecido. Se você acha que isso é um erro, entre em contato com um administrador';
$l['error_stop_forum_spam_fetching'] = 'Desculpe, algo foi errado, verificando seu tópico em um banco de dados de spammer. Provavelmente o banco de dados não pôde ser acessado. Por favor, tente novamente mais tarde.';
$l['error_suspendedposting'] = 'Os privilégios de postagem estão atualmente suspensos {1}. <br /> <br />

Data de Suspensão: {2}';
$l['error_suspendedposting_temporal'] = 'até {1}';
$l['error_suspendedposting_permanent'] = 'permanentemente';
