<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:53:09 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Quem está Online';
$l['nav_onlinetoday'] = 'Quem esteve Online Hoje';
$l['viewing_announcements'] = 'Vendo <a href="{1}">{2}</a> Anúncios';
$l['viewing_announcements2'] = 'Vendo Anúncios';
$l['viewing_attachment'] = 'Vendo Anexos';
$l['viewing_attachment2'] = 'Vendo <a href="attachment.php?aid={1}" target="_blank">Anexos</a> no Tópico <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Vendo <a href="calendar.php">o Calendário</a>';
$l['viewing_event'] = 'Vendo Evento';
$l['viewing_event2'] = 'Vendo Evento <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Adicionar Evento</a>';
$l['editing_event'] = 'Editando Evento';
$l['editing_post'] = 'Editando Mensagem';
$l['viewing_forum'] = 'Vendo Fórum';
$l['viewing_forum2'] = 'Vendo Fórum <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Sendo redirecionado para <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Página Principal</a>';
$l['activating_account'] = 'Ativando conta';
$l['viewing_profile'] = 'Vendo Perfil';
$l['viewing_profile2'] = 'Vendo Perfil de <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Registrando</a>';
$l['logging_in'] = '<a href="member.php?action=login">Autenticando-se em</a>';
$l['logging_in_plain'] = 'Autenticando-se em';
$l['logging_out'] = 'Saindo';
$l['emailing_user'] = 'Enviando Email a um usuário';
$l['rating_user'] = 'Avaliando usuário';
$l['viewing_memberlist'] = 'Vendo <a href="memberlist.php">Lista de Membros</a>';
$l['viewing_whoposted'] = 'Vendo quem postou mensagens';
$l['viewing_whoposted2'] = 'Vendo quem  postou mensagem no Tópico <a href="{1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Marcando fóruns como lidos</a>';
$l['viewing_helpdocs'] = 'Vendo <a href="misc.php?action=help">Documentos de Ajuda</a>';
$l['viewing_buddylist'] = 'Vendo <a href="misc.php?action=buddypopup">Lista de Amigos</a>';
$l['viewing_smilies'] = 'Vendo <a href="misc.php?action=smilies">Lista de Sorrisos</a>';
$l['viewing_syndication'] = 'Vendo <a href="misc.php?action=syndication">RSS</a> Page';
$l['replying_thread'] = 'Respondendo um Tópico';
$l['replying_thread2'] = 'Respondendo o Tópico <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Postando novo Tópico';
$l['posting_thread2'] = 'Postnado novo Tópico em <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Vendo <a href="online.php">Quem está Online</a>';
$l['viewing_woltoday'] = 'Vendo <a href="online.php?action=today">Quem esteve Online hoje</a>';
$l['creating_poll'] = 'Criando uma nova votação';
$l['editing_poll'] = 'Editando uma Votação';
$l['viewing_pollresults'] = 'Vendo resultados de uma Votação';
$l['voting_poll'] = 'Votando';
$l['using_modtools'] = 'Usando Ferramentas de Moderação';
$l['sending_pm'] = 'Enviando uma Mensagem Privada';
$l['reading_pm'] = 'Lendo Mensagem Privada';
$l['editing_pmfolders'] = 'Editando as pastas de MP';
$l['using_pmsystem'] = 'Usando o Sistema de MP';
$l['reporting_post'] = 'Reportando uma Mensagem';
$l['searching_forum'] = '<a href="search.php">Procurando</a> {1}';
$l['reading_thread'] = 'Lendo Tópico';
$l['reading_thread2'] = 'Lendo um Tópico <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Vendo Equipa do Fórum';
$l['viewing_stats'] = 'Vendo Estatísticas do Fórum';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Atualizando Perfil</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Atualizando Opções</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Editando Assinatura</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Alterando um Avatar</a>';
$l['viewing_subscriptions'] = 'Vendo <a href="usercp.php?action=subscriptions">Subscrição de Tópicos</a>';
$l['viewing_favorites'] = 'Vendo <a href="usercp.php?action=favorites">Tópicos favoritos</a>';
$l['editing_pad'] = 'Editando <a href="usercp.php?action=notepad">Bloco de Notas</a>';
$l['editing_password'] = 'Editando <a href="usercp.php?action=password">Senha</a>';
$l['user_cp'] = 'Vendo <a href="usercp.php">Painel de Controle do usuário</a>';
$l['viewing_portal'] = 'Vendo <a href="portal.php">Portal</a> Page';
$l['viewing_noperms'] = 'Vendo Página sem permissão';
$l['unknown_location'] = '<a href="{1}">Localização Desconhecida</a>';
$l['giving_reputation'] = 'Dando reputação para <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Vendo <a href="{1}">{2} Reputação</a>';
$l['viewing_reputation_report2'] = 'Vendo a reputação';
$l['member_resendactivation'] = 'Reenviando código de Ativação de Conta';
$l['member_lostpw'] = 'Recuperando <a href="member.php?action=lostpw">Senha Perdida</a>';
$l['sending_thread'] = 'Enviando Tópico a um amigo';
$l['guest'] = 'Visitante';
$l['page'] = 'Página';
$l['users_online'] = 'Quem está Online';
$l['on_username'] = 'Nome de usuário';
$l['time'] = 'Hora';
$l['location'] = 'Localização';
$l['online_today'] = 'Quem esteve Online hoje';
$l['refresh_page'] = 'Atualizando esta Página';
$l['online_online_plural'] = 'usuários';
$l['online_online_singular'] = 'usuário';
$l['online_member_plural'] = 'membros';
$l['online_member_singular'] = 'membro';
$l['online_anon_plural'] = 'são';
$l['online_anon_singular'] = 'é';
$l['online_guest_plural'] = 'visitantes';
$l['online_guest_singular'] = 'visitante';
$l['online_count'] = '{1} {2} ativo nos últimos {3} minutos ({4} {5}, {6} dos quais {7} invisíveis, e {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Nome do Servidor:';
$l['if_resolvable'] = '(Se Resolvido)';
$l['admin_options'] = 'Opções de Administrador:';
$l['search_regip_users'] = 'Procurar usuários que tenham registrado-se com este IP';
$l['search_postip_users'] = 'Procurar usuários que tenham postado mensagens com este IP';
$l['lookup'] = '[Verificar]';
$l['member_online_today'] = '<strong>1</strong> Membros estiveram online hoje';
$l['members_were_online_today'] = '<strong>{1}</strong> Membros Online hoje';
$l['member_online_hidden'] = ' ({1} membro era invisível )';
$l['members_online_hidden'] = ' ({1} membros eram invisíveis)';
$l['rating_thread'] = 'Avaliando tópico';
$l['viewing_imcenter'] = 'Vendo Centro IM';
$l['managing_favorites'] = 'Gerir Tópicos Favoritos';
$l['managing_subscriptions'] = 'Gerir Tópicos Subscritos';
$l['managing_group'] = 'Gerir Grupo de usuários';
$l['viewing_modcp'] = 'Vendo Painel de Moderador';
$l['viewing_modlogs'] = 'Vendo histórico de Moderador';
$l['managing_announcements'] = 'Gerenciando Anúncios';
$l['search_for_user'] = 'Procurando usuários';
$l['managing_warninglogs'] = 'Gerenciando histórico de Avisos';
$l['searching_ips'] = 'Procurando IPs';
$l['viewing_reports'] = 'Vendo Mensagens Reportadas';
$l['adding_announcement'] = 'Adicionado um Anúncio';
$l['deleting_announcement'] = 'Apagando um Anúncio';
$l['editing_announcement'] = 'Editando um Anúncio';
$l['managing_modqueue'] = 'Gerenciando Fila de Moderação';
$l['editing_user_profiles'] = 'Editando Perfil de usuários';
$l['managing_bans'] = 'Gerenciando Expulsões';
$l['revoking_warning'] = 'Excluindo um Aviso';
$l['warning_user'] = 'Alertando usuário';
$l['viewing_warning'] = 'Vendo Avisos';
$l['managing_warnings'] = 'Gerir Avisos';
$l['changing_dst'] = 'Alterando DST';
$l['printing_thread'] = 'Imprimindo Tópico';
$l['printing_thread2'] = 'Imprimindo Tópico <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Gerenciando uma lista de Amigos/Ignorados';
$l['viewing_contact_us'] = 'Vendo <a href="contact.php">Contate-nos</a>';
