<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:53:58 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = 'Inserir Votação';
$l['nav_editpoll'] = 'Editar Votação';
$l['nav_pollresults'] = 'Resultados da Votação';
$l['edit_poll'] = 'Editar Votação';
$l['delete_poll'] = 'Remover Votação';
$l['delete_q'] = 'Remover?';
$l['delete_note'] = 'Para remover esta votação, marque a caixa à esquerda e clique no botão à direita.';
$l['delete_note2'] = '<b>Nota:</b> Assim que esta votação foi removida, não existe maneira de recuperá-la.';
$l['question'] = 'Questão:';
$l['num_options'] = 'Número de opções:';
$l['max_options'] = 'Máximo:';
$l['poll_options'] = 'Opções de Votação:';
$l['update_options'] = 'Atualizar Opções';
$l['poll_options_note'] = 'Opções da Votação devem ser curtas e diretas.';
$l['options'] = 'Opções:';
$l['option_multiple'] = '<b>Permitir múltipla escolha:</b> usuários podem votar em mais que uma opção.';
$l['option_public'] = '<b>Votação Pública:</b> Permite aos usuários a habilidade de ver em que opções os usuários votaram.';
$l['option_closed'] = '<b>Votação Encerrada:</b> Se marcada, a votação irá encerrar através da participação.';
$l['poll_timeout'] = 'tempo Limite da Votação:';
$l['timeout_note'] = 'O número de dias que os usuários podem participar nesta votação.<br />(coloque 0 para não ter tempo limite.)';
$l['days_after'] = 'dias depois:';
$l['update_poll'] = 'Atualizar Votação';
$l['option'] = 'Opção';
$l['votes'] = 'Votos:';
$l['post_new_poll'] = 'Colocar Nova Votação';
$l['days'] = 'dias';
$l['poll_results'] = 'Resultados da votação';
$l['poll_total'] = 'Total:';
$l['poll_votes'] = 'votos';
$l['redirect_pollposted'] = 'A sua votação foi postada.<br />Você vai agora retornar ao tópico.';
$l['redirect_pollpostedmoderated'] = 'A sua votação foi postada, mas o seu tópico continua a aguardar por moderação.<br />Você vai retornar ao Fórum.';
$l['redirect_pollupdated'] = 'A votação foi atualizada.<br />Você vai agora retornar ao tópico.';
$l['redirect_votethanks'] = 'Obrigado por votar.<br />Você vai agora retornar ao tópico.';
$l['redirect_unvoted'] = 'O seu voto neste tópico foi removido.<br />Você vai agora retornar ao tópico.';
$l['redirect_polldeleted'] = 'Obrigado, a votação foi removida do tópico com sucesso.<br />Você vai agora retornar ao tópico.';
$l['error_polloptiontoolong'] = 'Uma ou mais opões da votação inseridas são longas e extrapolam o limite permitido. Por favor, volte atrás e reduza o tamanho.';
$l['error_noquestionoptions'] = 'Você ainda não inseriu uma questão para a sua votação ou não são opções suficientes. O número mínimo de opções que uma votação pode ter são 2.<br />Por favor volte atrás e corrija este erro.';
$l['error_pollalready'] = 'O Tópico já tem uma votação!';
$l['error_nopolloptions'] = 'A opção de votação especificada é inválida ou não existe.';
$l['error_alreadyvoted'] = 'Você já participou nesta votação.';
$l['error_notvoted'] = 'Você ainda não participou nesta votação.';
$l['error_invalidpoll'] = 'A Votação especificada é inválida e não existe.';
$l['error_pollclosed'] = 'Você não pode participar nesta votação porque está encerrada.';
$l['poll_deleted'] = 'Deletar votação';
$l['poll_edited'] = 'Editar votação';
$l['option_multiple_maxoptions'] = 'Número máximo de opções por usuário (0 sem limite):';
$l['error_polloptionsequence'] = 'Uma ou mais opções de votação que você inseriu contêm uma seqüência que não deve ser usada nelas: <strong> || ~ | ~ || </ strong>. Volte e remova-o.';
$l['error_maxpolloptions'] = 'Você votou em muitas opções. Você só pode votar em {1} opções. <br /> Por favor, volte e tente novamente.';
$l['poll_time_limit'] = 'Desculpe, mas você não pode adicionar uma pesquisa ao seu tópico. O Administrador configurou-o para que as pesquisas só possam ser adicionadas dentro de {1} horas de publicação.';
