<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:54:22 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portal';
$l['posted_by'] = 'Inserido por:';
$l['replies'] = 'Respostas';
$l['no_replies'] = 'Sem Respostas';
$l['latest_threads'] = 'Últimos Tópicos';
$l['latest_threads_replies'] = 'Respostas:';
$l['latest_threads_views'] = 'Visualizações:';
$l['latest_threads_lastpost'] = 'Última Mensagem:';
$l['private_messages'] = 'Mensagens Privadas';
$l['pms_received_new'] = '{1}, Você tem <b>{2}</b> mensagem(s) por ler.';
$l['pms_unread'] = 'Mensagens por ler';
$l['pms_total'] = 'Total de Mensagens';
$l['search_forums'] = 'Pesquisar Nos Fóruns';
$l['advanced_search'] = 'Pesquisa Avançada';
$l['forum_stats'] = 'Estatísticas do Fórum';
$l['num_members'] = 'Membros:';
$l['latest_member'] = 'Último Membro:';
$l['num_threads'] = 'Tópicos do Fórum:';
$l['num_posts'] = 'Inserção de Mensagens:';
$l['full_stats'] = 'Estatísticas Completas';
$l['welcome'] = 'Bem Vindo, {1}';
$l['guest'] = 'Visitante';
$l['guest_welcome_registration'] = 'Você tem que se <a href="{1}">registrar</a> antes, para poder colocar mensagens no Fórum.';
$l['username'] = 'Nome de usuário';
$l['password'] = 'Senha';
$l['login'] = 'Entrar!';
$l['member_welcome_lastvisit'] = 'Última Visita:';
$l['since_then'] = 'Desde aí, foram postados:';
$l['new_announcements'] = '{1} anúncios novos';
$l['new_announcement'] = '1 anúncio novo';
$l['new_threads'] = '{1} tópicos novos';
$l['new_thread'] = '1 tópico novo';
$l['new_posts'] = '{1} mensagens novas';
$l['new_post'] = '1 mensagem nova';
$l['view_new'] = 'Ver Novas Mensagens';
$l['view_todays'] = 'Ver Mensagens de Hoje';
$l['online'] = 'usuários Online';
$l['online_user'] = 'Está de momento 1 usuário online';
$l['online_users'] = 'Estão de momento <b>{1}</b> usuárioes online.';
$l['online_counts'] = '<b>{1}</b> Membro(s) | <b>{2}</b> Visitante(s)';
$l['no_one'] = 'Ninguém';
$l['print_this_item'] = 'Imprimir este artigo';
$l['send_to_friend'] = 'Enviar este artigo a um amigo';
$l['forum'] = 'Fórum:';
$l['latest_announcements'] = 'Último anúncios';
$l['portal_disabled'] = 'Você não pode usar a funcionalidade do portal como ele foi desabilitado pelo Administrador.';
