<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:56:15 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Obrigado, o tópico foi avaliado com sucesso. Vai agora retornar ao tópico.';
$l['error_invalidrating'] = 'Você selecionou uma avaliação inválida para este tópico. Por favor, volte atrás e tente novamente.';
$l['error_alreadyratedthread'] = 'Desculpe, mas você já avaliou este tópico.';
$l['rating_votes_average'] = '{1} Voto(s) - {2} de 5 na totalidade';
$l['one_star'] = '1 estrela de 5';
$l['two_stars'] = '2 estrelas de 5';
$l['three_stars'] = '3 estrelas de 5';
$l['four_stars'] = '4 estrelas de 5';
$l['five_stars'] = '5 estrelas de 5';
$l['rating_added'] = 'A sua avaliação foi adicionada!';
$l['error_cannotrateownthread'] = 'Desculpe, você não pode avaliar seu próprio tópico.';
