<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:57:42 +0000
// --------------------------------------------------------------------------------

$l['report_post'] = 'Mensagem Reportada';
$l['report_to_mod'] = 'Reportar esta mensagem a um moderador';
$l['only_report'] = 'Você deve apenas reportar mensagens que sejam spam, mensagens de publicidade, abusivas e que esteja em desacordo com os as regras deste fórum.';
$l['report_reason'] = 'O seu motivo para reportar esta mensagem:';
$l['thank_you'] = 'Obrigado.';
$l['post_reported'] = 'Esta mensagem foi reportada com sucesso. Você já pode fechar esta janela.';
$l['report_error'] = 'Erro';
$l['no_reason'] = 'Você não pode reportar uma mensagem sem ter um motivo específico para reportar.';
$l['go_back'] = 'Voltar';
$l['close_window'] = 'Fechar Janela';
$l['report_content'] = 'Reportar conteúdo';
$l['report_reason_post'] = 'Reportar post';
$l['report_reason_profile'] = 'Reportar perfil';
$l['report_reason_reputation'] = 'Reportar reputação';
$l['report_reason_rules'] = 'Quebrar as regras do fórum';
$l['report_reason_bad'] = 'Conteúdo inapropriado';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_wrong'] = 'Fórum errado';
$l['report_reason_other'] = 'Outra';
$l['success_report_voted'] = 'Obrigado por reportar esse conteúdo. <br /> Um membro da equipe do fórum verificará seu relatório em breve.';
$l['error_report_length'] = 'Forneça um motivo detalhado para o seu relatório.';
$l['error_invalid_report'] = 'Este conteúdo não existe ou não pode ser reportado.';
$l['error_invalid_report_reason'] = 'O motivo selecionado é inválido.';
$l['error_comment_required'] = 'É necessário um comentário adicional para o motivo selecionado.';
$l['error_report_duplicate'] = 'Este conteúdo já foi reportado por outro membro. <br /> Você também pode denunciar este conteúdo abaixo.';
$l['report_reason_other_description'] = 'Forneça mais informações sobre por que você está relatando esse conteúdo.';
