<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:58:44 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Relatório de Reputação';
$l['nav_profile'] = 'Perfil de {1}';
$l['reputation_disabled'] = 'Não é possível usar o sistema de reputação uma vez que o mesmo foi desativado por um administrador.';
$l['reputation'] = 'Reputação';
$l['error'] = 'Erro';
$l['add_no_uid'] = 'Não selecionou nenhum usuário para dar reputação.';
$l['add_no_permission'] = 'Não tem permissão para votar na reputação de outros usuários.';
$l['add_disabled'] = 'Não pode votar na reputação dos usuárioes deste grupo.';
$l['add_yours'] = 'Não pode votar na sua própria reputação.';
$l['add_invalidpower'] = 'Selecionou uma opção de votação inválida.';
$l['add_maxperday'] = 'Atingiu o máximo de pontos de reputação que pode atribuir diariamente.';
$l['add_maxperuser'] = 'Já atribuiu a este usuário os pontos máximos diários.';
$l['add_maxperthread'] = 'Já atribuiu a este usuário os pontos máximos (só num tópico) que pode atribuir diariamente.';
$l['add_no_comment'] = 'Você deve inserir um comentário de pelo menos 10 caracteres, para avaliar a reputação deste usuário.';
$l['add_toolong'] = 'Você tem de inserir um motivo, que não contenha mais de {1} caracteres.';
$l['add_negative_disabled'] = 'O Administrador desativou as reputações negativas.';
$l['add_neutral_disabled'] = ' O Administrador desativou as reputações neutras.';
$l['add_positive_disabled'] = ' O Administrador desativou as reputações positivas.';
$l['add_all_rep_disabled'] = ' O Administrador desativou todo o tipo de reputações. Você não pode avaliar este usuário.';
$l['reputation_report'] = 'Relatório de Reputação de {1}';
$l['reputation_members'] = 'Reputação de Membros:';
$l['reputation_posts'] = 'Reputação de Mensagens:';
$l['summary'] = 'Sumário';
$l['total_reputation'] = 'Reputação Total';
$l['post_reputation'] = 'Reputação de Mensagens';
$l['positive_count'] = 'Positivas';
$l['neutral_count'] = 'Neutras';
$l['negative_count'] = 'Negativas';
$l['last_week'] = 'Última Semana';
$l['last_month'] = 'Último Mês';
$l['last_6months'] = 'Últimos 6 meses';
$l['comments'] = 'Comentários';
$l['close_window'] = 'Fechar Janela';
$l['go_back'] = 'Voltar';
$l['add_reputation_vote'] = 'Adicionar uma avaliação de reputação de {1}';
$l['add_reputation_to_post'] = 'Esta reputação é para a mensagem de {1}.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>A reputação negativa está de momento desativada</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em> A reputação positiva está de momento desativada </em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em> A reputação neutra está de momento desativada </em></span>';
$l['no_comment_needed'] = 'Você está a editar a reputação, devido às mensagens deste(s) usuário(s), que está ligada aos seus perfis. Não é necessário um comentário, mas se quiser pode deixar um, por favor insira-o em baixo.<br />';
$l['no_comment'] = '[Sem comentário]';
$l['vote_added'] = 'Avaliação Adicionada';
$l['vote_updated'] = 'Avaliação Atualizada';
$l['vote_deleted'] = 'Avaliação Apagada';
$l['vote_added_message'] = 'A sua avaliação de reputação foi adicionada com sucesso para este usuário.';
$l['vote_updated_message'] = 'A sua avaliação de reputação foi atualizada com sucesso para este usuário.';
$l['vote_deleted_message'] = 'A avaliação de reputação foi apagada com sucesso para este usuário.';
$l['update_reputation_vote'] = 'Atualizar avaliação de reputação de {1}';
$l['positive'] = 'Positiva';
$l['negative'] = 'Negativa';
$l['neutral'] = 'Neutra';
$l['user_comments'] = 'Os seus comentários em {1}:';
$l['add_vote'] = 'Adicionar Avaliação';
$l['update_vote'] = 'Atualizar Avaliação';
$l['delete_vote'] = 'Deletar Avaliação';
$l['power_positive'] = 'Positiva ({1})';
$l['power_neutral'] = 'Neutra';
$l['power_negative'] = 'Negativa ({1})';
$l['show_all'] = 'Visualizar: Todos os Votos';
$l['show_positive'] = 'Mostrar: Avaliações Positivas';
$l['show_neutral'] = 'Mostrar: Avaliações Neutras';
$l['show_negative'] = 'Mostrar: Avaliações Negativas';
$l['sort_updated'] = 'Ordenar por: Última Atualização';
$l['sort_username'] = 'Ordenar por: Nome de usuário';
$l['last_updated'] = 'Última Atualização {1}';
$l['postrep_post'] = 'Mensagem #';
$l['postrep_given'] = 'Avaliação dada para <a href="{1}">mensagem de {2}</a> {3} <br />';
$l['no_reputation_votes'] = 'Este usuário, de momento não tem nenhuma avaliação de reputação de acordo com o critério especificado abaixo.';
$l['delete_reputation_confirm'] = 'Tem  a certeza que quer apagar esta avaliação de reputação?';
$l['delete_reputation_log'] = 'Reputação removida por {1} (UID: {2})';
$l['reputations_disabled_group'] = 'O sistema de reputação está desativado para usuários deste Grupo.';
$l['rate_user'] = 'Avaliar usuário';
$l['all_time'] = 'Todo tempo';
$l['report_vote'] = 'Reportar';
$l['postrep_given_nolink'] = 'Classificação dada para a postagem de {1} <br />';
$l['postrep_given_thread'] = 'em <a href="{1}">{2}</a>';
