<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 17:59:53 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Pesquisar';
$l['nav_results'] = 'Resultados';
$l['pages_last'] = 'Última';
$l['search'] = 'Pesquisar';
$l['search_keyword'] = 'Pesquisar por palavra chave';
$l['search_username'] = 'Pesquisar por usuário';
$l['search_entire_post'] = 'Pesquisar na mensagem inteira';
$l['search_titles_only'] = 'Pesquisar apenas por títulos';
$l['match_username'] = 'coincidir com nome de usuário';
$l['search_forums'] = 'Pesquisar no(s) Fórum(s)';
$l['search_all_forums'] = 'Pesquisar em todos os Fóruns abertos';
$l['search_options'] = 'Opções de Pesquisa';
$l['threads_at_least'] = 'Procurar tópicos com pelo menos';
$l['threads_at_most'] = 'Procurar tópicos com mais';
$l['find_anydate'] = 'Procurar mensagens por qualquer data de colocação';
$l['find_yesterday'] = 'Procurar mensagens de ontem';
$l['find_lastweek'] = 'Procurar mensagens de 1 semana atrás';
$l['find_2weeks'] = 'Procurar mensagens de 2 semanas atrás';
$l['find_month'] = 'Procurar mensagens de 1 mês atrás';
$l['find_3months'] = 'Procurar mensagens de 3 meses atrás';
$l['find_6months'] = 'Procurar mensagens de 6 meses atrás';
$l['find_year'] = 'Procurar por mensagens com mais de 1 Ano atrás';
$l['and_newer'] = 'mais recente';
$l['and_older'] = 'mais antiga';
$l['sorting_options'] = 'Opções de Ordenação';
$l['sort_lastpost'] = 'Ordenar por data da última mensagem';
$l['sort_author'] = 'Ordenar resultados por Autor';
$l['sort_forum'] = 'Ordenar resultados por Fóruns';
$l['sort_in'] = 'em ordem';
$l['sort_asc'] = 'ascendente';
$l['sort_desc'] = 'descendente';
$l['sort_order'] = 'ordem';
$l['asc'] = 'asc';
$l['desc'] = 'desc';
$l['display_options'] = 'Opções de visualização';
$l['show_results_as'] = 'Mostrar resultados como';
$l['show_results_threads'] = 'Tópicos';
$l['show_results_posts'] = 'Mensagens';
$l['search_results'] = 'Opções de Pesquisa';
$l['post'] = 'Mensagem';
$l['author'] = 'Autor';
$l['forum'] = 'Fórum';
$l['replies'] = 'Respostas';
$l['views'] = 'Visualizações';
$l['posted'] = 'Mensagem Postada';
$l['thread'] = 'Tópico Postado';
$l['lastpost'] = 'Última Mensagem';
$l['post_thread'] = 'Tópico:';
$l['post_subject'] = 'Mensagem:';
$l['replies2'] = 'Respostas';
$l['selectall'] = 'Selecione todos os resultados adicionais?';
$l['any_prefix'] = 'Procurar tópicos por qualquer prefixo';
$l['no_prefix'] = 'Sem prefixo';
$l['inline_thread_moderation'] = 'Moderação de tópico:';
$l['close_threads'] = 'Encerrar tópicos';
$l['open_threads'] = 'Abrir Tópicos';
$l['stick_threads'] = 'Fixar Tópicos';
$l['unstick_threads'] = 'Desafixar Tópicos';
$l['delete_threads'] = 'Deletar Tópicos';
$l['move_threads'] = 'Mover Tópicos';
$l['approve_threads'] = 'Aprovar Tópicos';
$l['unapprove_threads'] = 'Não Aprovar Tópicos';
$l['inline_delete_posts'] = 'Deletar Mensagens';
$l['inline_merge_posts'] = 'Juntar Mensagens';
$l['inline_split_posts'] = 'Dividir Mensagens';
$l['inline_approve_posts'] = 'Aprovar Mensagens';
$l['inline_unapprove_posts'] = 'Não Aprovar Mensagens';
$l['inline_post_moderation'] = 'Moderação de Mensagens:';
$l['inline_go'] = 'Ir';
$l['clear'] = 'Limpar';
$l['icon_dot'] = 'Contém mensagens suas. ';
$l['icon_no_new'] = 'Sem novas mensagens.';
$l['icon_new'] = 'Novas mensagens.';
$l['icon_hot'] = ' Tópico quente.';
$l['icon_lock'] = ' Tópico bloqueado.';
$l['attachment_count'] = 'Este tópico contém 1 anexo.';
$l['attachment_count_multiple'] = 'Este tópico contém {1} anexos.';
$l['goto_first_unread'] = 'Ir para a primeira mensagem por ler';
$l['page_selected'] = 'Todos os <strong>{1}</strong> resultados desta página estão selecionados.';
$l['all_selected'] = 'Todos os <strong>{1}</strong> resultados nesta pesquisa estão selecionados.';
$l['select_all'] = 'Selecionar todos os <strong>{1}</strong> resultados nesta Pesquisa.';
$l['clear_selection'] = 'Limpar Seleção.';
$l['results'] = 'Resultados';
$l['mod_options'] = 'Opções de Moderador';
$l['find_all'] = 'Procurar tudo';
$l['find_only_approved'] = 'Procurar por aprovados apenas';
$l['find_only_unapproved'] = 'Procurar por desaprovados apenas';
$l['redirect_searchresults'] = 'Obrigado, a sua pesquisa foi colocada e vai agora ser redirecionado para a lista de resultados.';
$l['error_minsearchlength'] = 'Um ou mais dos seus critérios de pesquisa foram menores que o comprimento mínimo. O comprimento mínimo de pesquisa é de {1} caracteres.<br /><br />Se você esta a tentar pesquisar por uma frase inteira, coloque-a entre  aspas. Por exemplo "A rápida raposa castanha ataca o preguiçoso cão".';
$l['error_nosearchresults'] = 'Desculpe, mas não foram obtidos resultados, com os critérios de pesquisa colocados. Por favor altere os critérios de pesquisa e tente novamente.';
$l['error_no_search_support'] = 'Esta Base de Dados não suporta pesquisas.';
$l['error_nosearchterms'] = 'Você não inseriu nenhum critério de pesquisa. No mínimo, deves inserir alguns critérios de pesquisa ou nome de usuário para efetuar a pesquisa.';
$l['error_searchflooding_1'] = 'Desculpe, mas você apenas pode efetuar uma pesquisa a cada {1} segundos. Por favor aguarde mais 1 segundo antes de tentar pesquisar novamente.';
$l['error_searchflooding'] = 'Desculpe, mas você apenas pode efetuar uma pesquisa a cada {1} segundos. Por favor aguarde mais {2} segundos antes de tentar pesquisar novamente.';
$l['error_invalidsearch'] = 'Foi inserida uma pesquisa inválida.  Por favor, volte atrás e tente novamente.';
$l['soft_delete_threads'] = 'Deletar Tópicos';
$l['restore_threads'] = 'Restaurar Tópicos';
$l['inline_soft_delete_posts'] = 'Deletar Mensagens';
$l['inline_restore_posts'] = 'Restaurar Mensagens';
$l['inline_move_posts'] = 'Mover Mensagens';
$l['display_all'] = 'Mostrar todos';
$l['display_only_approved'] = 'Mostrar apenas aprovados';
$l['display_only_unapproved'] = 'Mostrar apenas não aprovados';
$l['display_only_softdeleted'] = 'Mostrar apenas deletados';
