<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:00:17 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Equipe do Fórum';
$l['forum_team'] = 'Equipe do Fórum';
$l['moderators'] = 'Moderadores';
$l['mod_username'] = 'Nome de usuário';
$l['mod_forums'] = 'Fórun(s)';
$l['mod_email'] = 'Email';
$l['mod_pm'] = 'MP';
$l['uname'] = 'Nome de usuário';
$l['email'] = 'Email';
$l['pm'] = 'MP';
$l['group_leaders'] = 'Líder(s)';
$l['group_members'] = 'Membro(s)';
$l['no_members'] = 'Sem membros neste grupo';
$l['error_noteamstoshow'] = 'Não existem Equipes do Fórum para exibição.';
$l['username'] = 'Username';
$l['lastvisit'] = 'Última visita';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['away'] = 'Ausente';
