<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:03:09 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Remover Votação';
$l['close_thread'] = 'Encerrar Tópico';
$l['stick_thread'] = 'Fixar Tópico';
$l['author'] = 'Autor';
$l['message'] = 'Mensagem';
$l['threaded'] = 'Modo listagem';
$l['linear'] = 'Modo Linear';
$l['next_oldest'] = 'Mais Antigo';
$l['next_newest'] = 'Mais Recente';
$l['view_printable'] = 'Ver Vista de Impressão';
$l['send_thread'] = 'Enviar este Tópico a um Amigo';
$l['subscribe_thread'] = 'Subscrever este tópico';
$l['unsubscribe_thread'] = 'Anular Subscrição deste tópico';
$l['moderation_options'] = 'Opções de Moderação:';
$l['delayed_moderation'] = 'Moderação Adiada';
$l['thread_notes'] = 'Editar/ Ver Notas de Tópico';
$l['open_close_thread'] = 'Abrir / Encerrar Tópico';
$l['approve_thread'] = 'Aprovar Tópico';
$l['unapprove_thread'] = 'Não Aprovar Tópico';
$l['delete_thread'] = 'Deletar Tópico';
$l['delete_posts'] = 'Deletar mensagens selecionadas';
$l['move_thread'] = 'Mover / Copiar Tópico';
$l['stick_unstick_thread'] = 'Fixar/ Desafixar Tópico';
$l['split_thread'] = 'Dividir Tópico';
$l['merge_threads'] = 'Mesclar Tópicos';
$l['merge_posts'] = 'Mesclar Mensagens Seleccionadas';
$l['remove_redirects'] = 'Remover Redirecionamentos';
$l['remove_subscriptions'] = 'Remover Todas as Subscrições';
$l['poll'] = 'Votação:';
$l['show_results'] = 'Mostrar Resultados';
$l['edit_poll'] = 'Editar Votação';
$l['public_note'] = '<b>Nota:</b> Esta Votação é Pública, onde outros usuários vão poder ver o que escolheu.';
$l['total'] = 'Total';
$l['vote'] = 'Vote!';
$l['total_votes'] = '{1} votos';
$l['you_voted'] = '* Você votou por este item.';
$l['poll_closed'] = 'Esta votação está encerrada.';
$l['already_voted'] = 'Você já fez uma escolha nesta votação.';
$l['undo_vote'] = 'Anular voto';
$l['quick_reply'] = 'Resposta Rápida';
$l['message_note'] = 'Coloque a sua resposta a esta mensagem aqui.';
$l['signature'] = 'Assinatura';
$l['email_notify'] = 'Notificação de Email';
$l['disable_smilies'] = 'Desativar Sorrisos';
$l['post_reply'] = 'Inserir Resposta';
$l['post_reply_img'] = 'Inserir Resposta';
$l['post_thread'] = 'Inserir Tópico';
$l['preview_post'] = 'Visualizar Mensagem';
$l['rating_average'] = '{1} votos - {2} Média';
$l['rate_thread'] = 'Avaliar este Tópico:';
$l['thread_rating'] = 'Avaliação do Tópico:';
$l['similar_threads'] = 'Possíveis Tópicos Relacionados...';
$l['thread'] = 'Tópico:';
$l['replies'] = 'Respostas:';
$l['views'] = 'Visualizações:';
$l['lastpost'] = 'Última Mensagem';
$l['messages_in_thread'] = 'Mensagem neste Tópico';
$l['users_browsing_thread'] = 'usuários a ver este tópico:';
$l['users_browsing_thread_guests'] = '{1} Visitante(s)';
$l['users_browsing_thread_invis'] = '{1} usuário invisível(s)';
$l['users_browsing_thread_reading'] = 'A ler...';
$l['inline_delete_posts'] = 'Deletar mensagens';
$l['inline_merge_posts'] = 'Mesclar Mensagens';
$l['inline_split_posts'] = 'Separar Mensagens';
$l['inline_approve_posts'] = 'Aprovar Mensagens';
$l['inline_unapprove_posts'] = 'Não Aprovar Mensagens';
$l['inline_post_moderation'] = 'Moderação de Mensagem:';
$l['inline_go'] = 'Ir';
$l['clear'] = 'Limpar';
$l['thread_closed'] = 'Tópico Encerrado';
$l['no_subject'] = 'Sem Assunto';
$l['error_nonextnewest'] = 'Não existem tópicos mais recentes, que aqueles que está a ver.';
$l['error_nonextoldest'] = 'Não existem tópicos mais antigos, que aqueles que está a ver.';
$l['quickreply_multiquote_selected'] = 'Você selecionou uma ou mais mensagens para citar.';
$l['quickreply_multiquote_now'] = 'citar estas Mensagens agora';
$l['or'] = 'ou';
$l['quickreply_multiquote_deselect'] = 'desselecioná-las';
$l['search_thread'] = 'Procurar Tópico';
$l['enter_keywords'] = 'Insira uma palavra Chave';
$l['image_verification'] = 'Verificação de Imagem';
$l['verification_note'] = 'Por favor, insira o texto que se encontra na imagem, na caixa de texto. Este processo previne registros automáticos.';
$l['verification_subnote'] = '(Insensível a maiúsculas)';
$l['thread_modes'] = 'Modos de Tópico';
$l['add_poll_to_thread'] = 'Adicionar Pesquisa para esse tópico';
$l['soft_delete_thread'] = 'Deletar Tópico';
$l['restore_thread'] = 'Restaurar Tópico';
$l['poll_closes'] = 'Essa pesquisa vai fechar em: {1}';
$l['new_reply'] = 'Nova Resposta';
$l['search_button'] = 'Procurar';
$l['inline_soft_delete_posts'] = 'Deletar Mensagem';
$l['inline_restore_posts'] = 'Restaurar Mensagens';
$l['inline_move_posts'] = 'Mover mensagens';
$l['view_thread_notes'] = 'Notas de tópico';
$l['view_all_notes'] = 'Ver todas as notas';
$l['save_changes'] = 'Salvar mudanças';
$l['cancel_edit'] = 'Cancelar Edição';
$l['quick_edit_update_error'] = 'Ocorreu um erro ao editar a sua resposta:';
$l['quick_reply_post_error'] = 'Ocorreu um erro ao postar sua resposta:';
$l['quick_delete_error'] = 'Ocorreu um erro ao excluir a sua resposta:';
$l['quick_delete_success'] = 'A postagem foi excluída com sucesso.';
$l['quick_delete_thread_success'] = 'O tópico foi excluído com sucesso.';
$l['quick_restore_error'] = 'Ocorreu um erro ao restaurar sua resposta:';
$l['quick_restore_success'] = 'O post foi restaurado com sucesso.';
