<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:04:04 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Estatísticas do Fórum';
$l['board_stats'] = 'Estatísticas do Fórum';
$l['none'] = 'Nenhum';
$l['nobody'] = 'Ninguém';
$l['totals'] = 'Totais';
$l['averages'] = 'Médias';
$l['posts'] = 'Mensagens:';
$l['threads'] = 'Tópicos:';
$l['members'] = 'Membros:';
$l['ppd'] = 'Mensagens por dia:';
$l['tpd'] = 'Tópicos por dia:';
$l['mpd'] = 'Membros por dia:';
$l['ppm'] = 'mensagens por membro:';
$l['rpt'] = 'Respostas por tópico:';
$l['no_posts'] = 'Não';
$l['general'] = 'Geral';
$l['newest_member'] = 'Membro Novo:';
$l['members_posted'] = 'Membros que postaram:';
$l['todays_top_poster'] = 'Post do Dia: <b>{1}</b> (<b>{2}</b> mensagens)';
$l['popular_forum'] = 'Fórum mais Popular: <b>{1}</b> (<b>{2}</b> mensagens, <b>{3}</b> tópicos)';
$l['most_popular'] = 'Mais Popular...';
$l['most_replied_threads'] = 'Tópicos com Mais respostas';
$l['most_viewed_threads'] = 'Tópicos mais vistos';
$l['not_enough_info_stats'] = 'Desculpe, mas não existe informação suficiente neste Fórum para gerar estatísticas. Para as estatísticas serem geradas, necessita de ter pelo menos 1 membro e 1 tópico.';
$l['replies'] = 'respostas';
$l['views'] = 'visualizadas';
$l['stats_disabled'] = 'Você não pode visualizar a página de estatísticas porque foi desabilitado pelo Administrador.';
$l['tpm'] = 'Tópicos por membro:';
$l['top_referrer'] = 'Maior referenciador: <strong>{1}</strong> (<strong> {2}</strong> referências)';
