<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:04:14 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'Todos os Fóruns';
$l['forum'] = 'Fórum:';
$l['posted_by'] = 'Colocado Por:';
$l['on'] = 'em';
$l['portal'] = 'Portal
';
