<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:04:31 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Menu';
$l['ucp_nav_messenger'] = 'Mensagens';
$l['ucp_nav_compose'] = 'Nova Mensagem';
$l['ucp_nav_tracking'] = 'Seguir';
$l['ucp_nav_edit_folders'] = 'Editar Pastas';
$l['ucp_nav_profile'] = 'O Seu Perfil';
$l['ucp_nav_edit_profile'] = 'Editar Perfil';
$l['ucp_nav_edit_options'] = 'Editar Opções';
$l['ucp_nav_change_email'] = 'Alterar Email';
$l['ucp_nav_change_pass'] = 'Alterar Password';
$l['ucp_nav_change_username'] = 'Alterar Nome de Utilizador';
$l['ucp_nav_edit_sig'] = 'Alterar Assinatura';
$l['ucp_nav_change_avatar'] = 'Alterar Avatar';
$l['ucp_nav_misc'] = 'Outras Opções';
$l['ucp_nav_editlists'] = 'Amigos/Lista de Ignorados';
$l['ucp_nav_favorite_threads'] = 'Tópicos Favoritos';
$l['ucp_nav_subscribed_threads'] = 'Tópicos Subscritos';
$l['ucp_nav_forum_subscriptions'] = 'Subscrições do Fórum';
$l['ucp_nav_drafts'] = 'Rascunhos Salcos';
$l['ucp_nav_notepad'] = 'Bloco de Notas';
$l['ucp_nav_view_profile'] = 'Visualizar Perfil';
$l['ucp_nav_home'] = 'User CP';
$l['ucp_nav_usergroups'] = 'Grupos';
$l['ucp_nav_attachments'] = 'Gerir Anexos';
$l['ucp_nav_drafts_active'] = '<strong>Rascunhos Salvos ({1})</strong>';
