<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:05:41 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = 'Perfil de {1}';
$l['nav_warning_log'] = 'Registro de Avisos';
$l['nav_add_warning'] = 'Avisar Utilizador';
$l['nav_view_warning'] = 'Detalhes do Aviso';
$l['warning_for_post'] = '.. Mensagem:';
$l['already_expired'] = 'Expirou';
$l['warning_active'] = 'Ativo';
$l['warning_revoked'] = 'Retirado';
$l['warning_log'] = 'Registo de Avisos';
$l['warning'] = 'Aviso';
$l['issued_by'] = 'Avisado por';
$l['date_issued'] = 'Data do Aviso';
$l['expiry_date'] = 'Expira';
$l['active_warnings'] = 'Avisos Activos';
$l['expired_warnings'] = 'Avisos Expirados';
$l['warning_points'] = '({1} pontos)';
$l['no_warnings'] = 'Este utilizador não recebeu quaisquer avisos ou então já foram todos removidos.';
$l['warn_user'] = 'Avisar Utilizador';
$l['post'] = 'Mensagem:';
$l['warning_note'] = 'Mensagens Administrativas:';
$l['warning_type'] = 'Tipo de Aviso:';
$l['custom'] = 'Motivo Personalizado';
$l['reason'] = 'Motivo:';
$l['points'] = 'Pontos:';
$l['warn_user_desc'] = 'Aqui pode aumentar o nível de aviso deste utilizador se violou uma ou mais regras.';
$l['send_pm'] = 'Notificar Utilizador:';
$l['send_user_warning_pm'] = 'Enviar uma mensagem privada a este utilizador, informando-o deste aviso.';
$l['send_pm_subject'] = 'Título:';
$l['warning_pm_subject'] = 'Recebeu um aviso.';
$l['send_pm_message'] = 'Mensagem:';
$l['warning_pm_message'] = 'Caro {1}

Recebeu um aviso da equipa de {2}.
--

--';
$l['expiration_never'] = 'permanente';
$l['expiration_hours'] = 'horas';
$l['expiration_days'] = 'dias';
$l['expiration_weeks'] = 'semanas';
$l['expiration_months'] = 'meses';
$l['redirect_warned_banned'] = 'O utilizador também foi movido para o grupo {1} durante {2}.';
$l['redirect_warned_suspended'] = 'Os privilégios (para criar mensagens) deste utilizador foram suspensos durante {1}.';
$l['redirect_warned_moderate'] = 'Todas as mensagens deste utilizador serão moderadas durante {1}.';
$l['redirect_warned'] = 'O nível de aviso de {1} aumentou para {2}%.{3}<br /><br />Vai agora retornar ao local onde se encontrava.';
$l['error_warning_system_disabled'] = 'Você não pode usar o sistema de avisos, porque ele foi desativado pelo administrador do fórum.';
$l['reached_max_warnings_day'] = 'Você não pode avisar ninguém, porque chegou ao limite de números de avisos, que pode dar por dia.<br /><br />O número máximo de avisos que pode dar por dia é {1}.';
$l['user_reached_max_warning'] = 'Este utilizador não pode receber avisos porque já atingiu o nível máximo de avisos.';
$l['error_cant_warn_group'] = 'Você não ter permissões para avisar utilizadores deste grupo.';
$l['error_no_note'] = 'Você não inseriu nenhuma nota administrativa para este aviso.';
$l['error_invalid_type'] = 'Você selecionou um tipo de aviso inválido.';
$l['error_invalid_user'] = 'O utilizador selecionado não existe.';
$l['error_invalid_post'] = 'A mensagem selecionada não existe.';
$l['error_cant_custom_warn'] = 'Você não tem permissões para dar avisos personalizados aos utilizadores.';
$l['error_no_custom_reason'] = 'Você não inseriu um motivo para o seu aviso personalizado.';
$l['error_invalid_custom_points'] = 'Você não inseriu um número de pontos válido a adicionar ao nível de avisos destes utilizadores. Você tem de inserir um valor numérico maior que 0 mas menor ou igual a {1}.';
$l['details'] = 'Detalhes';
$l['view'] = 'Visualizar';
$l['current_warning_level'] = 'Actual Nível de Aviso: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = 'Detalhes de Aviso';
$l['revoke_warning'] = 'Revogar este Aviso';
$l['revoke_warning_desc'] = 'Para revogar este aviso, por favor insira o motivo em baixo. Esta ação não vai remover nenhuma expulsão ou suspensão imposta por este aviso.';
$l['warning_is_revoked'] = 'Este Aviso foi revogado';
$l['revoked_by'] = 'Revogado por:';
$l['date_revoked'] = 'Data da Revogação:';
$l['warning_already_revoked'] = 'Este aviso já foi revogado.';
$l['no_revoke_reason'] = 'Você não inseriu um motivo, do porquê de querer revogar este aviso.';
$l['redirect_warning_revoked'] = 'Este aviso foi revogado com sucesso e tendo baixado os pontos de aviso dos utilizadores.<br /><br />Você vai agora retornar aos avisos.';
$l['result'] = 'Resultado:';
$l['result_banned'] = 'O Utilizador será movido para o grupo de banidos ({1}) {2}';
$l['result_suspended'] = 'Privilégios para a criação de mensagens vão ser suspensos {1}';
$l['result_moderated'] = 'Mensagens serão moderadas durante {1}';
$l['result_period'] = 'por {1} {2}';
$l['hour_or_hours'] = 'Hora(s)';
$l['day_or_days'] = 'Dia(s)';
$l['week_or_weeks'] = 'Semana(s)';
$l['month_or_months'] = 'Mes(es)';
$l['expires'] = 'Expira:';
$l['new_warning_level'] = 'Novo nível de aviso:';
$l['cannot_warn_self'] = 'Não pode adicionar um aviso a si próprio.';
$l['error_cant_warn_user'] = 'Não tem permissão para avisar este utilizador.';
$l['existing_post_warnings'] = 'Avisos/Alertas existentes para esta mensagem';
$l['details_username'] = 'Username';
$l['details_warning_note'] = 'Notas administrativas';
$l['details_reason'] = 'Motivo';
$l['send_pm_options'] = 'Opções:';
$l['send_pm_options_anonymous'] = '<strong>MP Anônima</strong>: Envie esta mensagem privada como um usuário anônimo.';
$l['redirect_warned_pmerror'] = '<br /> <br /> Por favor note que o MP não foi enviado.';
$l['result_period_perm'] = 'permanentemente';
