<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Português (Brasil)
// Author of the language pack : dthiago (MyBB User)
// Language pack translators website : http://bf4brasil.com.br
// Compatible version of MyBB : 1612
// Last edited in MyBB Editor by : Prime
// Last edited date : Wed, 28 Jun 2017 18:06:21 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Não inseriu um novo título.';
$l['post_moderation'] = 'A sua mensagem está agora sobre a avaliação de um moderador.';
$l['post_doesnt_exist'] = 'A mensagem especificada não existe.';
$l['thread_doesnt_exist'] = 'O tópico especificado não existe.';
$l['thread_closed_edit_subjects'] = 'Este tópico está fechado e por isso não pode editar títulos.';
$l['no_permission_edit_subject'] = 'Não tem permissão para editar o título deste tópico.';
$l['thread_closed_edit_message'] = 'Este tópico está fechado e por isso não pode editar as mensagens contidas nele.';
$l['no_permission_edit_post'] = 'Não tem permissão para editar esta mensagem.';
$l['edit_time_limit'] = 'Apenas poderás editar as mensagens após {1} minutos de terem sido criadas.';
$l['postbit_edited'] = 'Esta mensagem foi editada a: {1} por';
$l['save_changes'] = 'Salvar Alterações';
$l['cancel_edit'] = 'Cancelar Alterações';
$l['captcha_not_exists'] = 'A imagem de verificação que está atualizando, não existe.';
$l['captcha_valid_not_exists'] = 'A imagem de verificação que está atualizando, não existe.';
$l['captcha_does_not_match'] = 'O código da imagem de verificação que inseriu está incorreto. Por favor insira o código tal como o vê na imagem.';
$l['captcha_matches'] = 'O código da imagem de verificação que inseriu está correto.';
$l['banned_username'] = 'O nome de utilizador escolhido foi bloqueado por um administrador.';
$l['banned_characters_username'] = 'O seu nome de utilizador contém um ou mais caracteres inválidos.';
$l['complex_password_fails'] = 'A Senha requer uma letra maiúscula, letra minúscula e um número.';
$l['username_taken'] = '{1} já foi registado por outro membro';
$l['username_available'] = '{1} está livre';
$l['invalid_username'] = '{1} não é um nome de utilizador de outro membro.';
$l['valid_username'] = '{1} é uma referência válida.';
$l['buddylist_error'] = 'Parece que não tem quaisquer amigos na sua lista de amigos. Por favor adicione alguns antes de utilizar esta funcionalidade,';
$l['close'] = 'Fechar';
$l['select_buddies'] = 'Seleccionar Amigos';
$l['select_buddies_desc'] = 'Para adicionar um ou mais amigos como recipientes, seleccione-os abaixo e clique OK.';
$l['selected_recipients'] = 'Destinatários selecionados';
$l['ok'] = 'OK';
$l['cancel'] = 'Cancelar';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['edited_post'] = 'Mensagem Editada';
$l['usergroup'] = 'Grupo de Utilizadores';
$l['thread_moderation'] = 'Seu tópico agora está sob moderação.';
$l['postbit_editreason'] = 'Motivo da edição';
$l['answer_valid_not_exists'] = 'A questão que você está tentando responder não existe.';
$l['answer_does_not_match'] = 'A resposta que você digitou não está correta.';
